fix(runtime): 合并同一个customWrapper下的setData更新
NervJS/taro pull request #10148
Opened 2021-08-30 02:54 UTC by Chen-AMao

**这个 PR 做了什么?** (简要描述所做更改)
目前在使用customWrapper时发现，对于一次更新，每单个dom更新都会触发一次setData，也即N个dom元素修改会连续调用N次setData。这样对于同一个(id)customWrapper就产生了频繁调用setData的问题。尤其当涉及到动画，会导致动画的触发不在同一帧；这样的话在customWrapper内无法实现动画同步。

这个pr主要是在一次更新中，后置待更新dom信息入到更新队列的时机。通过Map（以customWrapper的id为键值）存储并合并同一个customWrapper下本次需更新的dom信息，通过调用一次setData传到视图层。

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-09-01 07:28 UTC, Chen-jj requested changes

2021-09-01 07:28 UTC, Chen-jj commented on packages/taro-runtime/src/dom/root.ts
> +                  customWrapperMap.set(customWrapperId, { ...(customWrapperMap.get(customWrapperId) || {}), [`i.${splitedPath}`]: data[p] })
可以直接用 `customWrapper` 代替 `customWrapperId` 作为 **key**

2021-09-01 07:28 UTC, Chen-jj commented on packages/taro-runtime/src/dom/root.ts
> +                ctx: ctx.selectComponent(`#${id}`),
因为是使用 `customWrapper` 作为 key，这里直接用即可，不用多次调用 `ctx.selectComponent` 了

2021-09-01 08:00 UTC, Chen-AMao commented on packages/taro-runtime/src/dom/root.ts
> +                ctx: ctx.selectComponent(`#${id}`),
好的了解，我修改一下～

2021-09-02 12:12 UTC, Chen-jj approved these changes

2021-09-02 12:29 UTC, merged