fix(runtime): page.onLoad, page.onShow
NervJS/taro pull request #10249
Opened 2021-09-09 04:24 UTC by tango5614

确保 onshow 在 onload 之后执行

**这个 PR 做了什么?** (简要描述所做更改)

hello, 我是一个小程序 runtime 开发者，在使用 taro 时，加载页面之后，遇到了 **Page的`onShow` 生命周期在 `onLoad` 之前执行**的情况。

在查看源码后，发现 `safeExecute('onLoad')` 在一个回调里执行，无法保证一定在 `safeExecute('onShow')` 之后，所以提了这个pr， 因为是自研的小程序 runtime 没有收录在下面平台里，所以没法提供复现路径，抱歉

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-09-16 15:18 UTC, Chen-jj requested changes

2021-09-16 15:18 UTC, Chen-jj commented on packages/taro-runtime/src/dsl/common.ts
> +  const hasLoaded = new Promise(resolve => { loadResolver = resolve })
请问 PR 有测试过么？这个 `hasLoaded` 的逻辑只会正确触发一次吧，第一次 `resolve` 后，相同路由的其他页面实例，因为 `hasLoaded` 已经 `resolved` 了，就直接触发了。

例如 `index -> index`

2021-09-22 02:37 UTC, tango5614 commented on packages/taro-runtime/src/dsl/common.ts
> +  const hasLoaded = new Promise(resolve => { loadResolver = resolve })
确实会有这个问题 没有测到这个case 已修改

2021-09-22 08:46 UTC, luckyadam commented on packages/taro-runtime/src/dsl/common.ts
> +          loadResolver()
有没有可能小程序 onShow 的执行在这里的回调之后，这样就无法触发 onShow 里的代码了

2021-09-22 09:50 UTC, tango5614 commented on packages/taro-runtime/src/dsl/common.ts
> +          loadResolver()
这里的回调执行后 hasLoaded 变成 resolved，onShow 事件触发时会立即执行

2021-09-27 07:35 UTC, liximomo commented
@luckyadam  any updates? same prbolem here

2021-10-15 13:19 UTC, Chen-jj commented
@tango5614 PR 还是有问题：

当 `onShow` 先执行时，`hasLoaded` 为 `undefined`，这里会报错：

```js
// can not read then of undefined
hasLoaded.then(() => {})
```

可以试试这样改：

`loadResolver`, `hasLoaded` 都挂在 `config` 上，`onShow` 和 `onLoad` 都有初始化逻辑，且优先复用：

```js
// 伪代码
const config = {
  onLoad () {
    if (isUndefined(this.hasLoaded)) {
      this.$hasLoaded = new Promise(resolve => {
        this.$loadResolver = resolve
      })
    }
    
    // at right time
    this.$loadResolver()
  },
  onShow () {
    if (isUndefined(this.hasLoaded)) {
      this.$hasLoaded = new Promise(resolve => {
        this.$loadResolver = resolve
      })
    }
    this.$hasLoaded.then(...)
  }
}
```

此改动一旦出错，可能引发很严重的线上问题，所以烦请测试完备哈~

2021-11-01 13:57 UTC, tango5614 commented
> @tango5614 PR 还是有问题：
> 
> 当 `onShow` 先执行时，`hasLoaded` 为 `undefined`，这里会报错：
> 
> ```js
> // can not read then of undefined
> hasLoaded.then(() => {})
> ```
> 
> 可以试试这样改：
> 
> `loadResolver`, `hasLoaded` 都挂在 `config` 上，`onShow` 和 `onLoad` 都有初始化逻辑，且优先复用：
> 
> ```js
> // 伪代码
> const config = {
>   onLoad () {
>     if (isUndefined(this.hasLoaded)) {
>       this.$hasLoaded = new Promise(resolve => {
>         this.$loadResolver = resolve
>       })
>     }
>     
>     // at right time
>     this.$loadResolver()
>   },
>   onShow () {
>     if (isUndefined(this.hasLoaded)) {
>       this.$hasLoaded = new Promise(resolve => {
>         this.$loadResolver = resolve
>       })
>     }
>     this.$hasLoaded.then(...)
>   }
> }
> ```
> 
> 此改动一旦出错，可能引发很严重的线上问题，所以烦请测试完备哈~

正常情况下`onShow`是不会先于`onLoad`执行的。 
我理解在taro中生命周期的调用分三步 `1.小程序framework` -> `2.taro-createPageConfig中的方法` -> `3.用户定义的生命周期`，这个issues针对的问题是`2` -> `3` 这个过程的`onShow`, `onLoad`顺序错误, 你这里指出的问题是 `1` -> `2`这个过程的问题，如果framework设计的没错的话应该是不存在这个问题的

2021-11-12 08:19 UTC, Chen-jj approved these changes

2021-11-12 08:20 UTC, merged

2021-11-12 08:20 UTC, Chen-jj commented
感谢贡献~