fix(shared): 修复 @tarojs/shared processApis 方法当 config.isOnlyPromisify…
NervJS/taro pull request #10289
Opened 2021-09-14 14:55 UTC by hannq

… 为 true 时，错误覆盖部分公共方法 fix #10288

**这个 PR 做了什么?** (简要描述所做更改)
修复 @tarojs/shared processApis 方法当 config.isOnlyPromisify 为 true 时，错误覆盖部分公共方法 fix #10288

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #10288
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-09-16 11:19 UTC, Chen-jj requested changes

2021-09-16 11:19 UTC, Chen-jj commented on packages/shared/src/native-apis.ts
> +    } else if (!config.isOnlyPromisify) {
判断应该再提前一点，如果是 `isOnlyPromisify` 的情况，就可以不处理 `global` 对象里的几百个 API 了。

修改 212 行：

```js
const apis = new Set(Object.keys(global).filter(api => preserved.indexOf(api) === -1))
```

为：

```js
const apis = new Set(
    !config.isOnlyPromisify
      ? Object.keys(global).filter(api => preserved.indexOf(api) === -1)
      : new Set(patchNeedPromiseApis)
  )
```

2021-09-16 12:21 UTC, hannq commented on packages/shared/src/native-apis.ts
> +    } else if (!config.isOnlyPromisify) {
提交了，总感觉这个 `isOnlyPromisify` 最初就是为了 `@tarojs/plugin-inject` 加的，`commit` 时间都很像，改的也比较仓促

2021-09-16 14:55 UTC, Chen-jj commented on packages/shared/src/native-apis.ts
> +    } else if (!config.isOnlyPromisify) {
> 提交了，总感觉这个 `isOnlyPromisify` 最初就是为了 `@tarojs/plugin-inject` 加的，`commit` 时间都很像，改的也比较仓促

是的，感谢贡献～

2021-09-16 14:56 UTC, Chen-jj commented
@hannq 麻烦再更新下 snapshot 哈～测试好像又挂了

2021-09-17 11:34 UTC, Chen-jj approved these changes

2021-09-17 11:34 UTC, merged

2021-09-17 11:35 UTC, Chen-jj commented
感谢贡献～