feat(harmony): 新增 button 组件
NervJS/taro pull request #10441
Opened 2021-10-18 02:10 UTC by jiaozitang

**这个 PR 做了什么?** (简要描述所做更改)
鸿蒙插件新增 button 组件

**Demo**
https://github.com/jiaozitang/taro-demo/blob/harmony-demo-button/src/pages/index/component/MyButton/index.tsx

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙

2021-11-07 03:41 UTC, jiaozitang commented on packages/taro-harmony/src/template.ts
> +    const children = this.voidElements.has(comp.nodeName) ? '' : (comp.nodeName === 'button' ? '{{i.value}}' : '<container root="{{i}}"></container>')
button 不支持 子组件，无法使用 slot

2021-11-08 00:51 UTC, jiaozitang commented on packages/taro-harmony/src/template.ts
> +    const children = this.voidElements.has(comp.nodeName) ? '' : (comp.nodeName === 'button' ? '{{i.value}}' : '<container root="{{i}}"></container>')
button 不支持 子组件，无法使用 slot

2021-11-08 00:52 UTC, jiaozitang commented on packages/taro-harmony/src/template.ts
> +    const children = this.voidElements.has(comp.nodeName) ? '' : (comp.nodeName === 'button' ? '{{i.value}}' : '<container root="{{i}}"></container>')
通过props的方式，可以接受传value参数的方式显示文本吗？

2021-11-08 01:04 UTC, jiaozitang commented on packages/taro-harmony/src/components/components-harmony/button/index.js
> +    this.$emit('click', { id: this.id })
harmony button 不支持 tap 事件，文档：https://developer.harmonyos.com/cn/docs/documentation/doc-references/js-components-common-events-0000001051151132#ZH-CN_TOPIC_0000001173324611__tdb541af4e4db41d7a92e9b6e3c93f606

2021-11-08 01:41 UTC, jiaozitang commented on packages/taro-harmony/src/components/components-harmony/button/index.js
> +    this.$emit('click', { id: this.id })
未找到解决方案，暂时把自定义组件内 onClick 的逻辑删除了

2021-11-08 14:05 UTC, Chen-jj commented on packages/taro-harmony/src/template.ts
> +    const children = this.voidElements.has(comp.nodeName) ? '' : (comp.nodeName === 'button' ? '{{i.value}}' : '<container root="{{i}}"></container>')
把 `i.cn` 作为 props 传递给 `taro-button`，然后分析所有文本内容设置为 value

```html
<taro-button cn="{{i.cn}}"></taro-button>
```

```js
export default createOption({
  props: {
    cn: []
  },
  computed: {
    value () {
      return getValueFrom(this.cn)
    }
  }
}
```

2021-11-08 14:11 UTC, Chen-jj commented
按钮没有高度：

![image](https://user-images.githubusercontent.com/11807297/140756699-2df12261-c7f7-4de8-ae3f-ec1e7fc2e50a.png)

2021-11-08 14:18 UTC, Chen-jj requested changes

2021-11-08 14:18 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/button/index.css
> +button {
按钮没有高度：

![image](https://user-images.githubusercontent.com/11807297/140756699-2df12261-c7f7-4de8-ae3f-ec1e7fc2e50a.png)

2021-11-08 14:18 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/button/index.css
> +  width: 100px;
mini 的样式和微信规范的没有对齐吧

2021-11-08 14:26 UTC, Chen-jj requested changes

2021-11-08 14:26 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/button/index.hml
> +    @touchstart="{{onTouchStart}}"
事件绑定语法错了

2021-11-08 14:36 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/button/index.js
> +    this.$emit('click', { id: this.id })
不是 `<button>` 绑定 `tap` 事件，是监听到 `click` 事件后 emit `tap` 事件，同时组件模板需要绑定 `tap` 事件，eventHandler 需要判断把 button 的 event.type 从 `tap` 改为 `click`

2021-11-11 07:58 UTC, Chen-jj requested changes

2021-11-11 07:58 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/button/index.js
> +    if (this.disabled) {
`button` 设置了 `disabled` 后就不会触发 touchstart touchend 了，这里不需要再判断，下同

2021-11-11 07:58 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/button/index.js
> +    type: 'capsule',
1. 默认值写法错误：https://developer.harmonyos.com/cn/docs/documentation/doc-references/js-components-custom-props-0000000000611785#section44865584311
2.  模板给予 type 默认值：`type="{{i.type===undefined?'default':i.type}}"`

2021-11-11 07:58 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/button/index.js
> +    this.$trigger('touchstart')
自定义组件派发的 `touchstart` 事件目前会被 ban 掉。所以暂时不用派发了，`touchend` 一样。

2021-11-11 07:58 UTC, Chen-jj commented on packages/taro-harmony/src/runtime-utils.ts
> +      event.type = 'click'
tap 是对的，不需要改为 click 了

2021-11-11 11:49 UTC, Chen-jj requested changes

2021-11-11 11:49 UTC, Chen-jj commented on packages/taro-harmony/src/template.ts
> +    result.button.cn = 'i.cn'
```js
createMiniComponents (components): any {
  components.Button.cn = ''
  components.Button.bindtap = ''
  components.Button.type = "'default'"

  const result = super.createMiniComponents(components)

  delete result['pure-view']
  delete result['static-view']
  delete result['static-text']
  delete result['static-image']

  return result
}
```

2021-11-11 11:58 UTC, Chen-jj approved these changes

2021-11-11 11:58 UTC, merged