Feat/harmony progress com
NervJS/taro pull request #10442
Opened 2021-10-18 02:51 UTC by huozhongyi123

**这个 PR 做了什么?** (简要描述所做更改)
增加progress组件在鸿蒙适配里面

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-10-19 04:07 UTC, huozhongyi123 commented
@Chen-jj 已修复完成

2021-11-01 02:18 UTC, huozhongyi123 commented
@Chen-jj 已解决

2021-11-01 07:27 UTC, Chen-jj requested changes

2021-11-01 07:27 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/progress/index.js
> +    'borderRadius',
`borderRadius` `active` `activeMode` `duration` 鸿蒙好像不支持？不支持的话就不需要接这些 props 了~

2021-11-01 09:33 UTC, huozhongyi123 commented
@Chen-jj 已修复

2021-11-03 02:27 UTC, Chen-jj approved these changes

2021-11-03 02:28 UTC, merged