Feat/harmony interactive api
NervJS/taro pull request #10453
Opened 2021-10-19 04:26 UTC by huozhongyi123

**这个 PR 做了什么?** (简要描述所做更改)
增加适配鸿蒙的交互的api
案例 https://github.com/huozhongyi123/taro-harmony-react/blob/main/src/pages/index/index.jsx
`showLoading`和`hideLoading `目前不支持

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙（harmony）

2021-10-19 04:29 UTC, huozhongyi123 commented
@luckyadam @Chen-jj 适配鸿蒙交互api已完成

2021-11-01 02:26 UTC, huozhongyi123 commented
@Chen-jj 已完成，hidetoast目前方案看着没问题，loading看以后用自定义组件试试

2021-11-01 08:47 UTC, Chen-jj requested changes

2021-11-01 08:47 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +    resolve(null)
异步方法除了返回 promise 对象，还需要调用 `success` `fail` `complete`(如果肯定能成功，可以不调用 `fail`)。

并且，**参数需要遵循微信的规范**，不建议直接 `resolve(null)`，可以起一个微信小程序 demo 看异步回调携带的参数各是什么内容。

最后，`utils` 里有处理异步回调的 `callAsyncSuccess` `callAsyncFail` 方法，详情请参考 `navbar` API。

2021-11-01 08:47 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +    resolve(null)
请按微信规范处理异步回调，见 `showToast` 下的评论

2021-11-01 08:47 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +const noop = () => {}
`utils` 里有 `noop`

2021-11-01 08:47 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +    success: (data) => {
1. 参数遵循微信规范
2. 以正确的逻辑顺序处理 `resolve` `reject` `success` `fail` `complete` 的触发

2021-11-01 08:47 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +    title: 'Title Info',
不需要传入

2021-11-01 08:47 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +      success(data)
同上，请正确处理异步回调

2021-11-04 06:25 UTC, Chen-jj requested changes

2021-11-04 06:25 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +    success: noop,
这些方法在 `callAsyncSuccess ` 里已经有判空逻辑，不需要默认值

2021-11-04 06:25 UTC, Chen-jj commented on packages/taro-harmony/src/apis/interactive/index.ts
> +          return resolve(options.success(
promise 逻辑还是不对，现在 resolve 了 options.success 的返回值

2021-11-09 06:13 UTC, Chen-jj approved these changes

2021-11-09 06:13 UTC, merged