feat(harmony): 新增input组件
NervJS/taro pull request #10517
Opened 2021-10-28 06:04 UTC by troy-sxj

**这个 PR 做了什么?** (简要描述所做更改)
新增Taro适配harmony Input组件

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙（harmony）

**组件测试代码：**
```
import {Component} from 'react'
import {Input, Text, View} from '@tarojs/components'
import './index.scss'

export default class Index extends Component {

  constructor(props) {
    super(props);
    this.bindInput = this.bindInput.bind(this)
  }

  state ={
    value: 'defaultValue'
  }

  render() {
    return (
      <View className='block'>

        <Text className='input-title'>可以自动聚焦的 input</Text>
        <Input
          id='input1'
          type='text'
          placeholder='将会获取焦点'
          focus='true'
          onFocus={this.bindFocus}
          onBlur={this.bindBlur}
          onConfirm={this.bindConfirm}
          onKeyboardHeightChange={this.bindKeyboardHeightChange}
        />

        <Text className='input-title'>控制最大输入长度的 input</Text>
        <Input id='input2' type='text' placeholder='最大输入长度为 10' maxlength='10' />

        <Text className='input-title'>实时获取输入值：{this.state.value}</Text>
        <Input id='input3' type='text' value={this.state.value} onInput={this.bindInput} placeholder='输入同步到view中' />

        <Text className='input-title'>数字输入的 input</Text>
        <Input id='input4' type='number' placeholder='这是一个数字输入框' />

        <Text className='input-title'>密码输入的 input</Text>
        <Input id='input5' type='text' password placeholder='这是一个密码输入框' />

        <Text className='input-title'>控制占位符颜色的input</Text>
        <Input id='input6' type='text'  placeholder='占位符字体是红色的' placeholder-color='#F76260' />
      </View>
    )
  }

  bindInput(e) {
    console.log("[Input] bindInput === e:" + JSON.stringify(e))
    this.setState({
      value: e.detail.value
    })
  }

  bindFocus(e) {
    console.log("[Input] bindFocus === e:" + JSON.stringify(e))
  }

  bindBlur(e) {
    console.log("[Input] bindBlur === e:" + JSON.stringify(e))
  }

  bindConfirm(e) {
    console.log("[Input] bindConfirm === e:" + JSON.stringify(e))
  }

  bindKeyboardHeightChange(e) {
    console.log("[Input] bindKeyboardHeightChange === e:" + JSON.stringify(e))
  }

}
```
样式：
```
.block{
  display: flex;
  flex-direction: column;
  padding: 4px;
}

.input-title{
  font-size: 20px;
  margin-top: 10px;
  margin-bottom: 4px;
}
```

2021-10-31 09:18 UTC, troy-sxj commented
改动点：
1. 代码缩进调整
2. 处理input value

2021-11-01 06:10 UTC, Chen-jj requested changes

2021-11-01 06:11 UTC, Chen-jj commented
@troy-sxj 还有一点小细节麻烦调整一下哈

2021-11-01 07:34 UTC, Chen-jj approved these changes

2021-11-01 07:34 UTC, Chen-jj commented
感谢贡献~

2021-11-01 07:34 UTC, merged