Feat/harmony textare
NervJS/taro pull request #10548
Opened 2021-11-02 03:20 UTC by huozhongyi123

**这个 PR 做了什么?** (简要描述所做更改)

适配鸿蒙的textarea组件

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙（harmony）

2021-11-03 03:13 UTC, Chen-jj requested changes

2021-11-03 06:36 UTC, Chen-jj requested changes

2021-11-03 06:36 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.js
> +    textareaValue: '',
这个 `textareaValue` 好像没有放在 data 保存的必要？

2021-11-03 06:36 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.hml
> +  extend="{{autoHeight}}"
这里搞错了吧，没有这个 props

2021-11-03 06:36 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.hml
> +  headericon="{{headericon}}"
和 props 里的属性名不一致

2021-11-03 06:36 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.js
> +    'selectionStart',
`selectionStart` 驼峰 props 对应模板的 `selection-start`，而你在模板里绑定的是 `selectionstart`

2021-11-03 12:31 UTC, huozhongyi123 commented on packages/taro-harmony/src/components/components-harmony/textarea/index.js
> +    'selectionStart',
selectedstart="{{selectionStart}}" taro和鸿蒙的字段不一样

2021-11-09 07:22 UTC, Chen-jj requested changes

2021-11-09 07:22 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.js
> +    'auto-focus',
props 是驼峰写法

2021-11-09 07:22 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.hml
> +  extend="{{auto-height}}"
props 改驼峰后，此处对应修改

2021-11-09 07:22 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.js
> +    'auto-focus',
应该补上 disabled 的支持

2021-11-09 07:27 UTC, Chen-jj requested changes

2021-11-09 07:27 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/textarea/index.js
> +    textareaValue: '',
`textareaValue` 还需要考虑初始值、同步 props.value 的变更

2021-11-09 11:10 UTC, merged