Feat/harmony picker
NervJS/taro pull request #10559
Opened 2021-11-02 13:04 UTC by AdvancedCat

**这个 PR 做了什么?** (简要描述所做更改)

新增鸿蒙组件picker

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙（Harmony）

组件测试代码：
https://github.com/AdvancedCat/taro-harmony-react/blob/master/src/pages/picker/index.jsx

2021-11-03 08:43 UTC, Chen-jj requested changes

2021-11-03 08:43 UTC, Chen-jj commented
@AdvancedCat 

我列一下我认为正确的 demo 测试结果：

selector: 显示 2，默认选中 4
selector RK: 显示 小明，默认选中 小明
multi: 显示 bef，默认选中 aeg
multi RK: 显示 AEG，默认选中 AEG
time: 显示 12:30，默认选中 12:30
date: 显示 2021-11-11，默认选中 2021 11 11
date: 显示 ，默认选中 2021-11-11-13-13

2021-11-04 08:45 UTC, AdvancedCat commented
@Chen-jj 
代码已调整，经测试，demo中展示的效果如下：

selector: 显示 4，默认选中 2
selector RK: 显示 小明，默认选中 小明
multi: 显示 aeg，默认选中 bef
multi RK: 显示 AEG，默认选中 AEG
time: 显示 12:30，默认选中 当前时间(API6)  / 12:30(API7)
date: 显示 2021-11-11，默认选中 2021 11 11
datetime: 显示 2021-11-11-13-13，默认选中 2021-12-12-10-10

关于time类型的默认值，经测试，在API6中仍是当前时间，在API7中则为value的值，华为论坛讨论如下：
https://developer.huawei.com/consumer/cn/forum/topic/0201697213296960929?fid=0101587866109860105

Taro组件无selected属性，因此在Taro组件中传入selected属性时仍按照鸿蒙组件的解释，即selected代表弹窗时的默认值.

请指正。

2021-11-04 12:50 UTC, AdvancedCat commented
调整了部分代码逻辑：
- 去除selected属性的传入，取this.value为鸿蒙selected；
- 在不同type的if语句中直接return，降低复杂度；

Taro组件的value与鸿蒙value描述不一致，先以Taro组件为准，如果开发者需要自定义selected或者自定义鸿蒙value的需求，后续再提PR。

2021-11-08 13:05 UTC, Chen-jj requested changes

2021-11-09 02:06 UTC, Chen-jj requested changes

2021-11-10 16:31 UTC, closed without merging