feat(h5): cover-image组件
NervJS/taro pull request #10606
Opened 2021-11-08 08:58 UTC by jiaozitang

**这个 PR 做了什么?** (简要描述所做更改)
h5端新增cover-image组件

**Demo**
https://github.com/jiaozitang/taro-demo/tree/h5-demo-cover-image

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-11-11 13:43 UTC, Chen-jj requested changes

2021-11-11 13:43 UTC, Chen-jj commented on packages/taro-components/src/components/cover-view/cover-image.tsx
> +    console.log(Host)
这几行 log 可以去掉

2021-11-11 13:43 UTC, Chen-jj commented
@jiaozitang 有空补充一下测试用例咯

2021-11-16 00:52 UTC, jiaozitang commented
> @jiaozitang 有空补充一下测试用例咯

done

2021-11-22 08:07 UTC, Chen-jj approved these changes

2021-11-23 01:42 UTC, merged

2021-12-06 14:03 UTC, jiaozitang commented
fix #8504