feat(): add system api in taro-harmony
NervJS/taro pull request #10618
Opened 2021-11-09 12:26 UTC by LuMeiling

**这个 PR 做了什么?** (简要描述所做更改)
在packages/taro-harmony 增加了system的相关api

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙App

2021-11-11 08:10 UTC, Chen-jj requested changes

2021-11-11 08:10 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +        success && (typeof success == 'function') && success(res)
`utils` 里有工具函数处理异步回调。

2021-11-11 08:10 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +interface IOptionsShape extends IAsyncParams {
API 的类型可以直接从 Taro 取，请参考 navbar API

2021-11-14 08:20 UTC, LuMeiling commented on packages/taro-harmony/src/apis/system/index.ts
> +        success && (typeof success == 'function') && success(res)
代码已修改使用utils里的工具函数处理异步回调

2021-11-14 08:22 UTC, LuMeiling commented on packages/taro-harmony/src/apis/system/index.ts
> +interface IOptionsShape extends IAsyncParams {
已增加apid类型 辛苦查看 commitid：88c948d 和 commitid：c2c9189

2021-11-25 07:51 UTC, Chen-jj requested changes

2021-11-25 07:51 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +        isConnected: data.metered,
这里的逻辑是否有问题？感觉处理 `data.type === none` 时，才是 false，其余都是 true。现在取  `data.metered` 的话，连着 wifi 也返回 `isConnected: false`

2021-11-25 07:51 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +      brightness.getValue({
`setValue` 吧

2021-11-25 07:51 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +    if(!isString(phoneNumber) || isUndefined(phoneNumber) || isNull(phoneNumber)){
`!isString` 这个判断就够了吧？

2021-11-25 07:51 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +interface IOptionsShape extends IAsyncParams {
为什么下列几个 API 有不同的参数，这里还是定义同一个 Option Interface 的？

2021-11-29 06:31 UTC, Chen-jj requested changes

2021-11-29 06:31 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +import type Taro from '@tarojs/taro'
`import type` 放普通 `import` 之后，且两者之间空一行咯

2021-11-29 06:31 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +const offNetworkStatusChange: OffNetworkStatusChange = function () {
需要处理 `cb`：

![image](https://user-images.githubusercontent.com/11807297/143817852-eb80beea-c318-4edb-bdd7-d854aa1b9dd9.png)

2021-11-29 06:31 UTC, Chen-jj commented on packages/taro-harmony/src/apis/system/index.ts
> +      res.networkType = data.type
没有必要把 res 放到外层作用域去定义。而且，现在这样写逻辑是错的：试想先触发了一次 fail，再触发一次 success 的情况。

这样就好：

```js
// success
const res = {
  networkType: data.type,
  isConnected: data.type !== 'none'
}
// fail 同理
```

2021-11-29 08:26 UTC, Chen-jj approved these changes

2021-11-29 08:27 UTC, merged