feat(harmony): 完成用户相关api
NervJS/taro pull request #10614
Opened 2021-11-09 07:18 UTC by troy-sxj

**这个 PR 做了什么?** (简要描述所做更改)
新增harmony 用户相关api

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙APP

**测试代码:**
```
import {Component} from 'react'
import Taro from '@tarojs/taro'
import {Text, View} from '@tarojs/components'
import './index.scss'

export default class Index extends Component {

  constructor(props) {
    super(props);

    this.login = this.login.bind(this)
    this.getUserInfo = this.getUserInfo.bind(this)
    this.getUserProfile = this.getUserProfile.bind(this)
    this.authorize = this.authorize.bind(this)
    this.getSetting = this.getSetting.bind(this)
    this.openSetting = this.openSetting.bind(this)
  }
  
  render() {
    return (
      <View className='container'>

        <view className='div-button'>
          <Text className='button' onClick={this.login}>login</Text>
          <Text className='button' onClick={this.getUserInfo}>getUserInfo</Text>
          <Text className='button' onClick={this.getUserProfile}>getUserProfile</Text>
          <Text className='button' onClick={this.authorize}>authorize</Text>
          <Text className='button' onClick={this.getSetting}>getSetting</Text>
          <Text className='button' onClick={this.openSetting}>openSetting</Text>
        </view>

      </View>
    )

  }

  login() {
    Taro.login({
      success: (res) => {
        console.log('TaroApi:login == success: ' + JSON.stringify(res))
      },
      fail: (res) => {
        console.log('TaroApi:login == fail: ' + JSON.stringify(res))
      },
      complete: () => {
        console.log('TaroApi:login == complete')
      }
    })
  }

  getUserInfo() {
    Taro.getUserInfo({
      success: (res) => {
        console.log('TaroApi:getUserInfo == success: ' + JSON.stringify(res))
      },
        fail: (res) => {
        console.log('TaroApi:getUserInfo == fail: ' + JSON.stringify(res))
      },
        complete: () => {
        console.log('TaroApi:getUserInfo == complete')
      }
    })
  }

  getUserProfile() {
    Taro.getUserProfile({
      success: (res) => {
        console.log('TaroApi:getUserProfile == success: ' + JSON.stringify(res))
      },
      fail: (res) => {
        console.log('TaroApi:getUserProfile == fail: ' + JSON.stringify(res))
      },
      complete: () => {
        console.log('TaroApi:getUserProfile == complete')
      }
    })
  }

  authorize() {
    Taro.authorize()
  }

  getSetting() {
    Taro.getSetting()
  }

  openSetting() {
    Taro.openSetting()
  }
}
```

样式代码：
```
.container {
  flex-direction: column;
  justify-content: flex-start;
  margin-top: 20px;
  margin-left: 10px;
  margin-right: 10px;
}

.div-button {
  flex-direction: column;
}

.button{
  font-size: 16px;
  margin-left: 20px;
  margin-right: 20px;
  margin-top: 15px;
  background-color: #F2F2F2;
  text-color: #0D81F2;
}
```

2021-11-09 08:35 UTC, Chen-jj requested changes

2021-11-09 08:35 UTC, Chen-jj commented on packages/taro-harmony/src/program.ts
> +          '@hmscore/hms-jsb-account': 'commonjs @hmscore/hms-jsb-account'
这里不需要加，加了会保留 `require('@hmscore/hms-jsb-account')`，但其实应该把这个包打包进 webpack 产物中。因为在鸿蒙的目录结构下是找不到这个依赖的。

2021-11-12 02:20 UTC, troy-sxj commented on packages/taro-harmony/src/program.ts
> +          '@hmscore/hms-jsb-account': 'commonjs @hmscore/hms-jsb-account'
调整program逻辑，新增宿主项目package.json update

2021-11-12 08:28 UTC, Chen-jj approved these changes

2021-11-12 08:28 UTC, merged