Feat/harmony form
NervJS/taro pull request #10640
Opened 2021-11-12 08:18 UTC by crazyonebyone

**这个 PR 做了什么?** (简要描述所做更改)
鸿蒙兼容Form组件

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙应用（harmony）

2021-11-25 14:19 UTC, Chen-jj commented
提供一下测试用例

2021-12-05 12:51 UTC, crazyonebyone commented
> 

已提供

2021-12-06 06:51 UTC, Chen-jj requested changes

2021-12-06 06:51 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/input/index.js
> +    name: String,
需要为其余表单组件也补上 name 属性

2021-12-06 15:53 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/input/index.js
> +    name: String,
radio、checkbox 加一下，其余的表单组件我和鸿蒙侧对一下

2021-12-07 10:21 UTC, Chen-jj approved these changes

2021-12-07 10:22 UTC, merged