Harmony xueshuai
NervJS/taro pull request #10665
Opened 2021-11-15 11:33 UTC by xueshuai

**这个 PR 做了什么?** (简要描述所做更改)
使用 HarmonyOS 原生写法实现微信小程序规范的位置服务相关 API。
已实现 API：wx.offLocationChange，wx.getLocation，wx.onLocationChange，wx.stopLocationUpdate，wx.startLocationUpdate
不支持实现 API：wx.startLocationUpdateBackground，wx.onLocationChangeError，wx.offLocationChangeError，wx.openLocation，wx.choosePoi，wx.chooseLocation

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙（harmony）

2021-11-25 13:36 UTC, Chen-jj requested changes

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +import { General } from '@tarojs/taro'
更新一下最新的代码。

类型不需要自己定义，可以从 `@tarojs/taro` 中获取，可以参考 navbar API，例如：

```ts
type GetLocation = typeof Taro.getLocation

export const getLocation: GetLocation = function () {}
```

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +        success && success(locationWX)
`resolve`、回调函数的触发，在 `utils` 里有工具函数 `callAsyncSuccess` 和 `callAsyncFail`，可以参考其它 API 的实现来修改。

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +const geolocation = require('@ohos.geolocation')
Github Harmony API Discussion 中备注一下 API7+ 才支持，方便之后补充入文档

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +interface LocationRequest {
类型定义放文件开头

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +  type !== undefined && (params.type = type)
`@tarojs/shared` 里有 `isUndefined` 工具函数

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +  type !== undefined && (params.type = type)
另外我觉得是不是这样就行：

```ts
const params: IGetOHOSGeolocationParams = {
  type,
  altitude,
  isHighAccuracy,
  highAccuracyExpireTime
}
```

因为传入 `undefined` 应该也没关系

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/utils/index.ts
> +export function validateGeolocationOptions (funcName, options: any): {
这个函数和 `validateOptions` 有很多重复的部分，是不是应该改造 `validateOptions` 而不是新建一个工具函数

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +export function onLocationChange (options: GeoCallback = {}) {
`onLocationChange` 参数是 function，这里实现错了吧：

https://developers.weixin.qq.com/miniprogram/dev/api/location/wx.onLocationChange.html

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +export function offLocationChange (options: GeoCallback = {}) {
同 `onLocationChange`

2021-11-25 13:36 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +  return geolocation.on('locationServiceState', (err: any, state: boolean) => {
确认它和 `startLocationUpdate ` 作用一样吗，感觉不一样

![image](https://user-images.githubusercontent.com/11807297/143451109-0223916c-f595-425b-b15b-9b0681537f41.png)

![image](https://user-images.githubusercontent.com/11807297/143450999-b9c70ba3-d77c-49b3-8ebe-6342a7337757.png)

2021-11-27 14:11 UTC, xueshuai commented
测试demo
[test-demo.txt](https://github.com/NervJS/taro/files/7611847/test-demo.txt)

2021-11-29 07:56 UTC, Chen-jj requested changes

2021-11-29 07:56 UTC, Chen-jj commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +import type Taro from '@tarojs/taro'
`import type` 放普通 `import` 之后，且两者之后都需要空一行咯

2021-11-29 07:56 UTC, Chen-jj commented on packages/taro-harmony/src/apis/utils/index.ts
> +  resolve && resolve(res)
resolve 必定存在，不需要修改

2021-11-29 07:56 UTC, Chen-jj commented on packages/taro-harmony/src/apis/utils/index.ts
> +  reject && reject(res)
同上

2021-11-29 07:56 UTC, Chen-jj commented on packages/taro-harmony/src/apis/utils/index.ts
> +  const params = [{
这些需要校验的参数应该是外部调用方传进来，而不是工具函数内定义。

2021-11-29 13:20 UTC, xueshuai commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +export function onLocationChange (options: GeoCallback = {}) {
这个代码里已经改了，这里没有变

2021-11-29 13:21 UTC, xueshuai commented on packages/taro-harmony/src/apis/geolocation/index.ts
> +export function offLocationChange (options: GeoCallback = {}) {
同onLocationChange

2021-12-02 12:20 UTC, Chen-jj approved these changes

2021-12-02 12:20 UTC, merged