Feat/harmony navigator com
NervJS/taro pull request #10664
Opened 2021-11-15 08:57 UTC by huozhongyi123

**这个 PR 做了什么?** (简要描述所做更改)

鸿蒙适配中增加navigator组件
demo: https://github.com/huozhongyi123/taro-harmony-react/blob/main/src/pages/navigater/index.jsx

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙（harmony）

2021-11-25 08:25 UTC, Chen-jj requested changes

2021-11-25 08:25 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/navigator/index.js
> +    cls: {
不需要通过 `cls` 传递 class 了，鸿蒙会自己处理

2021-11-25 08:25 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/navigator/index.js
> +  props: {
需要增加对 `delta` 参数的支持

2021-11-25 08:25 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/navigator/index.hml
> +  class="{{cls}} {{clsHover}}"
去掉 `{{cls}}`

2021-11-25 08:25 UTC, Chen-jj commented on packages/taro-harmony/src/components/components-harmony/navigator/index.js
> +    const params = this.queryToJson(queryString)
`@tarojs/shared` 里有 `queryToJson` 工具函数可以直接使用，可以参考 router api 的实现代码

2021-11-27 06:31 UTC, huozhongyi123 commented
@Chen-jj 已修复。   delta参数鸿蒙中没有返回几级，只能退回某个路由链接下面，目前无法实现。 queryToJson 无法经过@tarojs/shared。组件的文件没有经过编译。

2021-11-29 05:43 UTC, merged