Feat/h5 textarea
NervJS/taro pull request #10681
Opened 2021-11-18 02:07 UTC by jiaozitang

**这个 PR 做了什么?** (简要描述所做更改)
修复issue https://github.com/NervJS/taro/issues/8003 https://github.com/NervJS/taro/issues/7997

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #8003 #7997
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-11-22 08:36 UTC, Chen-jj requested changes

2021-11-22 08:36 UTC, Chen-jj commented on packages/taro-components/src/components/textarea/style/index.scss
> +  line-height: 12px;
`line-height` 使用数字会比 px 好点吧？例如 `1.5`。这样用户使用 `font-size` 时能改变高度。

2021-11-22 09:10 UTC, Chen-jj approved these changes

2021-11-22 09:10 UTC, merged

2023-08-02 09:41 UTC, JHaoW commented
2023年了，为什么autoHeight还是无效。。。
 "@tarojs/components": "3.6.9-alpha.15",
"@tarojs/react": "3.6.9-alpha.15",
"@tarojs/runtime": "3.6.9-alpha.15",
"@tarojs/shared": "3.6.9-alpha.15",
"@tarojs/taro": "3.6.9-alpha.15",