Feat/harmony picker view
NervJS/taro pull request #10708
Opened 2021-11-22 12:13 UTC by AdvancedCat

**这个 PR 做了什么?** (简要描述所做更改)

新增鸿蒙组件 picker-view

测试代码
https://github.com/AdvancedCat/taro-harmony-react/blob/master/src/pages/picker-view/index.jsx

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙（Harmony）

2021-11-22 12:26 UTC, AdvancedCat commented
@Chen-jj 

1. range属性与PickerViewColumn
鸿蒙原生picker-view仅支持以range属性传入候选词，因此在实现上优先读取range属性；无range属性则会尝试解析子节点；

2. 深度遍历子节点
目前仅考虑了最简单的情况：「最多4层」&「优先遍历左子树」
```html
<PickerViewColumn>
     <View>
          <Text>1</Text>
     </View>
     <View>
         <Text>2</Text>
     </View>
     <View>
         <Text>3</Text>
     </View>
     <View>
         <Text>4</Text>
      </View>
</PickerViewColumn>
```
如上提取到候选词 [1, 2, 3, 4]

3. PickerView可以不传mode属性，将根据range字段动态区分组件子类型

如有问题，请指正

2021-11-25 14:17 UTC, Chen-jj requested changes

2021-11-25 14:17 UTC, Chen-jj commented
老哥稳！

2021-11-26 02:42 UTC, Chen-jj approved these changes

2021-11-26 02:42 UTC, merged