fix: taro-plugin-html genAttrMapFnFromDir
NervJS/taro pull request #10812
Opened 2021-12-03 07:54 UTC by Yang03

**这个 PR 做了什么?** (简要描述所做更改)

在运行时 React 组件`textArea`设置了 `autoFocus`, 会导致运行错误，
因为 判断 `key` 是否在 `map`中先把 `key` `toLowerCase`
但是取值的时候的 `key` 没有 `toLowerCase`

```
VM1157:10 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at fn (<anonymous>:10:26)
    at <anonymous>:22:13

```
**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-12-09 14:25 UTC, Chen-jj requested changes

2021-12-10 06:11 UTC, Yang03 commented on packages/taro-plugin-html/src/constant.ts
> +    key = key.toLowerCase();
ok

2021-12-10 09:31 UTC, Chen-jj approved these changes

2021-12-10 09:31 UTC, Chen-jj commented
稳！感谢贡献~

2021-12-10 11:24 UTC, merged