Harmony network
NervJS/taro pull request #10822
Opened 2021-12-05 10:31 UTC by xueshuai

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [x] 鸿蒙 OpenHarmony

2021-12-05 10:33 UTC, xueshuai commented
测试page
[harmony-test-network-page.text.zip](https://github.com/NervJS/taro/files/7655676/harmony-test-network-page.text.zip)

2021-12-06 03:09 UTC, Chen-jj requested changes

2021-12-06 03:09 UTC, Chen-jj commented on packages/taro-harmony/src/apis/network/request.ts
> +        header: data.header
`header` 需要处理成 Object

2021-12-07 11:13 UTC, Chen-jj approved these changes

2021-12-07 11:13 UTC, merged