fix(runtime): CustomWrapper 嵌套使用后失效
NervJS/taro pull request #10873
Opened 2021-12-09 13:30 UTC by CS-Tao

**这个 PR 做了什么?**

- 修复 #10872

**这个 PR 是什么类型?**

- [x] 错误修复(Bugfix) issue id #10872
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-12-10 17:49 UTC, Chen-jj requested changes

2021-12-10 17:49 UTC, Chen-jj commented on packages/taro-runtime/src/utils/index.ts
> +export const customWrapperCache = (function () {
缓存稍微有点麻烦，理解你想根据 id 缓存自定义组件实例的目的，但现在的实现是有问题的。

WeakMap 不影响垃圾回收的是 key 而不是 value。

现在 key 是永久放在 _customWrapperRefIdCache 里的一个对象 `{.current: id }`，代表这些 WeakMap 的 key 永久存在，因此 value（自定义组件实例）也得不到释放。

因此，这种需求下 WeakMap 其实发挥不了作用，你可以在 CustomWrapper 的 `attached` 和 `detached` 生命周期中手动管理缓存。

2021-12-11 03:51 UTC, CS-Tao commented on packages/taro-runtime/src/dom/root.ts
>              let hasCustomWrapper = false
我不确定当查询不到 customWrapper 时应该放弃更新这份数据，还是把数据交给其 parent CustomWrapper 或 page 执行 setData；我感觉放弃更新这份数据会更合理，目前的改动是这么实现的

在查询 customWrapper 时，如果循环被 break，此时会出现 hasCustomWrapper = true，但 customWrapper = null 的情况，如果使用 customWrapper 来判断，那么这份数据更新会被记入 normalUpdate 中；事实上我希望放弃更新这份数据

2021-12-11 03:51 UTC, CS-Tao commented on packages/taro-runtime/src/dom/root.ts
> +            for (let i = 1; i < dataPathArr.length; i++) {
嗯明白了，我改一下

2021-12-11 03:51 UTC, CS-Tao commented on packages/taro-runtime/src/utils/index.ts
> +export const customWrapperCache = (function () {
嗯好的，我对 WeakMap 的机制有些误解，我按你的建议改一下缓存机制

2021-12-13 11:46 UTC, CS-Tao commented on packages/taro-runtime/src/dom/root.ts
> +            for (let i = 1; i < dataPathArr.length; i++) {
@Chen-jj 这里我尝试了一下，因为 customWrapperId 是通过 `data.uid` 确定的，而 data 来自于 Parent CustomWrapper 或 page，从后往前推无法确定 data 是什么，同时无法正确判断 `getData.nn === CUSTOM_WRAPPER`；如果按照之前的逻辑使用 page 的 data 来判断是否为 CustomWrapper，那么只有 page 下的第一层 CustomWrapper 会被检测到，还是无法解决嵌套的问题

从前往后推，可以一步步更新 curCtx 和 curData，结合缓存，性能不会收到影响

2021-12-13 12:11 UTC, CS-Tao commented on packages/taro-runtime/src/dom/root.ts
>              let hasCustomWrapper = false
我发现当 CustomWrapper 在 attached 和 detached 生命周期中管理 cache 后，不会存在查询不到 customWrapper 的情况了，这里可以调整为使用 customWrapper 来判断

2021-12-13 13:38 UTC, CS-Tao commented on packages/taro-runtime/src/utils/index.ts
> +export const customWrapperCache = (function () {
缓存机制已更新，在 `createRecursiveComponentConfig` 添加了管理缓存的逻辑

2021-12-13 13:55 UTC, CS-Tao commented
@Chen-jj  更新了一版 https://github.com/NervJS/taro/pull/10873/commits/4adbc49981098daab56082632f0026bc6ee85027
- 修改了 CustomWrapper 缓存机制：在 attached 和 detached 生命周期中管理缓存
- 考虑到 data 只能从 parent CustomWrapper 或 page 实例中获取，仍然采用了从前往后遍历 custom-wrapper 实例
- 因为在部分终端（比如飞书开发工具的远程调试，不确定原因，感觉和远程调试时的 attached 执行时机有关）存在无法获取到 CustomWrapper 实例的情况，添加了警告日志并放弃对该 CustomWrapper setData

相关改动已在我们项目（飞书平台的小程序）中完成测试

2021-12-16 15:33 UTC, CS-Tao commented
改了一版，上一版在我们项目中发现会存在卡顿的问题，还是得采取从后往前寻找 CustomWrapper 的方式

我从头改了一下，主要改了两个地方

1. 使用 `customWrapperCache` 避免每次使用 `ctx.selectComponent` 取查询 dom。缓存在 `CustomWrapper` 的生命周期中管理
2. 在 `TaroRootElement` 使用 `this.data` 来储存页面和页面内的所有 CusotmWrapper 节点的数据，以保障在从后往前寻找 CustomWrapper 时能通过 this.data 顺利取到 nn 和 uid
    - 如果不使用 this.data 来管理数据，那么 nn 和 uid 来源应该是当前节点的 Parent CustomWrapper 或 page，需要从前往后寻找 

这样改动增加了 this.data 作为页面数据的拷贝版本，但经过测试发现性能会有明显地提升

前面的评论我 resolve 掉了，辛苦重新 review 下改动

2022-01-05 03:14 UTC, Chen-jj commented
@CS-Tao 

抱歉这么久才 Review。

CustomWrapper 的逻辑可以分三步：

1. 根据 setData 的数据路径，从后往前地寻找 CustomWrapper 和其 id
2. 根据 CustomWrapper 的 id 寻找对应的自定义组件实例
3. CustomWrapper setData

关于第一点，老哥你的方法是用 `this.data` 保存一份页面 data 数据的映射，方便按路径寻找 CustomWrapper 的 id。但是，Taro 的 DOM 树其实就已经拥有了这些信息，不需要另外通过 `this.data` 来保存。

关于第二点，利用 CustomWrapperCache 能很好地处理。

另外方便的话可以加一下开发者微信群咯，可以再沟通一下

2022-01-06 02:28 UTC, Chen-jj approved these changes

2022-01-06 02:29 UTC, merged