feat: add weapp `GetUserProfile` types api
NervJS/taro pull request #11024
Opened 2022-01-03 18:15 UTC by fupengl

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-01-05 06:42 UTC, Chen-jj requested changes

2022-01-05 06:42 UTC, Chen-jj commented on packages/shared/src/native-apis.ts
> +  'getUserProfile',
这是非所有小程序都支持的 API，因此最好修改到 'packages/taro-weapp/src/apis-list.ts' 中

2022-01-05 06:42 UTC, Chen-jj commented on packages/shared/src/native-apis.ts
> +function getNormalRequest(global) {
请修复 lint 错误

2022-01-05 06:42 UTC, Chen-jj commented on packages/taro-components/types/Button.d.ts
> +      getUserProfile
这里搞错了吧，Button 组件的 open-type 属性没有 getUserProfile：

![image](https://user-images.githubusercontent.com/11807297/148172043-7c6ca7a1-36a0-4732-aaf5-14ae703a8e1c.png)

你列的文档地址是 API，而 getUserProfile API 的类型目前已经存在。

2022-01-05 07:05 UTC, fupengl commented on packages/shared/src/native-apis.ts
> +  'getUserProfile',
OK

2022-01-05 07:05 UTC, fupengl commented on packages/shared/src/native-apis.ts
> +function getNormalRequest(global) {
1

2022-01-05 07:08 UTC, fupengl commented on packages/taro-components/types/Button.d.ts
> +      getUserProfile
对,我看到类型是已经有人添加了,仔细研究了下,应该是被文档误解了,这里类型不用添加

2022-01-06 02:02 UTC, Chen-jj commented
@fupengl 麻烦跑一下 `lerna run updateSnapshot --scope=@tarojs/mini-runner` 更新一下测试用例的 snapshot 哈

2022-01-06 05:59 UTC, fupengl commented
> @fupengl 麻烦跑一下 `lerna run updateSnapshot --scope=@tarojs/mini-runner` 更新一下测试用例的 snapshot 哈

已经执行了
不过公司环境是node 15 有个依赖安装不上,新增了一个 yarn 忽略检查node版本的参数

2022-01-06 12:12 UTC, Chen-jj commented
CI 还是跪了，麻烦再看看咯

2022-01-06 12:21 UTC, fupengl commented
> CI 还是跪了，麻烦再看看咯

哈哈哈,好坑

2022-01-06 12:35 UTC, fupengl commented
> CI 还是跪了，麻烦再看看咯

`yarn test` 已经跑完了的,我看看报错吧

2022-01-07 02:59 UTC, Chen-jj approved these changes

2022-01-07 02:59 UTC, merged