fix: window.setTimeout missing returned value bug
NervJS/taro pull request #11045
Opened 2022-01-06 09:24 UTC by blade254353074

**这个 PR 做了什么?** (简要描述所做更改)

在递归调用 window.setTimeout 和 clearTimeout 时，发现 window.setTimeout 并没有返回 number 值，查到是这里做了替换，逻辑和 BOM 实现不符

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [x] 移动端（React-Native）

2022-01-06 12:11 UTC, Chen-jj approved these changes

2022-01-06 12:11 UTC, Chen-jj commented
感谢贡献~

2022-01-06 12:19 UTC, Chen-jj requested changes

2022-01-06 12:19 UTC, Chen-jj commented on packages/taro-runtime/src/bom/window.ts
> +  (window as any).setTimeout = function (...args) {
`...args` 要补一下类型咯，不然 TS 报错了~

2022-01-07 03:54 UTC, blade254353074 commented on packages/taro-runtime/src/bom/window.ts
> +  (window as any).setTimeout = function (...args) {
@Chen-jj DONE

2022-01-07 05:49 UTC, Chen-jj commented on packages/taro-runtime/src/bom/window.ts
> +  (window as any).setTimeout = function (...args) {
@blade254353074 CI 还是跪了，麻烦再看看的

2022-01-07 06:17 UTC, blade254353074 commented on packages/taro-runtime/src/bom/window.ts
> +  (window as any).setTimeout = function (...args) {
...我在 github 上直接改的 没 clone 到本地

2022-01-07 06:42 UTC, Chen-jj commented on packages/taro-runtime/src/bom/window.ts
> +  (window as any).setTimeout = function (...args) {
老哥加油，今天会发 3.3 最后一个 minor 版本 3.3.20，希望能跟上车

2022-01-10 03:19 UTC, Chen-jj approved these changes

2022-01-10 03:19 UTC, merged