fix(mini-runner): @import rule must come first
NervJS/taro pull request #11246
Opened 2022-02-09 05:53 UTC by noyobo

**这个 PR 做了什么?** (简要描述所做更改)

根据 https://www.w3.org/TR/CSS2/cascade.html#at-import 描述，@import 规则应在所有其他规则之前。

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-02-09 06:39 UTC, Chen-jj requested changes

2022-02-09 06:39 UTC, Chen-jj commented on packages/taro-mini-runner/src/plugins/MiniPlugin.ts
> +    source.add(originSource)
这里可以增加一个判断，只有需要注入 `@import` 的情况下，才需要修改 `assets[appStyle]`

2022-02-14 16:31 UTC, Chen-jj commented
@noyobo 麻烦修复一下  CI 的 eslint 报错哈

2022-02-15 02:48 UTC, noyobo commented
> @noyobo 麻烦修复一下 CI 的 eslint 报错哈

嗯，同时增加了 sourcemap 的处理，你看下。

2022-03-05 13:37 UTC, Chen-jj approved these changes

2022-03-05 13:50 UTC, Chen-jj approved these changes

2022-03-05 13:51 UTC, Chen-jj commented
感谢贡献~

2022-03-05 14:07 UTC, merged

2022-03-30 09:26 UTC, shanlh commented
就这一改，全局样式优先级又高于组件样式，引起了很多样式问题，破坏性很大。 
看看当时放底部的原因：
https://github.com/NervJS/taro/pull/6125/commits/e2cae663f72fb61907e57b9f5a1fbb34ee9f7c68

2022-03-30 09:30 UTC, Chen-jj commented
@shanlh 感谢反馈，我们看看的