fix(taro-alipay): 支付宝小程序插件配置字段缺失
NervJS/taro pull request #11362
Opened 2022-02-28 06:09 UTC by fw6

支付宝小程序插件生成的plugin.json配置缺少pages

#11361

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-03-13 03:59 UTC, Chen-jj requested changes

2022-03-13 03:59 UTC, Chen-jj commented on packages/taro-loader/src/native-component.ts
> +hooks.initNativeApiImpls = [...(hooks.initNativeApiImpls || []), defaultReconciler.initNativeApi]
`native-component` 是 shift 进 loader 列表的，也就是最后一个 loader，babel-loader 在此前已经执行。

因此我们不能使用 ES6 的语法，麻烦改为：

```js
hooks.initNativeApiImpls = (hooks.initNativeApiImpls || []).concat(defaultReconciler.initNativeApi)
```

另外还多了一个空行

2022-03-14 03:32 UTC, fw6 commented on packages/taro-loader/src/native-component.ts
> +hooks.initNativeApiImpls = [...(hooks.initNativeApiImpls || []), defaultReconciler.initNativeApi]
已调整完成✅

2022-03-14 03:32 UTC, fw6 commented on packages/taro-loader/src/native-component.ts
> +hooks.initNativeApiImpls = [...(hooks.initNativeApiImpls || []), defaultReconciler.initNativeApi]
已调整完成✅

2022-03-14 03:38 UTC, fw6 commented on packages/taro-loader/src/native-component.ts
> +hooks.initNativeApiImpls = [...(hooks.initNativeApiImpls || []), defaultReconciler.initNativeApi]
此处添加了一行代码修复#11438 。
:bug: 只作为临时修复，感觉有更好的解决方案🤔 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/45113594/158100387-7d494c43-0ed4-43a8-b105-404cf02d2def.png">

2022-03-27 16:03 UTC, Chen-jj approved these changes

2022-03-27 16:06 UTC, Chen-jj commented
感谢 PR~

1. 关于 #11373，调整了一下写法
2. 关于 #11438 ，问题是插件的页面或组件的 js 不应该加入 devtools 插件的 runtime，因此改为在 loader 处过滤。

2022-03-27 16:33 UTC, merged