fix(router): 修复设置 basename 后不跳转默认路由的问题
NervJS/taro pull request #11427
Opened 2022-03-10 10:50 UTC by ryougifujino

**这个 PR 做了什么?** (简要描述所做更改)
[history](https://github.com/remix-run/history)升级到v5后取消了对`basename`对支持
[相关讨论1](https://github.com/remix-run/history/issues/810)
[相关讨论2](https://github.com/remix-run/history/pull/751)

而对默认路由跳转的处理还是沿用的v4版本的方式，导致了使用`https://.../basename`或`https://.../basename/`这样的方式访问不会跳转到默认路由（使用Taro 3.4.3版本验证）。（用以下配置可以复现）
```javascript
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  mini: {},
  h5: {
    publicPath: '/foo/',
    router: {
      basename: '/foo'
    },
    devServer: {
      // 省略
    }
  }
}
```
而老版本没有这个问题（使用Taro 3.2.7版本验证），这个问题应该是由[这个PR](https://github.com/NervJS/taro/pull/9829)引起的 @ZakaryCode ，所以应该从Taro 3.3.1版本开始就有这个问题了。这个问题会导致升级到新版本后只有`basename`的地址无法访问。

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-03-23 06:40 UTC, ryougifujino commented
@ZakaryCode @Chen-jj 能合一下吗，现在因为这个问题没办法升级新版本了。

2022-03-29 13:31 UTC, ZakaryCode requested changes

2022-03-29 13:31 UTC, ZakaryCode commented on packages/taro-router/src/router/index.ts
> +  if (pathname === '/' || onlyContainsBasename(pathname)) {
这里写法有点冗余，没必要新增方法

```tsx
if (stripBasename(history.location.pathname, handler.basename) === '/') {
  // ...
}
```

2022-03-30 16:37 UTC, ryougifujino commented on packages/taro-router/src/router/index.ts
> +  if (pathname === '/' || onlyContainsBasename(pathname)) {
还需要加个`=== ''`的判断，否则在`https://.../basename`和`https://.../#/basename`的情况下不生效。

2022-03-31 07:51 UTC, ZakaryCode commented on packages/taro-router/src/router/index.ts
> +  if (pathname === '/' || onlyContainsBasename(pathname)) {
正常状态下应该直接是空 🤔

2022-03-31 07:56 UTC, ZakaryCode commented on packages/taro-router/src/router/index.ts
> +  if (pathname === '/' || onlyContainsBasename(pathname)) {
不过两种状态都考虑确实也合理

2022-03-31 08:27 UTC, ryougifujino commented on packages/taro-router/src/router/index.ts
> +  if (pathname === '/' || onlyContainsBasename(pathname)) {
之前publicPath和basename是可以设置成一样的，但是在某个版本后就必须设置为publicPath: /foo/ basename: /foo这样了（https://github.com/NervJS/taro/issues/10247#issuecomment-963960124 也提到了这个问题），不知道是否和这个有关。

2022-04-01 08:44 UTC, ZakaryCode approved these changes

2022-04-06 01:59 UTC, merged