feat(mini-runner): 支持用户对内置配置进行修改
NervJS/taro pull request #11517
Opened 2022-03-27 10:40 UTC by elvinzhu

**这个 PR 做了什么?** (简要描述所做更改)

#11515 

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [o] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [o] 所有小程序
- [] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-03-28 12:09 UTC, Chen-jj requested changes

2022-03-28 12:09 UTC, Chen-jj commented on packages/taro-mini-runner/src/index.ts
> +  await customizeChain(webpackChain, null, config.webpackChain)
可以直接挪到 24 行调用，这样不用触发两次的。目前 Taro3 就是这样处理。

2022-04-02 08:38 UTC, elvinzhu commented on packages/taro-mini-runner/src/index.ts
> +  await customizeChain(webpackChain, null, config.webpackChain)
不行。 config.modifyWebpackChain 增加less相关的rule，而buildConf 对这个有依赖 @Chen-jj

2022-04-13 05:41 UTC, elvinzhu commented
为啥没有进展了

2022-07-22 02:08 UTC, Chen-jj approved these changes

2022-07-22 02:08 UTC, merged

2022-07-22 02:09 UTC, Chen-jj commented
感谢贡献~