feat(h5):添加非微信JS-SDK下的getLocation API实现
NervJS/taro pull request #11616
Opened 2022-04-11 23:15 UTC by CaiDingxian

**这个 PR 做了什么?** (简要描述所做更改)

添加非微信JS-SDK下的getLocation API实现，用于在非Js-sdk环境下获取GPS定位

判断浏览器环境，在非微信JS-SDK下的getLocation API使用web api实现，否则才使用JS-SDK实现。

- 和其它敏感API一样，该API在某些浏览器中需要用户点击按钮主动触发才有效

- getLocation API是其中一个要更新的API，Taro中有一系列的API后续可以 Web API 实现 ... ）

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-04-11 23:19 UTC, CaiDingxian reviewed
针对正常获取和异常，已经过测试

2022-04-12 02:11 UTC, ZakaryCode requested changes

2022-04-12 02:11 UTC, ZakaryCode commented on packages/taro-h5/src/api/location/getLocation.ts
> +    return processOpenApi('getLocation')
考虑到后续可能也有其他的 API 由类似的优化，是不是把这里的逻辑整合进 `processOpenApi ` 更合理一些 🤔

2022-04-12 02:11 UTC, ZakaryCode commented on packages/taro-h5/src/api/location/getLocation.ts
> +            errMsg: 'getLocation:ok'
这里的 errMsg 不需要，success 方法会自动补充

2022-04-12 02:11 UTC, ZakaryCode commented on packages/taro-h5/src/api/location/getLocation.ts
> +      errMsg: 'getLocation:fail The current browser does not support this feature'
errMsg 中的 `getLocation:fail ` 可以移除，方法内会自动补充

2022-04-12 10:44 UTC, CaiDingxian commented
@ZakaryCode  提到的几个问题，已经修缮

2022-04-15 03:06 UTC, ZakaryCode commented
> @ZakaryCode 提到的几个问题，已经修缮

原先的实现有点问题，不能抖动可能导致包体增大，顺手调整了。
另外测试用例有些问题，会相互污染，也同步做了处理

2022-04-15 03:06 UTC, ZakaryCode approved these changes

2022-04-15 06:53 UTC, CaiDingxian commented
修改了测试用例和processOpenApi的targetApi绑定，CI测试绿灯了

2022-04-15 08:00 UTC, ZakaryCode commented
> @ZakaryCode 修改了测试用例和processOpenApi的targetApi绑定，CI测试绿灯了

Object.defineProperty 没有给写权限，最后一个测试用例实际是执行错误的，稍微优化了一下

2022-04-15 08:18 UTC, merged