feat(vue3): 允许用户对vue-loader传入配置项
NervJS/taro pull request #11694
Opened 2022-04-21 13:55 UTC by AdvancedCat

**这个 PR 做了什么?** (简要描述所做更改)

允许用户给插件 `@tarojs/plugin-framework-vue3` 传递配置项，以更改 `vue-loader` 配置项.
同时，调整 `compilerOptions` 参数的配置，优先读取 `vueLoaderOption` 内的参数:

```js
const config = {
plugins: [
    [
      "@tarojs/plugin-framework-vue3",
      {
        mini: {
          compilerOptions: {  // 兼容旧版配置
            hotReload: false
          },
        },
        vueLoaderOption: {
          reactivityTransform: true,
          compilerOptions: {  // 优先读取
            hotReload: true
          },
        },
      },
    ],
  ],
}
```

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-04-21 13:56 UTC, AdvancedCat commented
fix #11678

2022-04-25 02:38 UTC, Chen-jj requested changes

2022-04-25 02:38 UTC, Chen-jj commented on packages/taro-plugin-vue3/src/webpack.h5.ts
> +    ...(config?.vueLoaderOption ?? {})
`...` 展开 config.vueLoaderOptions，当 config 是这样的时候会覆盖 compilerOptions

```js
config = {
  vueLoaderOption: {
    compilerOptions: {}
  }
}
```

2022-04-25 02:38 UTC, Chen-jj commented on packages/taro-plugin-vue3/src/index.ts
> +      modifyH5WebpackChain(ctx, chain, data, config)
H5 可以不传 data，data 是小程序才会有用的一个对象

2022-04-25 02:38 UTC, Chen-jj commented on packages/taro-plugin-vue3/src/webpack.mini.ts
> +  const compilerOptions = config?.vueLoaderOption?.compilerOptions || config?.mini?.compilerOptions || {}
config 一定存在，不用 `?.`

2022-04-25 02:38 UTC, Chen-jj commented on packages/taro-plugin-vue3/src/webpack.mini.ts
> +    ...(config?.vueLoaderOption ?? {})
同上，直接展开 `config?.vueLoaderOption` 会覆盖 `compilerOptions ` 配置

2022-04-25 02:38 UTC, Chen-jj commented on packages/taro-plugin-vue3/src/webpack.mini.ts
> +  const compilerOptions = config?.vueLoaderOption?.compilerOptions || config?.mini?.compilerOptions || {}
需要修改文档：https://docs.taro.zone/docs/vue3#compileroptions

2022-04-25 03:40 UTC, AdvancedCat commented on packages/taro-plugin-vue3/src/webpack.h5.ts
> +    ...(config?.vueLoaderOption ?? {})
已将 `...(config?.vueLoaderOption ?? {})` 提升到 `compilerOptions` 之前

2022-04-25 03:40 UTC, AdvancedCat commented on packages/taro-plugin-vue3/src/webpack.mini.ts
> +  const compilerOptions = config?.vueLoaderOption?.compilerOptions || config?.mini?.compilerOptions || {}
文档会在合并后及时修改

2022-04-26 02:50 UTC, Chen-jj approved these changes

2022-04-26 03:05 UTC, merged