Feat/create app
NervJS/taro pull request #11861
Opened 2022-05-30 07:20 UTC by kingzez

**这个 PR 做了什么?** 

[支持 create 创建项目](https://tarojs.notion.site/create-c3089dadc7b040aab8c830ac10c4e998)

新增 create-app 目录，包名为 `@tarojs/create-app`

# @tarojs/create-app

快速创建新的 Taro 应用。

```bash
pnpm create @tarojs/app
# or
yarn create @tarojs/app
# or
npm create @tarojs/app
```
然后按照提示进行操作

可以指定项目名称及是否支持 TypeScript，比如

```bash
pnpm create @tarojs/app my-app --typescript
# or
yarn create @tarojs/app my-app --typescript
# or
npm create @tarojs/app my-app --typescript
```

支持 TypeScript 别名

```bash
pnpm create @tarojs/app my-app --ts
# or
yarn create @tarojs/app my-app --ts
# or
npm create @tarojs/app my-app --ts
```

**这个 PR 是什么类型?** 
- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-06-09 10:16 UTC, huozhongyi123 commented on packages/create-app/README.md
> +```
cnpm也写上吧，包管理那边支持cnpm

2022-06-10 02:59 UTC, kingzez commented on packages/create-app/README.md
> +```
已加

2022-06-30 02:24 UTC, AdvancedCat commented
Nice PR！
PR合并后，需要同步增加 [文档说明](https://taro-docs.jd.com/taro/docs/GETTING-STARTED/#%E9%A1%B9%E7%9B%AE%E5%88%9D%E5%A7%8B%E5%8C%96)。

2022-07-22 03:31 UTC, Chen-jj requested changes

2022-07-22 03:31 UTC, Chen-jj commented on packages/create-app/package.json
> +  "version": "3.4.10",
3.4.13

2022-07-22 03:31 UTC, Chen-jj commented on packages/create-app/package.json
> +    "@tarojs/cli": "3.4.10",
3.4.13

2022-07-22 03:31 UTC, Chen-jj commented on packages/create-app/tsconfig.json
> +  "exclude": [
不需要 exclude，源码放 src 文件夹里（更规范），增加 include

```
"include": [
  "./src",
]
```

2022-07-22 07:31 UTC, kingzez commented on packages/create-app/tsconfig.json
> +  "exclude": [
已调整

2022-07-22 07:37 UTC, Chen-jj approved these changes

2022-07-22 07:57 UTC, merged