feat: 支持传递三方组件函数作为参数
NervJS/taro pull request #11993
Opened 2022-06-25 13:06 UTC by WEN-JY

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #11992
- [ ] 新功能(Feature)
- [x] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [x] 其他，请描述(Other, please describe):

主要改动：
修改了`@tarojs/plugin-platform-alipay`，使其支持三方组件函数传参，不走原来的事件合成管理逻辑，本身这类参数也是三方组件内部的逻辑，不属于原生事件，注意：**遵循小程序自定义组件参数绑定规则，函数需要在page实例上实现**
修改了`@tarojs/react`,在设置函数类属性的时候判断是否为三方组件，如果是，透传属性到attr（以on开头的）和props（普通函数）；
修改了`@tarojs/runtime`,在setAttribute时判断时三方组件且参数为函数，绑定到页面实例上，供三方组件使用；

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-06-25 13:14 UTC, WEN-JY commented
@Chen-jj 帮看下，是不是有更好的方案，实测https://github.com/WEN-JY/taro-demo/tree/feature-support-function-params
已经支持各种类型函数传递，修复了issue id #11992担心哪里不够友好，看看有没有建议

2022-06-26 00:38 UTC, WEN-JY reviewed
通过绑定三方组件自身的sid，实现渲染多个三方组件时，参数互不干扰

2022-06-26 16:29 UTC, Chen-jj commented
@WEN-JY 666~我们看看~

2022-06-26 16:29 UTC, vini123 commented
虚幻之物对应着冥冥之路！：《羽》

2022-06-30 07:49 UTC, Chen-jj requested changes

2022-06-30 07:49 UTC, Chen-jj commented on packages/taro-alipay/package.json
> +  "version": "3.5.0-canary.1",
这个文件不用修改

2022-07-04 07:41 UTC, Chen-jj commented
> 修改了@tarojs/plugin-platform-alipay，使其支持三方组件函数传参，不走原来的事件合成管理逻辑，本身这类参数也是三方组件内部的逻辑，不属于原生事件，注意：遵循小程序自定义组件参数绑定规则，函数需要在page实例上实现

@WEN-JY 关于这部分有疑问，`onEvent` 绑定为事件是为了响应第三方组件抛出的事件 (triggerEvent)，如果这样改为普通属性，则接收不到事件了。

感觉做到普通属性可以传递函数就可以？

2022-07-04 08:08 UTC, WEN-JY commented
> 

这里的改动是for 三方原生组件的，对正常组件的onEvent事件不影响，如：<input onChange={handleChange}>;

关于仅支持普通函数即可有两个考虑：
（1）阿里系现成的大量三方库提供的原生组件是通过onFunction的形式暴露props，支持普通函数解决不了此类现有组件的问题；
（2）三方组件本身的原生事件无需框架层面关心，理论上onTap、onTouch之类的原生事件，三方组件内部会进行监听，如果有必要，也可以通过本PR实现支持的特性 on+function或普通function进行调用，不影响的
@Chen-jj

2022-07-04 10:56 UTC, Chen-jj commented
> 1）现成的大量三方库提供的原生组件是通过onFunction的形式暴露props，支持普通函数解决不了此类现有组件的问题

这一点的确是没考虑到

> 2）三方组件本身的原生事件无需框架层面关心，理论上onTap、onTouch之类的原生事件，三方组件内部会进行监听

关于这里，我的意思不是自定义组件内原生事件的监听。是自定义组件通过 `this.triggerEvent(name, params)` 触发的事件，Taro 无法监听到。

2022-07-04 15:29 UTC, WEN-JY commented
> > 1）现成的大量三方库提供的原生组件是通过onFunction的形式暴露props，支持普通函数解决不了此类现有组件的问题
> 
> 这一点的确是没考虑到
> 
> > 2）三方组件本身的原生事件无需框架层面关心，理论上onTap、onTouch之类的原生事件，三方组件内部会进行监听
> 
> 关于这里，我的意思不是自定义组件内原生事件的监听。是自定义组件通过 `this.triggerEvent(name, params)` 触发的事件，Taro 无法监听到。

第二点你说的对，我将微信端的事件绑定先还原了，你再看看，阿里系不支持 `this.triggerEvent(name, params)`，我想的少了，你再看看，实际测了微信端函数参数支持后续再研究研究，目前这个pr主要针对阿里系的小程序，没有函数，基本就失去了父子通信的一半能力，后面我计划将ref的实现也写一下
@Chen-jj 你再看看新的commit

2022-07-06 15:09 UTC, WEN-JY reviewed
主要改动在于通过分端判断恢复支持triggerEvent的形式监听事件，交给eh统一处理，支付宝、钉钉小程序支持通过属性将函数传递给三方原生组件，支持事件调用

2022-07-09 12:06 UTC, WEN-JY reviewed
第一版本。。好多review搞蒙了，这个版本不支持triggerEvent触发事件，后面的修复了

2022-07-10 10:04 UTC, Chen-jj commented
目的是在支付宝小程序中使用 `onXXX` 的属性给自定义组件传递函数，[支付宝只允许使用 `on` 开头的属性传递函数](https://opendocs.alipay.com/mini/framework/component_object#%E5%A4%96%E9%83%A8%E4%BD%BF%E7%94%A8%E4%BC%A0%E9%80%92%20props)。

也就是支持这种写法 `onComponentClick={this.handleCustomClick}`，这种写法不需要支持：`componentClick={this.handleCustomClick}`。

但是在 JSX 里使用 onXXX 的语法会被处理为事件绑定，因此需要在 reconciler 把支付宝小程序原生自定义组件的 `onXXX` 属性对应的函数绑定到页面对象上，再通过修改模板传递页面对象上的对应函数。

所以修改 reconciler 和支付宝的模板即可。

> 但后续是不是还是要支持下微信端传递onEventHandle非事件函数

这点和 JSX 的事件语法冲突，暂不打算支持。

2022-07-10 10:15 UTC, Chen-jj requested changes

2022-07-10 10:15 UTC, Chen-jj commented on packages/taro-react/src/props.ts
> -function isEventName (s: string) {
这个函数可以不用动，不太确认 `startsWith` 在小程序的兼容性如何

2022-07-10 10:15 UTC, Chen-jj commented on packages/taro-react/src/props.ts
> +  const isThirdPartyComponent = Boolean((Current.page as any)?.config?.usingComponents?.[dom.nodeName])
参考此文件第 41-45 行，使用 `internalComponents` 去判断是否是内置组件：

```js
const compName = capitalize(toCamelCase(dom.tagName.toLowerCase()))

if (eventName === 'click' && compName in internalComponents) {
  eventName = 'tap'
}
```

2022-07-10 10:15 UTC, Chen-jj commented on packages/taro-react/src/props.ts
> +  const isAliApp = process.env.TARO_ENV === 'alipay' ||
`@tarojs/react` 里不应存在平台相关的逻辑，建议新创建一个运行时 hooks，在 `@tarojs/plugin-platform-alipay` 中处理这段逻辑（钉钉插件不需要处理，因为它继承于支付宝插件）。hooks 的创建、监听、调用在 `v3.5` 有改动，所以建议重新提交 PR 到 `feat/3.5` 分支。

2022-07-10 10:15 UTC, Chen-jj commented on packages/taro-react/src/props.ts
> +  } else {
这个 else 逻辑应该是没有作用的，可以取消改动。

2022-07-10 10:15 UTC, Chen-jj commented on packages/taro-react/src/props.ts
> +    // 非阿里系小程序走原逻辑
同上，只有在阿里系小程序环境、且是第三方自定义组件时，触发对应 hooks，在 hooks 里处理。

2022-07-10 10:15 UTC, Chen-jj commented on packages/taro-runtime/src/dom/element.ts
> +        if ((Current.page as any)?.config?.usingComponents[this.nodeName] && isFunction(value)) {
建议把这段逻辑放到上面提到的 hooks 中处理，这样不需要改动 taro-runtime

2022-07-10 10:16 UTC, Chen-jj commented
Review 了一下，总体逻辑没有问题的，但需要把这些改动解耦到支付宝插件中，麻烦抽空看看的~

2022-07-10 12:17 UTC, WEN-JY commented
> Review 了一下，总体逻辑没有问题的，但需要把这些改动解耦到支付宝插件中，麻烦抽空看看的~

收到，有些确实是我不太清楚的，我来调整下

2022-07-26 11:03 UTC, closed without merging

2022-07-27 02:25 UTC, Chen-jj commented
尴尬，3.5 合进 next 后，PR 被关了

@WEN-JY 麻烦重新提一下到 next，还是我这边 cherry-pick 一下

2022-08-08 09:47 UTC, tonyjeffreyIn commented
这个改动有合入么？ 现在在哪个版本上面？

2022-08-09 03:03 UTC, shenstar commented
在vue3框架也修复了吗，最新版本3.5.2，vue3框架支付宝小程序原生组件仍然不能传递函数

2022-08-15 03:35 UTC, tonyjeffreyIn commented
@WEN-JY  方便重提下么？

2022-08-15 03:40 UTC, tonyjeffreyIn commented
> 尴尬，3.5 合进 next 后，PR 被关了
> 
> @WEN-JY 麻烦重新提一下到 next，还是我这边 cherry-pick 一下
这个你能操作合入下么？ @Chen-jj

2022-08-25 02:42 UTC, antiansky commented
请问下这个feat什么时候可以发布？ @WEN-JY @Chen-jj @tonyjeffreyIn

2022-11-05 06:27 UTC, ct-0902 commented
请问这个什么时候可以修复，用支付宝第三方组件无法使用

2023-09-12 11:44 UTC, cuzme commented
想问下这个问题修复了吗

2024-12-16 09:07 UTC, chenweiliang6 commented
> Review 了一下，总体逻辑没有问题的，但需要把这些改动解耦到支付宝插件中，麻烦抽空看看的~

但是vue3也有一样的问题，有修复吗