feat(plugin-mini-ci): 新增支付宝小程序支持cli --open 打开开发者工具
NervJS/taro pull request #12112
Opened 2022-07-26 09:21 UTC by beezen

**这个 PR 做了什么?** (简要描述所做更改)
plugin-mini-ci 模块，新增支付宝小程序类型支持通过cli --open 命令来打开开发者工具

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-07-26 12:28 UTC, Chen-jj requested changes

2022-07-26 12:28 UTC, Chen-jj commented on packages/taro-plugin-mini-ci/package.json
> +    "minidev": "^1.5.1",
建议除了微信小程序 CLI 外（比较常用），其它小程序的 CLI 工具依赖使用 peerDependencies + peerDependenciesMeta optional 的方式声明。

可以参考 Vite 的做法：

https://github.com/vitejs/vite/blob/8469bf0a5e38cbf08ec28e598ab155d339edc442/packages/vite/package.json#L124-L143

有空也可以帮另外几个小程序 CLI 的依赖加上哈，之前遗漏了~

2022-07-26 12:28 UTC, Chen-jj commented on packages/taro-plugin-mini-ci/types/AlipayCI.d.ts
> +    /** 小程序开发者工具安装路径 */
此插件内增加 `.gitignore` 文件，忽略 types 文件夹。因为 types 是 tsc 自动生成的，不需要放 git 里。

2022-07-26 12:28 UTC, Chen-jj commented on packages/taro-plugin-mini-ci/src/AlipayCI.ts
> +    const { minidev } = require('minidev')
参照 `require('miniu')`，增加 try catch 判断，当 require 失败时提示用户安装。

2022-07-26 12:29 UTC, Chen-jj commented
另外麻烦解决一下冲突，我们刚把 3.5 合进 next，3.5 里对此插件有些改动。

2022-07-27 10:02 UTC, beezen commented
@Chen-jj 非常感谢 已经做了相应的调整了 再麻烦帮忙看看哦

2022-07-28 11:22 UTC, Chen-jj approved these changes

2022-07-28 11:23 UTC, Chen-jj commented
感谢贡献~

2022-07-28 13:41 UTC, merged