feat: 独立分包添加公共逻辑抽取
NervJS/taro pull request #12209
Opened 2022-08-03 07:59 UTC by alexlees

**这个 PR 做了什么?** (简要描述所做更改)

[独立分包添加公共逻辑抽取](https://github.com/NervJS/taro/commit/94b101f22b9741541607642d8767e135423a0f9b)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #12206
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-08-03 08:33 UTC, alexlees commented
@Chen-jj 有空 CR 下

2022-10-31 03:45 UTC, Chen-jj requested changes

2022-10-31 03:45 UTC, Chen-jj commented on packages/taro-mini-runner/src/plugins/MiniPlugin.ts
> +                test: module => {
这里的 `test` 逻辑可以去掉，因为 common group 已经声明了 `minChunks: 2`，而 `compPath` 对应的模块只会使用一次，所以没必要再进行过滤。

2022-10-31 03:45 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +                test: module => {
同上

2022-10-31 03:45 UTC, Chen-jj commented
@alexlees 抱歉 review 拖久了~麻烦再修改一下~

2022-11-01 03:45 UTC, alexlees commented on packages/taro-mini-runner/src/plugins/MiniPlugin.ts
> +                test: module => {
👌

2022-11-01 06:26 UTC, Chen-jj approved these changes

2022-11-01 06:27 UTC, Chen-jj commented
@alexlees 感谢贡献~

2022-11-07 08:47 UTC, merged