fix(deps): 删除无用依赖 #12193
NervJS/taro pull request #12202
Opened 2022-08-03 05:44 UTC by ZakaryCode

**这个 PR 做了什么?** (简要描述所做更改)

- 删除无用依赖
- 更新类型默认值

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: #12193

**这个 PR 涉及以下平台:**

- [x] Web 平台（H5）

2022-08-03 05:55 UTC, Chen-jj approved these changes

2022-08-03 08:10 UTC, Chen-jj commented
Besides, bump stencil to `2.16.0`+

https://github.com/ionic-team/stencil/issues/3195

2022-08-03 11:14 UTC, Chen-jj requested changes

2022-08-03 11:14 UTC, Chen-jj commented on package.json
> +    "@pmmmwh/react-refresh-webpack-plugin": "0.5.5",
这几个应该放在 plugin-react 的 devDependencies 里？

2022-08-04 02:28 UTC, ZakaryCode commented on package.json
> +    "@pmmmwh/react-refresh-webpack-plugin": "0.5.5",
按照当前仓库依赖的规则，devDependencies 应尽可能统一放到根目录下保证依赖版本统一。
考虑已经迁移到 pnpm 后不需要更新工作空间开发包的依赖，且当前不同依赖包 webpack 等等依赖版本需要区分，或许我们将根目录的 devDependencies 下放到对应包中是一个更好的选择 🤔

2022-08-05 02:22 UTC, Chen-jj approved these changes

2022-08-05 03:23 UTC, merged