refactor(types): 根据各个小程序官方文档，同步组件类型声明
NervJS/taro pull request #12215
Opened 2022-08-04 04:00 UTC by robinv8

相关讨论 #11740

**这个 PR 做了什么?** (简要描述所做更改)
根据各小程序官方文档，补全小程序组件类型声明文件

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-08-08 02:48 UTC, ZakaryCode requested changes

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/Camera.d.ts
> +
这里的换行需要处理下，会导致文档解析出现问题

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/Camera.d.ts
> +
还有这一类型多出的空行

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/Map.d.ts
>    optimize?: boolean
已经找不到的属性或许可以直接删除，deprecated 只标注为不推荐使用的参数 🤔

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/Map.d.ts
> +   *
参数说明可以在首次新增时手动调整一下，删掉一些冗余空行和平台向的说明（eg：可以删除版本要求相关，wx[xxxxxx]可以改成 Taro[xxxxxx]……）

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/RichText.d.ts
> +  true（基础库 3.150.1 及以后版本）
这一类换行需要处理一下

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/ScrollView.d.ts
> +  /** 滑动结束事件 (同时开启 enhanced 属性后生效) detail { scrollTop, scrollLeft, velocity }
如果可以把 detail 的内容解析到 CommonEventFunction 中会更好

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/ScrollView.d.ts
> +   * 默认值： false
解析出来 default 或许可以从此处删除

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/Swiper.d.ts
> +   * 默认值：0.05
此处默认值并未解析，是因为对应平台差异？

2022-08-08 02:48 UTC, ZakaryCode commented on packages/taro-components/types/Swiper.d.ts
> +   * first：第一个滑块。
希望可以解析成一个 interface 或者 `'first' | 'current' | 'highest' | 'none'` 用于提示用户可填写的字符串

2022-08-09 02:39 UTC, robinv8 commented
@ZakaryCode 我抽空处理一下

2022-08-26 14:50 UTC, closed without merging