feat: previewImage support zoom (#8274)
NervJS/taro pull request #12220
Opened 2022-08-04 10:34 UTC by baosiqing

**这个 PR 做了什么?** (简要描述所做更改)
为h5中的previewImage api提供缩放支持

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-08-05 02:54 UTC, ZakaryCode requested changes

2022-08-05 02:54 UTC, ZakaryCode commented on packages/taro-h5/src/api/media/image/previewImage.ts
> +      div.classList.add('swiper-zoom-container')
这个功能在两个包分别完成，有些割裂也不利于维护，或许这一部分应该考虑合并到 swiper 组件内部，如果不便合并可以让 swiper 组件暴露出 swiperjs 相关配置。

2022-08-05 02:54 UTC, ZakaryCode commented on packages/taro-h5/src/api/media/image/previewImage.ts
> +      div.classList.add('swiper-zoom-container')
该特性是全屏状态下展示的，`full=true` 时设置 `zoom: true` 也是个可行的方案，不过可以的话还是不要将特性分包实现

2022-08-05 02:54 UTC, ZakaryCode commented on packages/taro-h5/src/api/media/image/previewImage.ts
> +  swiper.zoom = true
新增的参数可以考虑在组件类型中标注，标注后这里应该不需要 @ts-ignore

```ts
const swiper: HTMLElement & Omit<SwiperProps, 'style' | 'children'> = document.createElement('taro-swiper-core')
```

2022-08-05 06:10 UTC, baosiqing commented on packages/taro-h5/src/api/media/image/previewImage.ts
> +  swiper.zoom = true
zoom参数在微信小程序的swiper组件中并不存在，是否有必要加入到类型定义中，这里只是想在使用previewImage时开启zoom

2022-08-05 07:08 UTC, baosiqing commented on packages/taro-h5/src/api/media/image/previewImage.ts
> +      div.classList.add('swiper-zoom-container')
swiper组件开启缩放有两个必要条件，一个是创建实例时的zoom参数，另一个是缩放的图片需要包裹在swiper-zoom-container 样式类中（类名可在zoom参数中更改），https://swiperjs.com/swiper-api#zoom ，这部分如果放在taro-swiper-item-core中实现，不知道是否可行，看起来逻辑改动应该会比较多，zoom参数也不能直接暴漏，需要父子组件交互

2022-08-05 11:53 UTC, ZakaryCode commented on packages/taro-h5/src/api/media/image/previewImage.ts
> +  swiper.zoom = true
新增一个特殊参数就行，可以是 zoom，也可以是 customSwiperOption 用来传入额外的配置（包括 full、zoom 等等）

> zoom参数在微信小程序的swiper组件中并不存在

现在的配置中已经存在一些平台专属配置，加一个也并不影响，另外这样也可以给到开发者更多定制的空间 🤔

2022-11-29 08:13 UTC, ZakaryCode approved these changes

2022-11-29 08:35 UTC, merged