fix(prebundle): 优化 vue3 与 prebundle 结合
NervJS/taro pull request #12362
Opened 2022-08-23 08:01 UTC by ZakaryCode

**这个 PR 做了什么?** (简要描述所做更改)

- 优化 vue3 组件类型
- 优化 prebundle 依赖排除提示
- 优化 vue3 prebundle 包含依赖

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #12340
- [x] TypeScript 类型定义修改(Typings)

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [x] Web 平台（H5）

2022-08-24 01:45 UTC, ado5 commented
react版本也有这个问题

2022-08-24 02:06 UTC, ZakaryCode commented
> react版本也有这个问题

该问题是 vue 专属的，如在 react 中有类似现象请在新的 issue 提供相关 demo

2022-09-04 08:51 UTC, Chen-jj requested changes

2022-09-04 08:51 UTC, Chen-jj commented on packages/taro-plugin-vue2/src/index.ts
> +      '@tarojs/plugin-framework-vue3/dist/runtime'
这里是不是写错了，Vue2 的插件使用了 Vue3 插件的 runtime?

2022-09-05 10:35 UTC, ZakaryCode commented on packages/taro-plugin-vue2/src/index.ts
> +      '@tarojs/plugin-framework-vue3/dist/runtime'
确实

2022-09-05 10:55 UTC, Chen-jj approved these changes

2022-09-05 10:55 UTC, merged