feat(taro-plugin-mini-ci):  Taro 小程序端构建CI（持续集成）插件重大更新
NervJS/taro pull request #12437
Opened 2022-09-05 07:37 UTC by bigmeow

**这个 PR 做了什么?** (简要描述所做更改)
去年的PR实现了从0到1，经过一年的项目沉淀和反馈，此次更新以灵活性、输入输出规范统一为特点
## 功能特性
- Taro插件参数支持传入函数体，并应用到了`@taro/plugin-mini-ci` 插件
之前Taro插件做了强验证，只支持传入对象作为参数，新增了支持传入函数作为参数，更加灵活。
举个例子，比如“构建微信小程序时根据构建号动态分配机器人编号”这个需求
- 支持独立的open、preview、upload 命令，操作自定义目录
适用于将`taro`作为项目一部分的开发场景
- 重新联调了各个平台的CI，一年过去了，各大平台的CI包都有不同程度的更新（特别是头条、支付宝）
- 新增 钉钉 小程序CI
- 统一所有平台CI构建后的输出数据，并将数据传递给新增的`onPreviewComplete`、`onUploadComplete`两个钩子
用户可以编写新的插件，基于这个钩子实现 `飞书`、`钉钉` CII推送功能，我计划晚点推一个新插件实现这个功能

## 其他
- 运行时动态加载各端CI包的方式变更，旧的`require`方式不支持`pnpm link`, 不方便调试
- 编写了一些ts类型供开发插件时使用，维护更友好
- 部分不兼容的选项更新统一，不兼容的选项已经在文档加了说明

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [x] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [x] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [x] 支付宝小程序
- [x] 百度小程序
- [x] 字节跳动小程序
- [x] 钉钉小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-09-05 11:01 UTC, Chen-jj requested changes

2022-09-05 11:01 UTC, Chen-jj commented on packages/taro-plugin-mini-ci/package.json
> +  "devDependencies": {
感觉这里还是把各小程序的 CI 工具作为 peerDependencies 比较好吧，留给开发者自行安装。而且百度的工具特别难装，令 Taro CI 非常容易卡死。

2022-09-06 03:13 UTC, bigmeow commented on packages/taro-plugin-mini-ci/package.json
> +  "devDependencies": {
可以。
我之前考虑到用户不用装，但框架开发者希望有类型提示，所以放`devDependencies `了,没想到对于Taro CI 来说也有这问题

2022-09-06 03:21 UTC, zhiqingchen commented on packages/taro-plugin-mini-ci/README.md
> +           "build:weapp": "taro open --type weapp --open",
--open 是否需要？

2022-09-06 03:21 UTC, zhiqingchen commented on packages/taro-plugin-mini-ci/package.json
>      "qrcode-terminal": "^0.12.0",
此包已不再使用

2022-09-06 06:24 UTC, bigmeow commented on packages/taro-plugin-mini-ci/README.md
> +           "build:weapp": "taro open --type weapp --open",
的确不需要

2022-09-06 09:00 UTC, zhiqingchen commented
swan upload 与 preview 验证 ok

2022-09-06 10:15 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/SwanCI.ts
> +        // TODO 没有百度小程序账号， 不知道它的上传码规则
@zhiqingchen 帮忙在这个位置打印下`_stdout `变量， 我留个注释备份

2022-09-15 10:04 UTC, zhiqingchen approved these changes

2022-09-15 10:33 UTC, zhiqingchen commented on packages/taro-plugin-mini-ci/README.md
> +        appid: "钉钉小程序appid,即钉钉开放平台后台应用管理的 MiniAppId 选项"
缺少,

2022-09-19 11:40 UTC, Chen-jj approved these changes

2022-10-20 01:53 UTC, merged

2022-10-20 01:53 UTC, Chen-jj commented
感谢贡献~