fix(router): 修复h5页面onShow时onReachBottom事件多次触发的问题
NervJS/taro pull request #12453
Opened 2022-09-07 12:26 UTC by KkZsc

**这个 PR 做了什么?** (简要描述所做更改)
修复 [#11504](https://github.com/NervJS/taro/issues/11504)

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-09-08 03:07 UTC, ZakaryCode commented
看起来并不能修复该问题🤔

2022-09-08 03:11 UTC, ZakaryCode requested changes
这个问题应该是 page 中 show 方法多调用了一次 bindPageEvents 导致的 （load 中已经调用过

2022-09-09 03:15 UTC, ZakaryCode commented
> bindPageEvents在解绑时的函数引用发生了改变，导致了解绑无效。
> 
> 比如从A页面跳转到B页面时，pageScrollFn已经被重新赋值为B页面时创建的函数引用，后退到A页面时解绑的是B页面的pageScrollFn，解绑不成功，这才导致多次触发onReachBottom。
> 
> 我这次改动是将绑定函数与页面关联起来，在解绑时才可以取到正确的函数引用做解绑。

你说的对

2022-09-09 03:15 UTC, ZakaryCode approved these changes

2022-09-09 07:25 UTC, ZakaryCode commented
测试用例还需要更新一下

2022-09-12 13:07 UTC, KkZsc commented
> @KkZsc 老哥，测试用例还需要更新一下

已更新

2022-09-13 02:30 UTC, merged