New Feature: history api for using react(vue-)router in miniprogram
NervJS/taro pull request #12497
Opened 2022-09-15 13:08 UTC by AdvancedCat

**这个 PR 做了什么?** (简要描述所做更改)

本 PR 在小程序运行时模拟实现了 history & location 对象，进而实现了在小程序环境中使用 react-router 和 vue-router 前端路由方案。

具体参见 [RFC 说明](https://github.com/NervJS/taro-rfcs/blob/feat/history/rfcs/0009-router-support.md) 。

DEMO 仓库:
- https://github.com/AdvancedCat/taro-react-router
- https://github.com/AdvancedCat/taro-vue-router

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-10-20 03:23 UTC, Chen-jj requested changes

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-runtime/src/dsl/common.ts
> +import { BEHAVIORS, CONTEXT_ACTIONS,CUSTOM_WRAPPER, EXTERNAL_CLASSES, ON_HIDE, ON_LOAD, ON_READY, ON_SHOW, OPTIONS, PAGE_INIT, VIEW  } from '../constants'
`CONTEXT_ACTIONS,` 后空格

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-runtime/src/index.ts
> +export { history, location,window } from './bom/window'
空格

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-runtime/src/bom/URLSearchParams.ts
> +const isArray = Array.isArray
`@tarojs/shared` 里有 isArray 工具函数

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-mini-runner/src/webpack/build.conf.ts
> +    history: ['@tarojs/runtime', 'history'],
`webpack5-runner` 也要同步添加，且需要测试 webpack5 prebundle 有没有正确处理这些 provider 对象

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-runtime/src/bom/window.ts
> +        this.location.trigger(CONTEXT_ACTIONS.INIT, pageId)
可以把 `this.location` `this.history` 在 initEvent 里分别先赋值于一个变量闭包起来使用，以减少代码体积？

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-runtime/src/dom/event.ts
> +  public button: number
button 属性的作用是？

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-runtime/package.json
> +  "devDependencies": {
需要显式安装 tslib 吗？taro-runtime 是运行时包，应该不会存在 devDependencies？

2022-10-20 03:23 UTC, Chen-jj commented on packages/taro-runtime/rollup.config.js
> +  external: ['react', 'nervjs', 'react-dom', 'vue', '@tarojs/shared', 'inversify', 'tslib'],
同上

2022-10-20 03:25 UTC, Chen-jj commented
> DEMO 仓库:
> 
> * https://github.com/AdvancedCat/taro-react-router
> * https://github.com/AdvancedCat/taro-vue-router

此 PR 合并后可以把 examples 放入 taro 的 examples 里

2022-10-25 07:32 UTC, AdvancedCat commented on packages/taro-runtime/src/constants/index.ts
> +  INIT = '__init__',
已改成 "0" "1" ...，主要是为了 TS 的类型检查

2022-10-25 07:33 UTC, AdvancedCat commented on packages/taro-mini-runner/src/webpack/build.conf.ts
> +    history: ['@tarojs/runtime', 'history'],
已完成，在 providerPlugin 中各自添加了相应的依赖

2022-10-25 07:34 UTC, AdvancedCat commented on packages/taro-runtime/package.json
> +  "devDependencies": {
Location 和 History 类用到了私有属性（迎合web端，私有属性不会出现在原型链中），需要 tslib 中的辅助函数来处理私有属性（__classPrivateFieldGet）

2022-10-30 10:04 UTC, merged