feat(taro-h5): 路由切换时保留toast
NervJS/taro pull request #12507
Opened 2022-09-17 04:22 UTC by KkZsc

**这个 PR 做了什么?** (简要描述所做更改)
H5端路由切换是不主动关闭toast，相关的关闭toast代码是在[修复modal在跳转后不隐藏的问题](https://github.com/NervJS/taro/commit/491aed8bd0666a7ded95957345cc076d1d6807c5#diff-633f1385f6945299741c557782c1cb98a590ec89d5926f2565f85ad12347ad42R278)时添加的。
但是个人认为跨页面的显示toast是很常见的功能，且toast不同于loading和modal，是有自动关闭逻辑的，不应随着路由变化关闭toast。

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-09-19 05:43 UTC, ZakaryCode requested changes
这里修改应该改造 modal 的逻辑，使其与页面关联之后再删除相关逻辑

2022-09-19 05:44 UTC, ZakaryCode commented
关联 issue #11168

2022-09-21 10:31 UTC, KkZsc commented
> 

Modal函数内已关联调用时的页面path，而且__taroRouterChange事件触发的太早在其回调里不能正确的取到router change之后的页面path。因此在taro-router里路由切换之后增加了__afterTaroRouterChange事件的trigger。

2022-10-12 06:07 UTC, ZakaryCode commented on packages/taro-h5/src/api/ui/interaction/index.ts
>    hideLoading()
这里是不是也要判断一下 🤔

2022-10-14 08:28 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/index.ts
>    hideLoading()
是的，已经加上了，并且修改了路由未挂载时对current的赋值逻辑

2022-10-14 08:29 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/index.ts
>    hideLoading()
> 这里是不是也要判断一下 🤔

是的，已经加上了，并且修改了路由未挂载时对current的赋值逻辑

2022-10-17 09:00 UTC, ZakaryCode commented on packages/taro-h5/src/api/ui/interaction/modal.ts
> +      this.current = Current.page && Current.page.path ? Current.page.path : getHomePage()
这里是 getHomePage 并不一定能解决对应 issue，因为虽然在 App 中调用时候首页没有加载，但用户并不一定从首页进入应用，此时依旧会出现 modal 或 toast 消失的情况

2022-10-17 09:05 UTC, ZakaryCode commented on packages/taro-h5/src/utils/index.ts
> +  const pathname = addLeadingSlash(pages[0])
此处 homePage 判断不太对，缺少 entryPagePath 相关的判断

> 另外，用户不一定从 homePage 进入应用

2022-11-06 10:28 UTC, KkZsc commented on packages/taro-h5/src/utils/index.ts
> +  const pathname = addLeadingSlash(pages[0])
已补充entryPagePath和customRoutes的相关逻辑

2022-11-11 06:45 UTC, yoyo837 commented
路由切换时保留`toast`但`Modal`可以仍然关闭吧?

2022-11-11 10:30 UTC, KkZsc commented
> 

是的，这个pr也关联修改了[#11168](https://github.com/NervJS/taro/issues/11168)

2022-12-02 14:16 UTC, yoyo837 commented
冲突了, 来解决一下

2022-12-05 03:08 UTC, yoyo837 commented
`push -f`

2022-12-05 03:33 UTC, ZakaryCode commented
可以增加一个和 next 分支的 merge 节点，差异文件太多了没法儿看 😂

2022-12-05 05:32 UTC, ZakaryCode commented
> 请问这要怎么操作呢，上一次提交我已经`rebase next`后`push --force`了😂

merge next 然后提交

2022-12-05 06:44 UTC, KkZsc commented
> 

现在merge next已经没有更改了
<img width="567" alt="image" src="https://user-images.githubusercontent.com/112836317/205566457-af037ab3-9c16-4984-9ca7-efe9b6411717.png">

2022-12-06 06:43 UTC, ZakaryCode commented
> 现在merge next已经没有更改了 <img alt="image" width="567" src="https://user-images.githubusercontent.com/112836317/205566457-af037ab3-9c16-4984-9ca7-efe9b6411717.png">

参考[这里](https://stackoverflow.com/questions/51775149/how-to-make-empty-merge-commit-ignoring-changes)

2022-12-07 12:51 UTC, closed without merging