Feat/3.6 postcss8
NervJS/taro pull request #12525
Opened 2022-09-20 02:52 UTC by xueshuai

**这个 PR 做了什么?** (简要描述所做更改)
1.Taro 插件Postcss版本升级到8.4.12
2.优化Postcss插件写法和依赖安装方式(stylelint-taro-rn包除外)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-10-20 02:44 UTC, xueshuai commented
>

2022-10-20 03:02 UTC, xueshuai commented
> @xueshuai 多了 yarn.lock

已删除。

2022-10-20 05:57 UTC, Chen-jj requested changes

2022-10-20 05:57 UTC, Chen-jj commented on packages/postcss-html-transform/src/index.ts
> +module.exports = (options: any = {}) => {
使用 CommonJS 语法是必须的么？

2022-10-20 05:57 UTC, Chen-jj commented on packages/taro-cli/package.json
> +    "ora": "^2.0.0",
ora 的版本不需要变动吧？

2022-10-20 05:57 UTC, Chen-jj commented on packages/taro-cli/package.json
> -    "postcss": "^6.0.22",
postcss 应该作为 devDependencies，待讨论的点同上。

2022-10-20 05:57 UTC, Chen-jj commented on packages/taro-webpack-runner/package.json
> +    "css-loader": "^6.7.1",
这里有一个问题是需要讨论的，`css-loader` 这类基本只有这个包才会安装的依赖，是锁死版本好还是声明 `^` 更好。我目前对 SemVer 的理解是，较通用的包使用 `^` `~` 可以避免用户安装多个版本的问题，如 `lodash`；而 `css-loader` 在使用 Taro 时应该只有 runner 包会安装它，锁死版本能避免其版本变动导致的不兼容问题。

2022-10-20 05:57 UTC, Chen-jj commented on packages/taro-webpack5-runner/package.json
>      "postcss-loader": "6.2.1",
不用升级到 7+ 么?

2022-10-20 05:57 UTC, Chen-jj commented on packages/taro-webpack-runner/package.json
>      "postcss-import": "12.0.1",
不用升级到 14 么？

2022-10-20 05:57 UTC, Chen-jj commented on packages/taro-webpack5-runner/package.json
>      "postcss-import": "12.0.1",
不用升级到 14+ 么?

2022-10-20 06:02 UTC, Chen-jj commented
提了一些问题，主要集中在依赖的治理上，也能反射到对整个项目上，我们以后应该怎样治理各种依赖。@zhiqingchen @ZakaryCode 两位可以一起讨论下。

@xueshuai 此外还需要处理一下冲突的。

2022-10-20 13:22 UTC, xueshuai commented on package.json
> +    "webpack-dev-server": "4.7.4",
这两个依赖没有修改

2022-10-20 13:23 UTC, xueshuai commented on packages/taro-cli/package.json
> +    "ora": "^2.0.0",
已还原，此依赖无需修改

2022-10-26 07:26 UTC, xueshuai commented
> 



> 提了一些问题，主要集中在依赖的治理上，也能反射到对整个项目上，我们以后应该怎样治理各种依赖。@zhiqingchen @ZakaryCode 两位可以一起讨论下。
> 
> @xueshuai 此外还需要处理一下冲突的。

已解决

2022-11-01 02:45 UTC, ZakaryCode commented
> 提了一些问题，主要集中在依赖的治理上，也能反射到对整个项目上，我们以后应该怎样治理各种依赖。@zhiqingchen @ZakaryCode 两位可以一起讨论下。

依赖治理还是如双周会上所说，如果在包内使用的依赖需要明确标注，这样不论是增减依赖还是升级都有明确的方向可以验证。

根目录已有的依赖可以尽可能移除，包括项目内各个包的链接还有包对应的 types 依赖，根目录依赖只应保留包括 husky 在内用于项目治理的依赖。

最后关于项目版本，除 webpack 这类特殊依赖不同包会依赖不同版本需要，其它依赖应尽可能统一版本，或至少在大版本上统一；如有特殊处理或需要的锁定版本的情况，应在对应包的 readme 中说明情况，并注明版本升级的条件便于后续验证。

2022-11-03 06:51 UTC, ZakaryCode approved these changes

2022-11-03 06:51 UTC, merged

2022-11-04 12:10 UTC, xueshuai commented on packages/postcss-html-transform/src/index.ts
> +module.exports = (options: any = {}) => {
使用esm语法，发布canary的测试版本后，包语法错误，export找不到，怀疑可能是esm的导出语法与环境有冲突，调整为cjs进行测试