feat: Add cropImage support
NervJS/taro pull request #12529
Opened 2022-09-20 06:51 UTC by nuintun

**这个 PR 做了什么?** (简要描述所做更改)

增加微信小程序 cropImage 接口

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-09-20 06:53 UTC, nuintun commented
https://github.com/NervJS/taro/issues/12524

2022-09-20 08:13 UTC, Chen-jj requested changes

2022-09-20 08:13 UTC, Chen-jj commented on packages/shared/src/native-apis.ts
> +  'cropImage',
这里麻烦改到 weapp 插件里咯：

![image](https://user-images.githubusercontent.com/11807297/191204412-44f1eef7-186b-43f2-a8ff-43571ada6b39.png)

2022-09-20 08:15 UTC, Chen-jj commented
另外应该还需要更新一下 snapshot，Taro 根目录执行命令 `pnpm --filter "@tarojs/mini-runner" run updateSnapshot`

2022-09-21 03:04 UTC, Chen-jj approved these changes

2022-09-21 06:17 UTC, nuintun commented
@Chen-jj 本地没安装 `gyp` 环境，你帮更新下 `snapshot` 吧

![image](https://user-images.githubusercontent.com/1730277/191428346-adbb1ad6-3c8a-4e91-a624-7a052bf175d8.png)

2022-09-21 06:18 UTC, nuintun commented on packages/shared/src/native-apis.ts
> +  'cropImage',
@Chen-jj 已修改

2022-09-21 06:19 UTC, Chen-jj commented
> @Chen-jj 本地没安装 `gyp` 环境，你帮更新下 `snapshot` 吧
> 
> ![image](https://user-images.githubusercontent.com/1730277/191428346-adbb1ad6-3c8a-4e91-a624-7a052bf175d8.png)

好勒

2022-09-21 07:34 UTC, merged