chore: 部分抹平h5与小程序参数差异
NervJS/taro pull request #12546
Opened 2022-09-21 09:10 UTC by yoyo837

**这个 PR 做了什么?** (简要描述所做更改)

`onLaunch`的查询参数在微信小程序中的与`h5`不一致, 抹平它.

小程序:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/6134547/191464460-6306e8bb-811d-48fb-a938-a3cda5821eec.png">

H5:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/6134547/191464627-cc9845c9-a48a-4823-9178-53afa9227614.png">

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [x] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-09-21 11:37 UTC, ZakaryCode requested changes
CI 挂了，测试用例需要更新一下

2022-09-21 11:38 UTC, ZakaryCode commented
另外可以考虑顺便修复这个 #12387，并提供 `getLaunchOptionsSync` API

2022-09-21 11:57 UTC, ZakaryCode commented
> 我本地无法完成安装, 之前PR都是盲改的, 有什么好的建议吗? 让我可以本地跑用例那种.
> 
> ![image](https://user-images.githubusercontent.com/6134547/191496862-44c495bc-9612-4ab3-8472-49e49b063f6c.png)

这是 puppeteer 安装的问题，设置环境变量 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 跳过安装就行

2022-09-21 14:25 UTC, yoyo837 commented
> 

我研究一下, 还不太熟.

2022-09-21 14:25 UTC, yoyo837 commented
> 另外可以考虑顺便修复这个 #12387，并提供 `getLaunchOptionsSync` API

我研究一下, 还不太熟.

2022-09-23 08:02 UTC, ZakaryCode approved these changes
感谢贡献

2022-09-23 08:03 UTC, ZakaryCode commented
> > 另外可以考虑顺便修复这个 #12387，并提供 `getLaunchOptionsSync` API
> 
> 我研究一下, 还不太熟.

刚刚看 PR 的时候顺手修了 😂

2022-09-23 08:13 UTC, yoyo837 commented
> > > 另外可以考虑顺便修复这个 #12387，并提供 `getLaunchOptionsSync` API
> > 
> > 
> > 我研究一下, 还不太熟.
> 
> 刚刚看 PR 的时候顺手修了 😂

666 👍

2022-09-23 11:25 UTC, merged