chore: prettier 更新以支持 singleAttributePerLine
NervJS/taro pull request #12599
Opened 2022-09-29 08:07 UTC by yoyo837

**这个 PR 做了什么?** (简要描述所做更改)

 prettier 更新以支持 singleAttributePerLine

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [x] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-09-30 02:12 UTC, yoyo837 commented
大佬再看看,是因为啥,

2022-09-30 02:14 UTC, yoyo837 commented
Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with packages/taro-webpack5-prebundle/package.json

2022-09-30 07:06 UTC, ZakaryCode commented
试试本地重新更新下咯

2022-09-30 08:49 UTC, yoyo837 commented
成功了

2022-10-10 02:27 UTC, ZakaryCode requested changes

2022-10-10 02:27 UTC, ZakaryCode commented on .npmrc
> +strict-peer-dependencies=false
此处不应该变更该配置

2022-10-10 11:10 UTC, ZakaryCode approved these changes

2022-10-10 11:11 UTC, merged