fix: promisify tt.getUserProfile
NervJS/taro pull request #12614
Opened 2022-10-05 16:13 UTC by TheKonka

#12612

**这个 PR 做了什么?** (简要描述所做更改)

fix #12612

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [x] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-10-09 14:54 UTC, Chen-jj requested changes

2022-10-09 14:54 UTC, Chen-jj commented on pnpm-lock.yaml
> +      metro-react-native-babel-preset: registry.npmjs.org/metro-react-native-babel-preset/0.70.3
麻烦恢复 pnpm-lock.yaml 的改动

2022-10-10 02:03 UTC, TheKonka commented on pnpm-lock.yaml
> +      metro-react-native-babel-preset: registry.npmjs.org/metro-react-native-babel-preset/0.70.3
已恢复

2022-10-10 02:53 UTC, Chen-jj commented
@TheKonka 麻烦在项目根目录运行 `pnpm --filter "@tarojs/mini-runner" run updateSnapshot` 更新一下测试用例

2022-10-13 07:51 UTC, Chen-jj commented
感谢贡献~

2022-10-13 07:52 UTC, Chen-jj approved these changes

2022-10-13 07:52 UTC, merged

2022-11-08 06:12 UTC, ZakaryCode commented
@TheKonka 老哥，看下邮箱 😂