refactor: 实现小程序组件类型自动同步的功能
NervJS/taro pull request #12646
Opened 2022-10-12 16:06 UTC by robinv8

**这个 PR 做了什么?** (简要描述所做更改)

每周六同步一次小程序组件类型并自动提交 PR

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-10-13 02:35 UTC, ZakaryCode requested changes

2022-10-13 02:35 UTC, ZakaryCode commented on .github/workflows/sync-components-types.yml
> +      - name: Create Pull Request
可以在 taro-docs 也加一个类似的 CI

2022-10-13 12:46 UTC, robinv8 commented on .github/workflows/sync-components-types.yml
> +          labels: |
已处理

2022-10-13 13:19 UTC, robinv8 commented on .github/workflows/sync-components-types.yml
> +      - name: Create Pull Request
已添加 https://github.com/NervJS/taro-docs/pull/31

2022-10-17 05:37 UTC, ZakaryCode approved these changes

2022-10-17 05:41 UTC, ZakaryCode commented
lock 还需要再更新下

2022-10-17 06:06 UTC, robinv8 commented
> lock 还需要再更新下

已更新

2022-10-17 06:54 UTC, merged