fix(plugin-html): 修复开启html转译插件后，部分元素属性没有进行映射导致更新失败的问题
NervJS/taro pull request #12698
Opened 2022-10-21 06:42 UTC by Barrierml

**这个 PR 做了什么?** (简要描述所做更改)
#### bug原因
开启`html`转译插件后，`html`元素`nodeName`名发生了变化，致使后续更新时原有的`TaroElement`兜底属性名转化失效
https://github.com/NervJS/taro/blob/44d8f9e16e2c61b80dcd4af3e6567a8ca08e5527/packages/taro-runtime/src/dom/element.ts#L180
https://github.com/NervJS/taro/blob/44d8f9e16e2c61b80dcd4af3e6567a8ca08e5527/packages/taro-runtime/src/dom/element.ts#L197
又因为`Taro`的首次渲染走的`hydrate`，并不依赖`TaroElement`的`nodeName`进行名称映射，于是就出现了第一次渲染正常，后续更新属性无效的问题
#### 解决方案
1. 将`TaroElement`上的`nodeName `目前的`html`元素tag映射为小程序元素名，例如 `img` -> `image` 使得兜底元素转化生效，但是修改后的影响范围未知
2. （此PR所选用方案）每次修改属性时重新进行一次属性映射
> 头痛医头，脚痛医脚 罢了

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #12673

**这个 PR 涉及以下平台:**

- [x] 所有小程序

2022-10-21 11:36 UTC, yoyo837 commented
合并之后直接来个新版本吧  🤪

2022-10-30 16:07 UTC, Chen-jj requested changes

2022-10-30 16:07 UTC, Chen-jj commented on packages/taro-plugin-html/src/runtime.ts
> +  } else if (alias[key] && alias[key] !== key) {
这里的 `else if` 我感觉应该放在 66 行：

```js
if (attrMapFn) {
    const value = payload.value
    const [mapKey, mapValue] = attrMapFn(key, value, props)
    payload.path = `${_path}.${alias[mapKey] || mapKey}`
    payload.value = mapValue
}
```

的后面。

否则被 `attrMapFn` 转换后的 mapKey 逻辑会被这里的 `else if` 给覆盖了。

2022-10-30 16:07 UTC, Chen-jj commented on packages/taro-plugin-html/src/runtime.ts
> +  } else if (alias[key] && alias[key] !== key) {
同上

2022-11-02 08:02 UTC, Barrierml commented
@Chen-jj 已更新

2022-11-07 08:28 UTC, Chen-jj approved these changes

2022-11-07 08:28 UTC, Chen-jj commented
感谢贡献~

2022-11-07 09:15 UTC, merged