fix: win filename 兼容
NervJS/taro pull request #12710
Opened 2022-10-25 08:18 UTC by PengBoUESTC

**这个 PR 做了什么?** (简要描述所做更改)

babel-loader exclude windows 路径兼容

windows filename : D:\project\taro-fire\node_modules\@tarojs\components\dist\esm\index-e58a2d48.js
mac filename: /Users/XXX/code/jd_Object/taro-fire/node_modules/@tarojs/components/dist/esm/index-310de3d5.js

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-10-25 08:26 UTC, PengBoUESTC commented
3.1.4 版本 components  没有编译 class, 导致 win 打包 与 mac 打包不一致，
经查 是由于 babel-loader exclude 规则 在  win 不起作用

2022-10-29 16:55 UTC, Chen-jj requested changes

2022-10-29 16:55 UTC, Chen-jj commented on packages/taro-webpack-runner/src/util/chain.ts
> +      if (/@tarojs[\\|\/]components/.test(filename)) return true
`/@tarojs[\\/]components/` 这样就可以~

2022-10-31 10:59 UTC, Chen-jj approved these changes

2022-10-31 11:31 UTC, merged