fix(tt): 抹平部分API
NervJS/taro pull request #12715
Opened 2022-10-26 07:57 UTC by jianjiachenghub

**这个 PR 做了什么?** (简要描述所做更改)
#11879
字节小程序存在部分api没有与Taro（或者说微信）对齐，目前只发现一个Taro.showToast比较影响，先修复下，[具体表现见ssues/11879抖音小程序showtoast icon为error时显示错误](https://github.com/NervJS/taro/issues/11879)
TODO：应该还存在部分api有差异，后续想个方案看看怎么能全量对比下

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [x] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-10-28 10:27 UTC, Chen-jj requested changes

2022-10-28 10:27 UTC, Chen-jj commented on packages/shared/src/native-apis.ts
> +        value: ((options: Record<string, any>) => unknown) | unknown
value 不一定是函数，见 alipay 插件

2022-10-28 10:27 UTC, Chen-jj commented on packages/taro-alipay/src/apis.ts
> +import { IApiDiff,processApis } from '@tarojs/shared'
请使用 import type 引入类型

2022-10-28 10:27 UTC, Chen-jj commented on packages/taro-swan/src/apis.ts
> +import { IApiDiff,processApis } from '@tarojs/shared'
同上

2022-10-28 10:27 UTC, Chen-jj commented on packages/taro-tt/src/apis.ts
> +import { IApiDiff, processApis } from '@tarojs/shared'
同上

2022-10-28 10:28 UTC, Chen-jj commented
@jianjiachenghub 感谢贡献~麻烦修改上述问题，然后 taro 根目录运行 `pnpm --filter "@tarojs/mini-runner" run updateSnapshot` 更新一下 snapshot

2022-10-30 02:13 UTC, jianjiachenghub commented on packages/shared/src/native-apis.ts
> +        value: ((options: Record<string, any>) => unknown) | unknown
> value 不一定是函数，见 alipay 插件

大佬是不是看漏了 最后有个| unknown 其它CR问题已解决

2022-10-30 11:06 UTC, Chen-jj commented on packages/shared/src/native-apis.ts
> +        value: ((options: Record<string, any>) => unknown) | unknown
666~稳

2022-10-30 11:06 UTC, Chen-jj approved these changes

2022-10-30 11:06 UTC, merged

2022-10-30 11:07 UTC, Chen-jj commented
感谢贡献~