feat: support compile plugin export
NervJS/taro pull request #12732
Opened 2022-10-28 09:47 UTC by kagawagao

**这个 PR 做了什么?** (简要描述所做更改)

- 完善小程序插件类型定义
- 支持编译小程序插件导出

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

已在微信小程序实测，未测试其他小程序

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-10-28 09:52 UTC, kagawagao commented
relatived PRs: https://github.com/NervJS/taro/pull/12457

add [example](https://github.com/kagawagao/taro/blob/feature%2Fplugin-export/examples/build-weapp-plugin/src/app.config.ts#L21) and [test case](https://github.com/kagawagao/taro/blob/feature%2Fplugin-export/examples/build-weapp-plugin/src/app.config.ts#L21)

2022-10-31 07:30 UTC, Chen-jj requested changes

2022-10-31 07:30 UTC, Chen-jj commented on examples/build-weapp-plugin/src/app.config.ts
> +      export: 'plugin-export'
测试发现，需要带 `.js` 后续才可以。有空可以测试试试。

2022-10-31 07:30 UTC, Chen-jj commented on examples/build-weapp-plugin/src/app.config.ts
> +      export: 'plugin-export'
此外，这个 demo 的编译配置中的 `copy` 配置在此 PR 后已不需要，可以删除，否则编译会报 warning。

2022-10-31 07:30 UTC, Chen-jj commented on examples/build-weapp-plugin/src/plugin-export.ts
> +export default { whoami: 'Wechat MiniProgram' }
这里使用了 `expot default` 代替 `module.exports`，那么插件调用时，应该改为 `requireMiniProgram().default.whoami`。否则按目前的写法，console 输出是 undefined

2022-10-31 07:30 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +      this.addEntry(filePath, entryName, META_TYPE.EXPORTS)
`META_TYPE.EXPORTS` 会在 webpack 的输出前插入 `module.exports=`，不太确定 Webpack5 的 runtime 有没有改动。换句话说不知道还按这样处理在 webpack5 能不能跑，需要测试一下。

2022-10-31 07:31 UTC, Chen-jj requested changes

2022-10-31 07:31 UTC, Chen-jj commented on packages/taro-mini-runner/src/__tests__/fixtures/plugin-export/src/packageA/common.js
> +}
最后留一空行

2022-10-31 07:31 UTC, Chen-jj commented on packages/taro-mini-runner/src/__tests__/fixtures/plugin-export/src/packageA/detail/index.css
> +}
最后留一空行

2022-10-31 11:07 UTC, kagawagao commented on packages/taro-mini-runner/src/__tests__/fixtures/plugin-export/src/packageA/common.js
> +}
done

2022-10-31 11:08 UTC, kagawagao commented on packages/taro-mini-runner/src/__tests__/fixtures/plugin-export/src/packageA/detail/index.css
> +}
done

2022-10-31 11:36 UTC, kagawagao commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +      this.addEntry(filePath, entryName, META_TYPE.EXPORTS)
`webpack5` 编译小程序插件本身就会报错

https://github.com/NervJS/taro/issues/12284

2022-10-31 11:59 UTC, kagawagao commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +      this.addEntry(filePath, entryName, META_TYPE.EXPORTS)
将上述的编译问题修复之后，测试了下，是可以正常编译输出 `plugin.export` 的

2022-10-31 13:12 UTC, kagawagao commented on examples/build-weapp-plugin/src/app.config.ts
> +      export: 'plugin-export'
> 

@Chen-jj 开发者工具会报错，真机不会

2023-03-06 09:20 UTC, closed without merging