Fix/h5 lifecycle
NervJS/taro pull request #12775
Opened 2022-11-04 06:37 UTC by hisanshao

**这个 PR 做了什么?** (简要描述所做更改)
修复h5环境下reLaunch不执行show方法的问题A->B->A

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-11-11 06:13 UTC, ZakaryCode commented
提交 pr 时注意下更新测试用例哦，另外尽可能不要在同一个 pr 提交多个无关联性的特性或修复

2022-11-11 06:55 UTC, ZakaryCode requested changes

2022-11-11 06:55 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar && methodName !== 'reLaunch' && methodName !== 'redirectTo') {
这样修复会导致其他的隐患，还是应该在判断为 tabbar 内根据 methodName 清理路由栈

2022-11-11 06:55 UTC, ZakaryCode commented on packages/taro-runtime/src/dsl/common.ts
> +      // 如果实例还在的情况下先等实例卸载之后再装载，场景：PageA navigateTo PageB and then reLaunch PageA
该修复与 reLaunch 后不执行 show 事件有关，且与 mount 逻辑冲突

2022-11-11 07:19 UTC, hisanshao commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar && methodName !== 'reLaunch' && methodName !== 'redirectTo') {
我理解relaunch应该就是要先卸载所有的再装载新的页面，redirect卸载最后一个再装载新页面，不管是不是tabbar 页面吧，相当于新页面要重新load

2022-11-11 07:19 UTC, hisanshao commented on packages/taro-runtime/src/dsl/common.ts
> +      // 如果实例还在的情况下先等实例卸载之后再装载，场景：PageA navigateTo PageB and then reLaunch PageA
这里确实不是很清楚会不会影响其他地方，但我自己测试下来是没发现问题，有思路怎么改吗

2022-11-11 07:21 UTC, hisanshao commented on packages/taro-runtime/src/dsl/common.ts
> +      // 如果实例还在的情况下先等实例卸载之后再装载，场景：PageA navigateTo PageB and then reLaunch PageA
之前unmounting 每次都会被重置，导致那个if肯定有问题了

2022-11-11 07:22 UTC, hisanshao commented
> 提交 pr 时注意下更新测试用例哦，另外尽可能不要在同一个 pr 提交多个无关联性的特性或修复

好的👌

2022-11-11 09:23 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar && methodName !== 'reLaunch' && methodName !== 'redirectTo') {
> 我理解relaunch应该就是要先卸载所有的再装载新的页面

是的，但由于浏览器本身的限制，实际并不能实现类似的效果，在这里新增判断只能将其逻辑导向 'REPLACE' 动作，实际上并没有清空路由栈。如果需要修复应当调用 unload 先清空路由栈内所有页面，然后 load 当前页面（不过这实际上也并不能改变浏览器携带的路由信息，这个缺陷只能忽略了）。

> redirect卸载最后一个再装载新页面，不管是不是tabbar 页面吧，相当于新页面要重新load

这样的逻辑实际上并不能和小程序相关操作对应，redirectTo 实际上等于 switchTab，但是对于 TabBar 不能和一般页面同样处理，会导致页面出现重复的 TabBar 页面节点，这实际上并不合理；另外 TabBar 页面和普通页面并不一样，如果是同一页面是不需要做额外的处理的。

依照当前小程序 TabBar 的逻辑，这里对于 tabbar 在 'REPLACE' 动作下的路由栈处理确实存在问题，应当在此处清空路由栈，并卸载所有非 TabBar 页面。

2022-11-11 09:31 UTC, ZakaryCode commented on packages/taro-runtime/src/dsl/common.ts
> +      // 如果实例还在的情况下先等实例卸载之后再装载，场景：PageA navigateTo PageB and then reLaunch PageA
> 之前unmounting 每次都会被重置，导致那个if肯定有问题了

不同页面 unmounting 被重置是正常的，在这里除非前置页面被卸载否则不应当有问题，应当检查 onload 与 unload 事件的调用时序是否导致了问题

另外对 prepareMountList 作用域的修改会导致卸载单个页面时，非对应页面的 mount 方法被执行

2022-11-12 06:25 UTC, hisanshao commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar && methodName !== 'reLaunch' && methodName !== 'redirectTo') {
不执行show的问题我再看下了代码逻辑，应该是和stamp的取值有关，A跳B再reLaunchA这个时候旧的A和新的A的stamp都是1，而实例的key是根据path+stamp的，又因为异步的原因，导致load时候创建的新实例，在第一个A卸载的umount回调里面又被delete了，所以show的时候判断到没有实例就不执行了。这里stamp是不是可以用时间戳之类的替换，保证唯一性？

我测试了一下小程序的tabbar页面，也是会出现重复的tabbar页面节点的，你意思是H5不能这么处理？

2022-11-17 11:49 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar && methodName !== 'reLaunch' && methodName !== 'redirectTo') {
之前使用 stacks. Length 是因为早期路由判断散落在各个包内，且初期使用有大量业务反馈存在并发跳转，虽然改也可以，但是个人觉得该参数与 $taroTimestamp 重复，且 injectPageInstance 无触发问题应该通过 removePageInstance 来解决更符合逻辑。

2022-11-17 12:49 UTC, ZakaryCode requested changes

2022-11-17 12:49 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +              const delta = stacks.getDelta(pathname)
合并注释，不需要每一行都写 😂

2022-11-17 12:49 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +          return handler.show(stacks.getItem(prevIndex), pageConfig, prevIndex)
此处还是改为原来的判断相对较好，即 preIndex 出现错误时依旧有页面显示兜底，另外 pop 也有可能存在需要判断  tabbar 情况，比如：navigateTo 跳转到 tabbar 页面回退时，由浏览器回退（或可考虑在 API 限制判断 tabbar 跳转 🤔）

2022-11-17 12:49 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +          handler.unload(currentPage, delta + 1)
优化 unload 方法，在其中通过 removePageInstance 卸载页面实例

2022-11-17 12:49 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +          return handler.show(stacks.getItem(prevIndex), pageConfig, prevIndex)
需优化 stacks 逻辑，区分实际路由栈和面向开发者的路由栈；或者将 tabbar 路由栈作区分。

2022-11-28 11:12 UTC, closed without merging