fix(h5): 修复H5路由栈内实例卸载异常的问题
NervJS/taro pull request #12888
Opened 2022-11-28 11:21 UTC by hisanshao

**这个 PR 做了什么?** (简要描述所做更改)
修复H5路由栈内实例卸载异常的问题

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-11-29 07:03 UTC, ZakaryCode requested changes

2022-12-01 01:59 UTC, ZakaryCode commented
> 原来的逻辑load里面的stampId比createPageConfig那里是+1的(因为load方法里面push了一个page，stampId是根据stacks.length来取值的)，相差一个是有什么原因的吗？我现在是取相同的，load里面的stampId是传递进去的，有没有影响的？

应该不会，晚点我再梳理看看

2022-12-01 14:21 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar(currentPage!.path!)) {
看了下这里加 stack 长度判断感觉意义不大，你看呢

2022-12-01 14:25 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar(currentPage!.path!)) {
没啥需要需要修复的，这个 PR 就准备合并了

2022-12-02 02:14 UTC, hisanshao commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar(currentPage!.path!)) {
你说的是113行吧，之前是没加的，没加的时候firstIns第一次进入的时候是空的，要么firstIns这里要做非空判断，要么就移到外面去判断，想想反正如果stacks为空肯定是不用执行if语句里面的逻辑，就放外面了

2022-12-02 02:14 UTC, hisanshao commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar(currentPage!.path!)) {
> 没啥需要需要修复的，这个 PR 就准备合并了

你说的是113行吧，之前是没加的，没加的时候firstIns第一次进入的时候是空的，要么firstIns这里要做非空判断，要么就移到外面去判断，想想反正如果stacks为空肯定是不用执行if语句里面的逻辑，就放外面了

2022-12-02 02:15 UTC, hisanshao commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar(currentPage!.path!)) {
> 感觉这里加 stack 长度判断感觉意义不大，你看呢

你说的是113行吧，之前是没加的，没加的时候firstIns第一次进入的时候是空的，要么firstIns这里要做非空判断，要么就移到外面去判断，想想反正如果stacks为空肯定是不用执行if语句里面的逻辑，就放外面了

2022-12-02 06:52 UTC, ZakaryCode commented on packages/taro-router/src/router/spa.ts
> +      if (handler.isTabBar(currentPage!.path!)) {
不是，我已经给你删了，这行之前是这样的 /doge

```js
stacks. Length === 1 && handler.isTabBar(currentPage!.path!)
```

2022-12-02 07:46 UTC, ZakaryCode approved these changes
感谢贡献

2022-12-02 08:12 UTC, merged