fix(taro-h5): 路由切换时保留toast，关闭loading和modal时增加页面path判断
NervJS/taro pull request #12945
Opened 2022-12-07 13:52 UTC by KkZsc

**这个 PR 做了什么?** (简要描述所做更改)
- h5端在路由切换时保留toast，loading和modal的关闭增加页面path判断，[#12507](https://github.com/NervJS/taro/pull/12507)
- 更新taro-mini-runner测试用例快照

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-12-08 11:00 UTC, ZakaryCode requested changes

2022-12-08 11:00 UTC, ZakaryCode commented on packages/taro-h5/src/api/ui/interaction/index.ts
> -  hideToast()
当前逻辑下，toast、loading、modal 都与页面相关联，应该不会导致 app.js 中调用的 toast 被页面事件取消，应当不需要移除这里隐藏相关的逻辑？

2022-12-08 11:00 UTC, ZakaryCode commented on packages/taro-h5/src/api/ui/interaction/index.ts
> +  if (modal.currentPath && Current.page && modal.currentPath !== Current.page.path) {
modal.currentPath !== Current.page?.path

2022-12-09 12:14 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/modal.ts
> +import { getLaunchPage,inlineStyle } from '../../../utils'
已修改

2022-12-09 12:14 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/toast.ts
> +import { getLaunchPage,inlineStyle } from '../../../utils'
> 请注意格式

已修改

2022-12-09 12:14 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/modal.ts
> +import { getLaunchPage,inlineStyle } from '../../../utils'
> 格式问题

已修改

2022-12-09 12:22 UTC, KkZsc commented on packages/taro-h5/src/utils/index.ts
> +function getHomePage (appConfig) {
> 或者考虑提供类似 initTabBarApis 方法，使两边共用

将```getHomePage```转移到了```@tarojs/router/src/utils/index```

并且在```@tarojs/taro-h5/src/utils/index```里通过以下方式引入：
```import { addLeadingSlash, getHomePage, stripBasename } from '@tarojs/router/dist/utils'```

2022-12-09 12:22 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/toast.ts
> +    this.currentPath = Current.page && Current.page.path ? Current.page.path : getLaunchPage()
> this.currentPath = Current.page?.path ?? getLaunchPage()

已修改

2022-12-09 12:40 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/index.ts
> -  hideToast()
> 当前逻辑下，toast、loading、modal 都与页面相关联，应该不会导致 app.js 中调用的 toast 被页面事件取消，应当不需要移除这里隐藏相关的逻辑？

我这里的初衷是想在页面A ```navigateTo``` 到页面B的时候保留toast，因为toast是有自动关闭逻辑的，不会出现toast一直存在的情况

2022-12-09 12:41 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/index.ts
> +  if (modal.currentPath && Current.page && modal.currentPath !== Current.page.path) {
> modal.currentPath !== Current.page?.path

已修改

2022-12-10 04:09 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/index.ts
> -  hideToast()
> 但实际还是有 toast 时间过长，可能跨页面的情况存在，如果页面跳转时间小于 toast 时间会在极小的情况下出现异常的体验，且开发者很难自行修复

toast的持续时长是由开发者控制的，开发者在使用showToast时是有相应的预期的，如果不能接受跨页面的toast只需将duration设置一个较小的值，或者不在调用showToast后立刻切换路由（相反如果在showToast后立刻切换了路由，是否可以认为开发者是需要将toast保留到下一个页面呢）。

2022-12-12 02:27 UTC, ZakaryCode commented on packages/taro-h5/src/api/ui/interaction/index.ts
> -  hideToast()
> toast的持续时长是由开发者控制的，开发者在使用showToast时是有相应的预期的，如果不能接受跨页面的toast只需将duration设置一个较小的值，或者不在调用showToast后立刻切换路由（相反如果在showToast后立刻切换了路由，是否可以认为开发者是需要将toast保留到下一个页面呢）。

理论上是，但这与微信表现形式不一致（微信是不会消失，但仅在本页面存在不会跨页面显示

2022-12-12 11:38 UTC, KkZsc commented on packages/taro-h5/src/api/ui/interaction/index.ts
> -  hideToast()
> > toast的持续时长是由开发者控制的，开发者在使用showToast时是有相应的预期的，如果不能接受跨页面的toast只需将duration设置一个较小的值，或者不在调用showToast后立刻切换路由（相反如果在showToast后立刻切换了路由，是否可以认为开发者是需要将toast保留到下一个页面呢）。
> 
> 理论上是，但这与微信表现形式不一致（微信是不会消失，但仅在本页面存在不会跨页面显示

已经将hideToast加回，后续可以考虑将toast、loading、modal的渲染放在当前taaro_page下，和微信的实现统一？

2022-12-13 08:41 UTC, ZakaryCode commented on packages/taro-h5/src/api/ui/interaction/index.ts
> -  hideToast()
> 已经将hideToast加回，后续可以考虑将toast、loading、modal的渲染放在当前taaro_page下，和微信的实现统一？

是这么考虑，可以对 taro_page 的结构优化，或者考虑提供一个 Web Component 组件封装下

2022-12-13 08:43 UTC, ZakaryCode approved these changes

2022-12-13 09:20 UTC, merged