feat: web请求运行时扩展，支持在小程序中使用常见的web请求库
NervJS/taro pull request #13021
Opened 2022-12-25 16:03 UTC by bigmeow

**这个 PR 做了什么?** (简要描述所做更改)
支持常见的 web 请求库在 taro 中可正常使用（例如 axios）。
本插件实现的功能:
- [x] document 支持创建 anchorElement 类型元素（A标签）(功能独立)
- [x] document.cookie （功能独立）
- [x]  XMLHttpRequest 实现（有依赖和处理cookie）
- [ ]  可选择性注入相关BOM

### 测试方法：
1. git clone pr所在分支，在`packages`目录下创建一个`taro`项目，把`package.json`中的`taro`相关依赖全部修改成`workspace:*`;
2. 根目录下 pnpm install
3. 根目录下 pnpm run build
4. 项目目录下正常启动项目即可

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2023-01-10 03:29 UTC, Chen-jj commented
axios 压缩后体积会有多大呢

2023-01-10 03:34 UTC, yoyo837 commented
个人不太支持这个 `feature`, 小程序中运行条件是可控的, 必要性不大. 至于web, 会有API层面的抹平成本吧? 如果不需要抹平, 就应该用户自行引入web来使用, taro最多改一些兼容不做拦路虎.

2023-01-10 04:16 UTC, bigmeow commented
> axios 压缩后体积会有多大呢

我是用 `axios` 做的测试， 用户自行决定是否使用 `axios`或者其他库， 理论上其他库也是支持的；
如下图： GZIP 12.1 ， 非GZIP 28.5， 测试链接（https://cdn.bootcdn.net/ajax/libs/axios/1.2.2/esm/axios.min.js）
![image](https://user-images.githubusercontent.com/10484248/211460527-a6abc39e-0159-4d2b-ae07-f8a261700d65.png)

2023-01-10 04:19 UTC, bigmeow commented
> 个人不太支持这个 `feature`, 小程序中运行条件是可控的, 必要性不大. 至于web, 会有API层面的抹平成本吧? 如果不需要抹平, 就应该用户自行引入web来使用, taro最多改一些兼容不做拦路虎.

Web 层不需要做什么， 这个插件只在编译小程序时注入。
`taro最多改一些兼容不做拦路虎` 我没太理解

2023-01-10 04:24 UTC, yoyo837 commented
那我个人更不理解, 为啥要在小程序模拟xhr了, 直接利用底层的不行吗? 想要使用库的一些特征设计, 比如拦截器?

2023-01-10 05:17 UTC, bigmeow commented
> 那我个人更不理解, 为啥要在小程序模拟xhr了, 直接利用底层的不行吗? 想要使用库的一些特征设计, 比如拦截器?

这个疑问我觉得和 “为啥要支持小程序中使用vue、react、vue-router一样，直接用底层的不行吗”一样是不是有点钻牛角尖了？
我回答是“当然可以，并且运行时方案性能肯定比不上底层，毕竟多了一层胶水层代码”，但做出来就是希望复用 `Web` 中的生态库（特别是降低从h5迁移到小程序这部分用户的成本），当然也有不需要它的用户，所以做成了插件的形式，这本来就是个双向选择的，并没有说注入了很多我本来不需要的代码

2023-01-10 06:08 UTC, yoyo837 commented
倒不是那个意思, 网络库带来的优势连`vue、react、vue-router`带来的优势十分之一都没有, 不扯远了哈, 只是说个感受.

2023-01-10 06:19 UTC, bigmeow commented
> 倒不是那个意思, 网络库带来的优势连`vue、react、vue-router`带来的优势十分之一都没有, 不扯远了哈, 只是说个感受.

这个我承认，准确说应该是请求这一块的可替代性太强，不过这个需求确实存在，且算是 vue 生态中很重要的一个生态库，基本是个 vue 项目就能看到它，基于它封装业务逻辑很多

2023-01-10 06:34 UTC, Chen-jj commented
对一些大型应用来说，一个可以开箱即用的跨端请求库还是很有必要的，可以复用很多例如缓存、拦截器、心跳等能力。

至于跨端请求库选择遵循小程序还是 Web 的 API 标准去实现都没有问题，然而目前业界的确没有遵循小程序标准实现且得到广泛肯定的请求库。那么先从 Web 生态借力，兼容那些得到过时间验证的请求库，如 axios，是比较合理的选择。引入 XHR、Cookie 这些 Web 标准的 API 到小程序环境是为了兼容这些请求库的使用，这部分的代码以插件形式按需注入，开发者根据项目情况选择是否启用，也是比较合理的。另一层的需求，则是为了 @bigmeow 提到的，降低 Web 应用迁移到小程序这部分用户的成本。

我的疑问在于，目前对 axios 的支持程度大概如何，是否在 Taro 文档官方推荐 axios 作为跨端请求库（目前看接近 30k 的体积非常大），以及后续框架是否考虑下场去开发一个更贴合 Taro 规范的跨端请求库。

2023-01-10 06:35 UTC, yoyo837 commented
> 对一些大型应用来说，一个可以开箱即用的跨端请求库还是很有必要的，可以复用很多例如缓存、拦截器、心跳等能力。
> 
> 至于跨端请求库选择遵循小程序还是 Web 的 API 标准去实现都没有问题，然而目前业界的确没有遵循小程序标准实现且得到广泛肯定的请求库。那么先从 Web 生态借力，兼容那些得到过时间验证的请求库，如 axios，是比较合理的选择。引入 XHR、Cookie 这些 Web 标准的 API 到小程序环境是为了兼容这些请求库的使用，这部分的代码以插件形式按需注入，开发者根据项目情况选择是否启用，也是比较合理的。另一层的需求，则是为了 @bigmeow 提到的，降低 Web 应用迁移到小程序这部分用户的成本。
> 
> 我的疑问在于，目前对 axios 的支持程度大概如何，是否在 Taro 文档官方推荐 axios 作为跨端请求库（目前看接近 30k 的体积非常大），以及后续框架是否考虑下场去开发一个更贴合 Taro 规范的跨端请求库。

有道理, 小程序确实没有标准.

2023-01-10 07:45 UTC, bigmeow commented
1.目前对 axios 的支持程度大概如何： 建一个example 项目， 对照 axios 的测试用例 手动一个个过（自动化测试用例不太确定工作量大小）

2. 不考虑web规范，只考虑包大小和跨端功能的话， 这里有个很优秀的请求库 [fly](https://github.com/wendux/fly), 给它提PR 或者fock下来改成Taro.request 规范的都非常合适

1和2我觉得都可以推荐给用户，他们自己选择适合自己项目的，在功能同样强大的前提下，前者主打兼容性，后者主打性能

2023-01-10 08:22 UTC, Chen-jj requested changes

2023-01-10 08:22 UTC, Chen-jj commented on packages/taro-plugin-http/src/index.ts
> +        const injectedPath = `${packageName}/dist/runtime`
此插件的 runtime 感觉需要在 post 阶段插入，参考 taro-plugin-react-devtools，因为它引用了 `@tarojs/taro`，可能会有问题

![image](https://user-images.githubusercontent.com/11807297/211496270-896ec068-f2b1-437c-94a5-dfe2bf92ea85.png)

2023-01-10 08:22 UTC, Chen-jj commented on packages/taro-runtime/src/dom/anchorElement.ts
> +import { parseUrl } from '../bom/location'
axios 只是会创建 a 标签吗，是否会挂载到 dom 树？如果会挂载的话，需要确定一下和 plugin-html 有没有冲突

2023-01-11 07:52 UTC, bigmeow commented on packages/taro-runtime/src/dom/anchorElement.ts
> +import { parseUrl } from '../bom/location'
只创建，不挂载，只是从a 标签上读取一下当前地址

2023-01-17 11:03 UTC, ZakaryCode approved these changes
感谢贡献

2023-01-17 11:03 UTC, merged