feat: jd mini ci
NervJS/taro pull request #13129
Opened 2023-01-12 13:13 UTC by PengBoUESTC

**这个 PR 做了什么?** (简要描述所做更改)
京东小程序ci 工具接入

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [x] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2023-01-13 03:26 UTC, PengBoUESTC commented
#13119 @bigmeow

2023-01-16 09:05 UTC, Chen-jj requested changes

2023-01-16 09:05 UTC, Chen-jj commented on packages/taro-plugin-mini-ci/src/BaseCi.ts
> +  jd?:JdConfig
空格

2023-01-16 09:10 UTC, PengBoUESTC commented
操作失误 =_=, 重新邀请下 review @Chen-jj @bigmeow

2023-01-17 03:56 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      await this.jdCi.preview({
返回值需要处理下， 参考 `WeappCI` 的逻辑：
1. 预览后生成图片到本地某个固定路径： 默认是`path.join(this.projectPath, 'preview.jpg')`
2. 将图片中的二维码数据读取出来，统一打印二维码到控制台
3. 触发 `triggerPreviewHooks` 事件， 将 二维码图片本地绝对路径和 二维码中存储数据输出出去

2023-01-17 03:56 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      await this.jdCi.upload({
上传体验码同上

2023-01-17 03:56 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/index.ts
> +            base64: joi.boolean()
`base64 `这个选项可以干掉了，因为内部统一本地生成图片，要需要打印到控制台；
`projectPath ` 选项也干掉，统一使用外部定义的公共的 `projectPath` 选项

2023-01-17 03:56 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      this.jdCi = require('jd-miniprogram-ci')
统一用 `getNpmPkgSync('jd-miniprogram-ci', process.cwd())` 引入包

2023-01-17 04:04 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      await this.jdCi.preview({
因为不同的小程序CI略有差异，而我希望能统一所有平台的输出CI输出数据，所以没有使用CI自带的控制台打印

2023-01-17 07:56 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      await this.jdCi.preview({
想改成这样 我得调整一下 京东小程序的 ci 工具， 我看看

2023-01-17 08:23 UTC, PengBoUESTC commented
@bigmeow 请勿通过代码 先等我发版 京东 ci 工具

2023-01-17 08:59 UTC, PengBoUESTC commented
> @bigmeow 请勿通过代码 先等我发版 京东 ci 工具

已 发版 1.0.2

2023-01-17 10:18 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/BaseCi.ts
> +  base64?: boolean
只留一个 `privateKey` 就行了

2023-01-17 10:18 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
`previewQrcodePath` 参数没有传递给 `jdCi.preview` 函数， jdCI 是咋生成图片路径的

2023-01-17 10:18 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +        qrcodeFormat: 'image',
同上，看起来少了个 `qrcodeOutputDest` 参数

2023-01-17 10:18 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +    printLog(processTypeEnum.WARNING, '京东小程序不支持 "--open" 参数打开开发者工具')
这块问下开发工具的童鞋，有原生协议支持不？

2023-01-17 10:27 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      await generateQrcodeImageFile(previewQrcodePath, qrcodeContent)
如果 `previewQrcodePath `参数传递给 jdCi.preview 函数了， 那么 `generateQrcodeImageFile ` 函数似乎就没必要被调用了

2023-01-17 10:28 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
你这个 previewQrcodePath 是要在 本地生成的 位置吧， 我看你不是 有写 根据 url 写到本地的 功能吗，
京东小程序是 发到 自己 的 oss 的

2023-01-17 10:29 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
我看 阿里 跟 dingding 你也没有传这个参数吧

2023-01-17 10:29 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +    printLog(processTypeEnum.WARNING, '京东小程序不支持 "--open" 参数打开开发者工具')
这个我有时间问问

2023-01-17 10:34 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
阿里的CI包自己没有生成二维码图片到本地，但是返回了二维码中的数据， 所以我根据数据和路径自己生成到本地了；
微信的CI包自己生成了二维码图片到本地， 但是没告诉我二维码中的数据是什么，所以我是扫描读取了图片内容，自己不单独生成图片了

2023-01-17 10:36 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
我看你的CI 包API很像微信， 是CI包自己就生成了图片， 返回的`result.imgUrl` 这个字段是啥呀？ 二维码的oss地址？还是小程序的oss地址？还是预览码中存储的数据？

2023-01-17 10:44 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
> 

`generateQrcodeImageFile("本地路径", "二维码内容")`  ，表示在指定路径生成指定内容的二维码， 不是下载远程图片到本地哦， 预览码内容可能是个自已定scheme， 也可能是是个oss链接，只要确保生产的二维码被扫描后可以打开小程序就行

2023-01-17 11:04 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
> 我看你的CI 包API很像微信， 是CI包自己就生成了图片， 返回的`result.imgUrl` 这个字段是啥呀？ 二维码的oss地址？还是小程序的oss地址？还是预览码中存储的数据？

二维码的 链接

2023-01-17 11:06 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/BaseCi.ts
> +  base64?: boolean
已修改

2023-01-17 11:24 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      await generateQrcodeImageFile(previewQrcodePath, qrcodeContent)
> 如果 `previewQrcodePath `参数传递给 jdCi.preview 函数了， 那么 `generateQrcodeImageFile ` 函数似乎就没必要被调用了

现在 京东小程序的 ci 工具 没有支持 这么多参数  ， 目前返回值 ` { base64Data?: string //二维码 base64数据  ， imgUrl?: string  // 二维码(扫码进入小程序) URL}`

2023-01-17 11:25 UTC, PengBoUESTC commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      // 返回 图片 base64转换效果
> > 
> 
> `generateQrcodeImageFile("本地路径", "二维码内容")` ，表示在指定路径生成指定内容的二维码， 不是下载远程图片到本地哦， 预览码内容可能是个自定义的scheme， 也可能是是个oss链接，只要确保生产的二维码被扫描后可以打开小程序就行

京东小程序 CI工具 也是 通过  `jimp` 读的 这个链接 生成的 控制台二维码

2023-01-17 11:38 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      this.triggerPreviewHooks({
这里应该是 triggerUploadHooks

2023-01-17 11:38 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      this.triggerUploadHooks({
这里应该是 `triggerUploadHooks `

2023-01-17 11:38 UTC, bigmeow commented on packages/taro-plugin-mini-ci/src/JdCI.ts
> +      await generateQrcodeImageFile(previewQrcodePath, qrcodeContent)
明白了， 这块似乎这里没啥问题了

2023-01-17 11:44 UTC, bigmeow commented
改完正好今天可以发测试版本

2023-01-17 12:55 UTC, merged