fix(api): createMediaRecorder  类型补充
NervJS/taro pull request #13276
Opened 2023-02-12 09:21 UTC by halodong

**这个 PR 做了什么?** (简要描述所做更改)
createMediaRecorder  类型补充,  fix [#12389](https://github.com/NervJS/taro/issues/12389)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-02-14 02:27 UTC, ZakaryCode requested changes

2023-02-14 02:27 UTC, ZakaryCode commented on packages/taro/types/api/media/media-recorder.d.ts
> +      /** 指定录制的时长（s)，到达自动停止。默认值：600	最大 7200，最小 5 */
可以参考以下修改文档注释内容：

```diff
-      /** 指定录制的时长（s)，到达自动停止。默认值：600	最大 7200，最小 5 */
+      /**
+       * 指定录制的时长（s)，到达自动停止。最大 7200，最小 5
+       * @default 600
+       */
```

2023-02-14 02:27 UTC, ZakaryCode commented on packages/taro/types/api/media/media-recorder.d.ts
> +      /** 指定录制的时长（s)，到达自动停止。默认值：600	最大 7200，最小 5 */
默认值会在 API 文档生成中解析，需要单独备注

2023-02-14 02:44 UTC, halodong commented on packages/taro/types/api/media/media-recorder.d.ts
> +      /** 指定录制的时长（s)，到达自动停止。默认值：600	最大 7200，最小 5 */
好的，我调整一下

2023-02-15 02:22 UTC, ZakaryCode approved these changes
感谢贡献

2023-02-15 02:45 UTC, merged