feat(cli): cli增加初始化插件能力
NervJS/taro pull request #13283
Opened 2023-02-13 07:40 UTC by tutuxxx

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-03-10 07:22 UTC, ZEJIA-LIU commented on packages/taro-cli/src/create/plugin.ts
> +    templateFiles.forEach(async file => {
这里的 async 好像没什么作用

2023-03-10 07:29 UTC, ZEJIA-LIU commented on packages/taro-cli/templates/plugin-compile/src/index.ts
> +<% if (['plugin-build'].includes(type)) { -%>
建议把第30行开始的条件判断内容合并到这里

2023-03-10 07:36 UTC, ZEJIA-LIU commented on packages/taro-cli/templates/plugin-compile/src/index.ts
> +import webpackChain from 'webpack-chain';
建议把第 31 行到 72 行的条件判断内容合并到下面

2023-03-10 07:49 UTC, ZEJIA-LIU requested changes
提了一些代码风格的小建议，麻烦有空可以看看修改一下～

2023-03-12 09:10 UTC, tutuxxx commented
> 提了一些代码风格的小建议，麻烦有空可以看看修改一下～

2023-03-12 09:11 UTC, ZEJIA-LIU commented
您好，我已收到您的邮件，我会尽快给你回复，如有急事，请致电13825803202，谢谢。

2023-03-12 09:16 UTC, tutuxxx commented
> 提了一些代码风格的小建议，麻烦有空可以看看修改一下～

提到的两个点都已处理

2023-03-13 02:25 UTC, ZEJIA-LIU approved these changes
feat: cli增加初始化插件能力

2023-03-13 03:24 UTC, ZEJIA-LIU approved these changes

2023-03-13 07:17 UTC, merged

2023-04-03 06:29 UTC, Chen-jj commented
@tutuxxx 麻烦有空补充一下文档的