chore(type): useShareAppMessage 类型定义增强
NervJS/taro pull request #13303
Opened 2023-02-14 17:44 UTC by bigmeow

**这个 PR 做了什么?** (简要描述所做更改)

useShareAppMessage 类型定义增强

用例1， 支持异步函数:
```ts
  import { ShareAppMessageReturnObject, useShareAppMessage } from "@tarojs/taro";

  useShareAppMessage(() => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          title: "",
          imageUrl: "",
          path: ""
        });
      }, 1000);
    });
  });
```

用例2， 支持 `promise` 属性:
```ts
  import { ShareAppMessageReturnObject, useShareAppMessage } from "@tarojs/taro";

  useShareAppMessage(() => {
    const p = new Promise<ShareAppMessageReturnObject>(resolve => {
      setTimeout(() => {
        resolve({
          title: "",
          imageUrl: "",
          path: ""
        })
      }, 1000)
    })
    return {
      title: "",
      imageUrl: "",
      path: "",
      promise: p
    };
  });

```

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-02-15 02:21 UTC, ZakaryCode requested changes

2023-02-15 02:21 UTC, ZakaryCode commented on packages/taro/types/taro.lifecycle.d.ts
> +  interface WeappShareAppMessageReturnObject extends ShareAppMessageReturnObject{
注意格式问题

2023-02-15 02:45 UTC, bigmeow commented on packages/taro/types/taro.lifecycle.d.ts
> +  type ShareAppMessageReturn = ShareAppMessageReturnObject | Promise<ShareAppMessageReturnObject> | WeappShareAppMessageReturnObject
这样推到出来会有个  `Promise<WeappShareAppMessageReturnObject>`, 不支持的

2023-03-03 08:39 UTC, ZakaryCode approved these changes

2023-03-03 08:40 UTC, merged