chore(type): 打开小程序，根据条件判断appId是否必传
NervJS/taro pull request #13412
Opened 2023-03-06 06:49 UTC by ruidoc

**这个 PR 做了什么?** (简要描述所做更改)

使用 Taro.navigateToMiniProgram() 打开另一个小程序，如果传递 shortLink 则不需要传递 appId，而当前 appId 是必传项。
本次提交优化类型，使 shortLink 和 appId 任意一项必传即可。

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [x] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-03-07 07:28 UTC, ZakaryCode requested changes

2023-03-07 07:28 UTC, ZakaryCode commented on packages/taro/types/api/navigate/index.d.ts
> +    type Option = {
尽可能避免 `type Value = aa & bb` 一类写法，在 tsc 中的解析结果会有丢失，在 taro 可能会导致文档自动生成错误

```diff
+ interface Option extends BasicOption
- type Option = {
```

2023-03-07 08:07 UTC, ruidoc commented on packages/taro/types/api/navigate/index.d.ts
> +    type Option = {
经过尝试，interface 不能实现 shortLink 和 appId 任意一项必传，那就只能将 appId 改为可选属性了。

2023-03-07 08:51 UTC, ZakaryCode commented on packages/taro/types/api/navigate/index.d.ts
> +    type Option = {
还是要尽可能把参数写到一起，可以参考如下调整，这样可以尽可能保证文档属性说明的连贯性

```ts
interface IAppIdOption {
  appId: string
  shortLink?: string
  ...
}
type TLinkOption = Exclude<IAppIdOption, 'appId' | 'shortLink'> & {
  appId?: string
  shortLink: string
}
type Option = IAppIdOption | TLinkOption
```

2023-03-10 14:07 UTC, ruidoc commented on packages/taro/types/api/navigate/index.d.ts
> +    type Option = {
已更新，大佬瞅一眼

2023-03-13 06:04 UTC, ZakaryCode commented on packages/taro/types/api/navigate/index.d.ts
> +    type Option = {
不能这样改啊，后续很难维护的 😂
把每个 API 的分开，文档生成时会根据 API 的类型分别生成的

2023-03-13 11:55 UTC, ruidoc commented on packages/taro/types/api/navigate/index.d.ts
> +    type Option = {
我不太清楚文档的规则。你的意思是直接在 namespace 下修改，不用考虑多个 namespace 提取公共类型？

2023-03-15 09:44 UTC, closed without merging

2024-10-09 03:46 UTC, woshishade commented
这个问题需要更新taro版本修复吗？如果需要的话需要什么版本会修复这个问题?

2024-10-09 03:50 UTC, woshishade commented
@ruidoc 知道怎么解决吗？