feat(types):完善QQ小程序广告类型 #13445
NervJS/taro pull request #13447
Opened 2023-03-14 03:08 UTC by SeaHaiWorld

**这个 PR 做了什么?** (简要描述所做更改)
完善QQ小程序广告类型

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [x] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-03-14 06:25 UTC, ZakaryCode requested changes

2023-03-14 06:25 UTC, ZakaryCode commented on packages/taro-components/types/Ad.d.ts
> +  /** 广告类型：swan支持banner、feed，需和百青藤平台上的代码位类型相匹配。qq支持banner、card、feeds、block
可以改为
```diff
- 广告类型：swan支持banner、feed，需和百青藤平台上的代码位类型相匹配。qq支持banner、card、feeds、block
+ 广告类型：banner、feed ，需和百青藤平台上的代码位类型相匹配
@supported swan, tt, qq
@default feed
+ @swan 支持 banner、feed
+ @qq 支持 banner、card、feeds、block
```

2023-03-14 06:31 UTC, ZakaryCode commented on packages/taro-components/types/Ad.d.ts
> +  /** 广告类型：swan支持banner、feed，需和百青藤平台上的代码位类型相匹配。qq支持banner、card、feeds、block
还有测试用例挂了，需要更新 mini-runner 下的快照

2023-03-15 02:17 UTC, SeaHaiWorld commented on packages/taro-components/types/Ad.d.ts
> +  /** 广告类型：swan支持banner、feed，需和百青藤平台上的代码位类型相匹配。qq支持banner、card、feeds、block
好的，我更新一下

2023-03-15 07:03 UTC, TheKonka commented
https://github.com/NervJS/taro/blob/7c9a07cca54327731269b9c39a3645514c9c7176/packages/shared/src/components.ts#L411-L417

这里面有的属性其实可以不用加

2023-03-15 08:08 UTC, SeaHaiWorld commented on packages/taro-components/types/Ad.d.ts
> +  /** 广告类型：swan支持banner、feed，需和百青藤平台上的代码位类型相匹配。qq支持banner、card、feeds、block
fixed

2023-03-15 08:08 UTC, SeaHaiWorld commented
fixed

2023-03-21 02:26 UTC, ZakaryCode approved these changes
感谢贡献

2023-03-21 02:26 UTC, merged

2023-03-31 07:22 UTC, zspggp commented
> fixed

![1](https://user-images.githubusercontent.com/128504353/229051316-b30ef755-5b64-4eeb-b8b6-254c21fb4030.png)
![2](https://user-images.githubusercontent.com/128504353/229051400-e86ab66d-4733-4334-aa0d-b07807ed55fc.png)
![3](https://user-images.githubusercontent.com/128504353/229051533-a479ea49-e32b-4d2d-ad43-6008ef8ae32d.png)

你好，使用今天刚发布的Taro 3.6.2-canary.2，测试依然不可以，可以帮忙再看一下吗？

2023-04-04 04:39 UTC, zspggp commented
3.6.3 确认已修复。感谢。