feat(h5): 启用虚拟模块缓存
NervJS/taro pull request #13508
Opened 2023-03-24 06:10 UTC by ZakaryCode

**这个 PR 做了什么?** (简要描述所做更改)

- 升级虚拟模块依赖版本
- 移除 bootstrap 模块缓存禁用

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #13505

**这个 PR 涉及以下平台:**

- [x] Web 平台（H5）

2023-03-28 03:42 UTC, Chen-jj requested changes

2023-03-28 03:42 UTC, Chen-jj commented on pnpm-lock.yaml
需要处理一下冲突

2023-03-31 02:27 UTC, heiazu approved these changes

2023-03-31 07:47 UTC, Chen-jj approved these changes

2023-03-31 07:48 UTC, merged