给taro添加solid支持
NervJS/taro pull request #13607
Opened 2023-04-08 02:01 UTC by zsytssk

**这个 PR 做了什么?** (简要描述所做更改)

给taro添加solid支持

**这个 PR 是什么类型?** (至少选择一个)

- [x] 新功能(Feature)

**这个 PR 涉及以下平台:**

- [x] 微信小程序
- [x] 支付宝小程序

2023-04-17 02:47 UTC, Chen-jj requested changes

2023-04-17 02:47 UTC, Chen-jj commented on packages/babel-preset-taro/index.js
可以在 solid 的项目模板的 babelrc 里配置即可

2023-04-17 02:47 UTC, Chen-jj commented on packages/taro-solid/package.json
taro-solid 可以放在 taro-plugin-solid?

2023-04-17 03:03 UTC, ZakaryCode commented on packages/taro-components-library-solid/src/component-lib/index.ts
> +export const CoverImage = createComponent('taro-cover-image-core');
这一部分内容建议参考 stencil-output-target [在组件库内输出](https://github.com/NervJS/taro/blob/next/packages/taro-components/scripts/stencil/stencil.config.ts#L9)

同时加上 /*@__PURE__*/ 标注用来移除生产环境不必要的注入，参考 [@tarojs/components/lib/react/components]( https://unpkg.com/browse/@tarojs/components@3.6.5/lib/react/components.js)

2024-03-27 02:38 UTC, ZakaryCode commented
该 PR 包含的内容会逐步拆解到 4.x 分支合入，目前 react 适配组件库部分组件还存在适配问题，stencil 适配器调整暂未合入

2024-05-03 06:20 UTC, closed without merging