fix(taro-h5): request timeout use AbortController abort
NervJS/taro pull request #13633
Opened 2023-04-11 12:26 UTC by wangjunjia

**这个 PR 做了什么?** (简要描述所做更改)

修复 taro-h5 request 参数 timeout 不生效

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #13624
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-04-12 07:09 UTC, ZakaryCode requested changes

2023-04-12 07:09 UTC, ZakaryCode commented on packages/taro-h5/src/api/network/request/index.ts
> +      controller.abort()
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/24262362/231379236-8c151da6-4011-42c3-af7f-92da7463332e.png">

2023-04-12 12:48 UTC, wangjunjia commented on packages/taro-h5/src/api/network/request/index.ts
> +      controller.abort()
好的，抱歉没有查看支持率， 我再修改一下， 谢谢～

2023-04-12 13:04 UTC, wangjunjia commented
哈喽， @ZakaryCode 添加 abortcontroller-polyfill 了， 辛苦再 review 一下， 谢谢～

2023-04-13 02:45 UTC, ZakaryCode approved these changes
LGTM

2023-04-13 10:36 UTC, merged