feat(postcss-pxtransform): h5 支持 px单位; weapp 支持 rem 和 px 单位
NervJS/taro pull request #13650
Opened 2023-04-13 09:04 UTC by linhaobin

**这个 PR 做了什么?** (简要描述所做更改)

postcss-pxtransform
- h5 支持 px单位
- weapp 支持 rem 和 px 单位

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #7637 fix #10212
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-04-13 09:32 UTC, xuanzebin approved these changes

2023-04-13 09:43 UTC, xuanzebin commented
还需要调整 h5、小程序 的 pxTransform 方法，以及 webapck5-runner 和 webpack-runner 里面 getHtmlWebpackPlugin 对应的逻辑。

2023-04-14 07:33 UTC, linhaobin commented
> 还需要调整 h5、小程序 的 pxTransform 方法，以及 webapck5-runner 和 webpack-runner 里面 getHtmlWebpackPlugin 对应的逻辑。

调整了，看下还有什么逻辑需要调整的。
另外请教下有没有什么方式可以在 taro 不发布到 npm 的情况下，在自己电脑上怎么使用最新修改的代码应用到实际项目中进行测试？

2023-04-17 06:09 UTC, xuanzebin commented
> > 还需要调整 h5、小程序 的 pxTransform 方法，以及 webapck5-runner 和 webpack-runner 里面 getHtmlWebpackPlugin 对应的逻辑。
> 
> 调整了，看下还有什么逻辑需要调整的。 另外请教下有没有什么方式可以在 taro 不发布到 npm 的情况下，在自己电脑上怎么使用最新修改的代码应用到实际项目中进行测试？

pr 我们这边今天看一下，然后测试的话，我们一般会新建一个测试项目，然后使用 yarn 来安装依赖，之后通过 yarn link 将修改后的 taro 代码 link 到测试项目中进行调试。

2023-04-17 12:38 UTC, ZakaryCode requested changes

2023-04-17 12:38 UTC, ZakaryCode commented on packages/taro-h5/src/api/taro.ts
> +    case 'rem':
Web 环境下，rem 为默认值

```diff
- case 'rem':
+ default:
+   // rem:
....
///

2023-04-18 03:06 UTC, linhaobin commented on packages/taro-loader/src/app.ts
> +  baseFontSize: ${pxTransformConfig.baseFontSize || (pxTransformConfig.minRootSize >= 1 ? pxTransformConfig.minRootSize : 20)},
copy 过来的 😂 去掉了

2023-04-18 03:09 UTC, linhaobin commented on packages/taro-webpack5-runner/src/webpack/MiniCombination.ts
>        plugin: webpackPlugin.getPlugins(),
fixed

2023-04-18 03:09 UTC, linhaobin commented on packages/taro-webpack5-runner/src/webpack/H5WebpackPlugin.ts
> +    if ((options?.targetUnit ?? 'rem') === 'rem') {
fixed

2023-04-18 03:09 UTC, linhaobin commented on packages/taro-h5/src/api/taro.ts
> +    case 'rem':
fixed

2023-04-18 03:09 UTC, linhaobin commented on packages/taro-webpack5-runner/src/postcss/postcss.mini.ts
> +export const getPostcssPlugins = function (appPath: string, postcssOption: [string, any, Func?][] = []) {
getPostcssPlugins 函数改成一样的了，option 之前的类型不对，改成了 [string, any, Func?][]

2023-04-18 06:42 UTC, ZakaryCode commented on packages/taro-webpack5-runner/src/postcss/postcss.mini.ts
> +export const getPostcssPlugins = function (appPath: string, postcssOption: [string, any, Func?][] = []) {
稍许调整了下，我直接提交咯～

2023-04-18 06:51 UTC, ZakaryCode approved these changes

2023-04-18 07:11 UTC, xuanzebin approved these changes

2023-04-18 07:12 UTC, merged