Feat/cli global plugin
NervJS/taro pull request #13693
Opened 2023-04-19 09:45 UTC by ZEJIA-LIU

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ x ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ x ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-04-20 13:34 UTC, ZakaryCode requested changes

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/Kernel.ts
> +      const coommandName = commandNames[i]
command?

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/Kernel.ts
> +  cliComadnsPath: string
cliCommandsPath?

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/utils/index.ts
> +  // 全局的插件引入报错，不抛出 Error 影响主流程，而是通过 log 提醒然后把插件 fliter 掉，保证主流程不变
filter?

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/utils/index.ts
> +          // 全局的插件运行报错，不抛出 Error 影响主流程，而是通过 log 提醒然后把插件 fliter 掉，保证主流程不变
filter?

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/utils/index.ts
> +        console.log(chalk.yellow(`找不到插件依赖 "${item}"，请先在项目中安装，项目路径：${root}`))
可以的话，希望 CLI 输出的日志，可以加上统一的前缀，例如：

```
Taro(CLI): xxxxx
```

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/utils/index.ts
> +export function resolvePresetsOrPlugins (root: string, args, type: PluginType, skipError?: boolean): IPlugin[] {
另外这个文件引入的 `IPlugin, IPluginsObject` 可以标注为类型

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/Config.ts
> +  TARO_GROBAL_CONFIG_DIR
```diff
- TARO_GROBAL_CONFIG_DIR
+ TARO_GLOBAL_CONFIG_DIR
```

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/Config.ts
> +  disableGlobalConfig: boolean
此处应当不是必须的参数？

```diff
- disableGlobalConfig: boolean+
+ disableGlobalConfig?: boolean
```

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-service/src/Config.ts
> +  disableGlobalConfig
补充类型

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-helper/src/constants.ts
> +
1. 删除空行
2. grobal => global
3. 新增变量应该与 L206-L209 是同类，可以合并到一处？

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-cli/.gitignore
> +!templates/global-config
sort

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-cli/src/cli.ts
> +      kernel.cliComadnsPath = commandsPath
cliComadnsPath => cliCommandsPath

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-cli/src/cli.ts
> +            compiler: args.compilter,
compilter => compiler?

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-cli/src/presets/commands/update.ts
> +
空行移除

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-cli/src/presets/commands/global-config.ts
> +            const pluginWithoutVersionName = getPkgVersionNameByFilterVsersion(pluginName)
getPkgVersionNameByFilterVsersion => getPkgVersionNameByFilterVersion

2023-04-20 13:34 UTC, ZakaryCode commented on packages/taro-cli/src/create/fetchTemplate.ts
> +
lint

2023-04-20 16:15 UTC, ZEJIA-LIU commented on packages/taro-service/src/Kernel.ts
> +      'applayCliCommandPlugin'
done

2023-04-20 16:15 UTC, ZEJIA-LIU commented on packages/taro-service/src/Kernel.ts
> +  cliComadnsPath: string
done

2023-04-20 16:16 UTC, ZEJIA-LIU commented on packages/taro-service/src/utils/index.ts
> +  // 全局的插件引入报错，不抛出 Error 影响主流程，而是通过 log 提醒然后把插件 fliter 掉，保证主流程不变
done

2023-04-20 16:16 UTC, ZEJIA-LIU commented on packages/taro-service/src/utils/index.ts
> +          // 全局的插件运行报错，不抛出 Error 影响主流程，而是通过 log 提醒然后把插件 fliter 掉，保证主流程不变
done

2023-04-20 16:26 UTC, ZEJIA-LIU commented on packages/taro-service/src/utils/index.ts
> +        console.log(chalk.yellow(`找不到插件依赖 "${item}"，请先在项目中安装，项目路径：${root}`))
后面检查cli过程所有的输出，统一加上

2023-04-21 03:07 UTC, ZakaryCode approved these changes

2023-04-21 08:47 UTC, merged