fix(taro-webpack5-runner): 修复webpack5中vue通过render函数渲染组件，无法在微信小程序中渲染问题
NervJS/taro pull request #13749
Opened 2023-04-26 09:51 UTC by voidman2017

**这个 PR 做了什么?** (简要描述所做更改)
关联issue：https://github.com/NervJS/taro/issues/13338

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-04-27 01:53 UTC, xuanzebin requested changes
taro-mini-runner 需要同步修改

2023-04-27 01:54 UTC, voidman2017 commented
> taro-mini-runner 需要同步修改

👌验证通过再提交该部分修改

2023-04-27 03:22 UTC, Chen-jj requested changes

2023-04-27 03:22 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
> +            FunctionExpression (node) {
两点问题：

1. 判断不对，暂时想到需要命中以下写法：

```js
{
  render: function (h) {
    h('', ...)
  }
}

{
  render:  h => {
    h('', ...)
  }
}

{
  render (h) {
    h('', ...)
  }
}
```

可以看到，render 函数可以是 `FunctionExpression`、`ArrowFunctionExpression`、`ObjectMethod` 等。

2. 如果思路是找到上述三者再遍历其内部的 `CallExpression`，会不会影响性能，毕竟在 38 行就扫了全部的 `CallExpression`，已经非常慢了。

综上，建议在 60 行增加一个 else 分支，判断 `CallExpression` 的祖先节点是否有 `ObjectProperty` 或 `ObjectMethod` 名为 `render`，若果存在，再把 render 函数的首个参数名与 `CallExpression` 的 `callee` 对比，两者相等时，再判断 `CallExpression` 首个参数是否字符串，是则命中

2023-04-27 11:24 UTC, voidman2017 commented on packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
> +            FunctionExpression (node) {
参照思路进行了修改，示例代码进行测试：
```

<script>
/* export default {
  name: 'comp',
  render: (createElement) => {
    return createElement('view', [
      createElement('button', '这是测试按钮111'),
      createElement(
        'swiper',
        {
          class: 'swiper-1111',
          attrs: {
            indicatorColor: '#999',
            indicatorActiveColor: '#333',
            circular: true,
            indicatorDots: true,
            autoplay: true,
          },
        },
        [
          createElement('swiper-item', [createElement('view', '111')]),
          createElement('swiper-item', [createElement('view', '222')]),
          createElement('swiper-item', [createElement('view', '333')]),
        ]
      ),
    ])
  },
} */

/* export default {
  name: 'comp',
  render: function (c) {
    return c('view', [
      c('button', '这是测试按钮222'),
      c(
        'swiper',
        {
          class: 'swiper-1111',
          attrs: {
            indicatorColor: '#999',
            indicatorActiveColor: '#333',
            circular: true,
            indicatorDots: true,
            autoplay: true,
          },
        },
        [
          c('swiper-item', [c('view', '1111')]),
          c('swiper-item', [c('view', '2222')]),
          c('swiper-item', [c('view', '3333')]),
        ]
      ),
    ])
  },
} */

export default {
  name: 'comp',
  render(xxxxxxx) {
    return xxxxxxx('view', [
      xxxxxxx('button', '这是测试按钮333'),
      xxxxxxx(
        'swiper',
        {
          class: 'swiper-1111',
          attrs: {
            indicatorColor: '#999',
            indicatorActiveColor: '#333',
            circular: true,
            indicatorDots: true,
            autoplay: true,
          },
        },
        [
          xxxxxxx('swiper-item', [xxxxxxx('view', '11111')]),
          xxxxxxx('swiper-item', [xxxxxxx('view', '22222')]),
          xxxxxxx('swiper-item', [xxxxxxx('view', '33333')]),
        ]
      ),
    ])
  },
} 
</script>
```

2023-04-28 02:52 UTC, Chen-jj requested changes

2023-04-28 02:52 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
> +                if (isRenderNode(node, ancestors)) {
逻辑应该反过来，当不是 createElement 函数的调用时，返回。如果是 createElement 函数的调用，则进行后续收集逻辑。

而且判断要和 74-79 行这些判断一起 && 进行：当都不是 React Vue3 Vue2 的createElement 函数的调用时，返回。

收集的逻辑是 React Vue3 Vue2 通用的，分别收集了第三方自定义组件和内置组件。

对内置组件的收集，是通过触发 `onParseCreateElement` 钩子来进行的。所以可以在 taro-plugin-vue2 包中参考 taro-plugin-vue3/index.ts 中，监听 `onParseCreateElement` 钩子来收集内置组件

2023-04-28 02:52 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
> +      componentConfig.includes.add(firstArg.value)
收集逻辑放 `onParseCreateElement` 中，这里只要判断第一个参数是字符串就行？

2023-04-28 02:54 UTC, Chen-jj requested changes

2023-04-28 02:54 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
> +    if (ancestor.type === 'FunctionExpression' && ancestor?.id?.name === 'render') {
这里好像只能命中 `function render () {}`？能通过你提供的几个测试用例吗

2023-04-28 07:05 UTC, voidman2017 commented on packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
> +                if (isRenderNode(node, ancestors)) {
已参照逻辑进行了修改

2023-04-28 07:06 UTC, voidman2017 commented on packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
> +    if (ancestor.type === 'FunctionExpression' && ancestor?.id?.name === 'render') {
测试用例如上文提到的示例代码：
```

<script>
/* export default {
  name: 'comp',
  render: (createElement) => {
    return createElement('view', [
      createElement('button', '这是测试按钮111'),
      createElement(
        'swiper',
        {
          class: 'swiper-1111',
          attrs: {
            indicatorColor: '#999',
            indicatorActiveColor: '#333',
            circular: true,
            indicatorDots: true,
            autoplay: true,
          },
        },
        [
          createElement('swiper-item', [createElement('view', '111')]),
          createElement('swiper-item', [createElement('view', '222')]),
          createElement('swiper-item', [createElement('view', '333')]),
        ]
      ),
    ])
  },
} */

/* export default {
  name: 'comp',
  render: function (c) {
    return c('view', [
      c('button', '这是测试按钮222'),
      c(
        'swiper',
        {
          class: 'swiper-1111',
          attrs: {
            indicatorColor: '#999',
            indicatorActiveColor: '#333',
            circular: true,
            indicatorDots: true,
            autoplay: true,
          },
        },
        [
          c('swiper-item', [c('view', '1111')]),
          c('swiper-item', [c('view', '2222')]),
          c('swiper-item', [c('view', '3333')]),
        ]
      ),
    ])
  },
} */

export default {
  name: 'comp',
  render(xxxxxxx) {
    return xxxxxxx('view', [
      xxxxxxx('button', '这是测试按钮333'),
      xxxxxxx(
        'swiper',
        {
          class: 'swiper-1111',
          attrs: {
            indicatorColor: '#999',
            indicatorActiveColor: '#333',
            circular: true,
            indicatorDots: true,
            autoplay: true,
          },
        },
        [
          xxxxxxx('swiper-item', [xxxxxxx('view', '11111')]),
          xxxxxxx('swiper-item', [xxxxxxx('view', '22222')]),
          xxxxxxx('swiper-item', [xxxxxxx('view', '33333')]),
        ]
      ),
    ])
  },
} 
</script>
```

如果有无法通过的用例，还麻烦提供一下，这边验证一下

2023-06-08 03:28 UTC, Chen-jj approved these changes

2023-06-08 03:29 UTC, Chen-jj commented
@voidman2017 老哥稳！感谢贡献~

2023-06-08 03:46 UTC, voidman2017 commented
> @voidman2017 老哥稳！感谢贡献~

这个pr会被采纳吗

2023-06-08 03:47 UTC, Chen-jj commented
> > @voidman2017 老哥稳！感谢贡献~
> 
> 这个pr会被采纳吗

会的，随 3.6.8 发布

2023-06-08 03:48 UTC, voidman2017 commented
> > > @voidman2017 老哥稳！感谢贡献~
> > 
> > 
> > 这个pr会被采纳吗
> 
> 会的，随 3.6.8 发布

好的😄

2023-06-08 05:42 UTC, xuanzebin approved these changes

2023-06-08 05:42 UTC, merged