fix(https://github.com/NervJS/taro/issues/13761): throw error if met …
NervJS/taro pull request #13762
Opened 2023-04-28 11:52 UTC by Jeff-Tian

…in upload step

在遇到错误时，通过将捕获到 error 再抛出，以便让流水线显示失败。

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-04-30 08:38 UTC, AdvancedCat requested changes
看上下文，有好几处的 error 抛出，应该要统一处理一下

2023-05-02 08:42 UTC, Jeff-Tian commented
要不统一改成用 process.exit(1)？我看其他地方报错后用了 process.exit(1)。测试下来也是可以的：

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/3367820/235620340-fd862c44-6c21-4399-907c-441f385f7a9f.png">

2023-05-02 08:43 UTC, Jeff-Tian commented
用 process.exit 似乎更好一些，不会打印错误堆栈，显示上更清爽一些。

2023-05-04 01:58 UTC, Jeff-Tian commented
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/3367820/236092671-08729c52-ecb5-4b80-acc5-1d011d68d30b.png">


感谢指正！ 确实，修改后的效果一样。

2023-05-04 02:01 UTC, Jeff-Tian commented on packages/taro-plugin-mini-ci/src/DingtalkCI.ts
> +      process.exit(1)
已经撤销。

2023-05-04 07:13 UTC, bigmeow approved these changes

2023-05-04 11:08 UTC, AdvancedCat approved these changes

2023-05-05 02:19 UTC, merged