feat(component): picker textProps
NervJS/taro pull request #13790
Opened 2023-05-06 07:10 UTC by halodong

组件内部文本props，新增textProps对象，为h5，rn等组件解决国际化问题，例Picker 组件， 传入 

```js
textProps={{
     okText: 'ok',
     cancelText: 'cancel'
}}
```

其他组件有类似需求的话，一样通过textProps, 在类型注释和文档中写明对应的可传的值

fix #12489 

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-05-08 02:47 UTC, ZakaryCode requested changes

2023-05-08 02:47 UTC, ZakaryCode commented on packages/taro-components/src/components/picker/picker.tsx
> +export type PickerText = {
建议使用 interface

2023-05-08 02:47 UTC, ZakaryCode commented on packages/taro-components/src/components/picker/picker.tsx
> +  @Prop() textProps?: PickerText = undefined
```diff
- @Prop() textProps?: PickerText = undefined
+ @Prop() textProps?: PickerText = {}
```

下面使用时可以减少一个可选链，减少冗余

2023-05-09 01:29 UTC, halodong commented on packages/taro-components/src/components/picker/picker.tsx
> +  @Prop() textProps?: PickerText = undefined
@ZakaryCode  刚想起来没有修改对应的 readme 文件，今晚我加下

2023-05-09 06:02 UTC, ZakaryCode commented on packages/taro-components/src/components/picker/picker.tsx
> +  @Prop() textProps?: PickerText = undefined
文档会基于类型描述自动输出，如果有需要可以直接在类型中注明

2023-05-09 07:30 UTC, halodong commented on packages/taro-components/src/components/picker/picker.tsx
> +  @Prop() textProps?: PickerText = undefined
> 文档会基于类型描述自动输出，如果有需要可以直接在类型中注明

ok，目前没有要调整的了

2023-05-10 03:14 UTC, ZakaryCode approved these changes

2023-05-10 08:07 UTC, merged