feat(h5): 补充部分不支持api
NervJS/taro pull request #13803
Opened 2023-05-08 14:40 UTC by smileying

**这个 PR 做了什么?** (简要描述所做更改)
-   增加 暂时不支持 API 提示， 涉及的API主要有：
    editImage、cropImage 、openQzonePublish、
    requestSubscribeDeviceMessage、offWifiConnectedWithPartialInfo、checkIsPictureInPictureActive

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-05-10 08:19 UTC, ZakaryCode requested changes

2023-05-10 08:19 UTC, ZakaryCode commented on packages/taro-h5/src/api/ui/window.ts
> +export const checkIsPictureInPictureActive = temporarilyNotSupport('checkIsPictureInPictureActive')
文件最后加一个空行，其他文件也是一样

2023-05-10 08:19 UTC, ZakaryCode commented on packages/taro-h5/src/api/qq/index.ts
> +export const openQzonePublish = temporarilyNotSupport('openQzonePublish')
需在 @tarojs/taro-h5/src/api/index.ts 中引入

2023-05-11 04:37 UTC, smileying commented on packages/taro-h5/src/api/ui/window.ts
> +export const checkIsPictureInPictureActive = temporarilyNotSupport('checkIsPictureInPictureActive')
ok

2023-05-11 04:37 UTC, smileying commented on packages/taro-h5/src/api/qq/index.ts
> +export const openQzonePublish = temporarilyNotSupport('openQzonePublish')
ok

2023-05-11 05:36 UTC, ZakaryCode approved these changes
感谢贡献

2023-05-11 05:36 UTC, merged