fix(h5): 优化组件编译模式导出配置 fix #13958
NervJS/taro pull request #13995
Opened 2023-06-09 09:43 UTC by ZakaryCode

**这个 PR 做了什么?** (简要描述所做更改)

为组件编译模式提供默认的导出格式

> 根据框架排除常用的依赖

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #13958

**这个 PR 涉及以下平台:**

- [x] Web 平台（H5）

2023-06-14 02:22 UTC, Chen-jj requested changes

2023-06-14 02:22 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/webpack/H5Combination.ts
> +      switch (framework) {
这部分放在框架插件中咯

2023-06-14 05:46 UTC, ZakaryCode commented on packages/taro-webpack5-runner/src/webpack/H5Combination.ts
> +      switch (framework) {
可

2023-06-15 07:56 UTC, Chen-jj approved these changes

2023-06-19 06:23 UTC, merged