feat: 开发配置体验增强
NervJS/taro pull request #14021
Opened 2023-06-14 10:36 UTC by bigmeow

**这个 PR 做了什么?** (简要描述所做更改)
主要是针对 `config/index.ts` 文件的增强， 优化配置体验：
- 类型定义完善、增加注释
- 支持直接导出对象配置或者异步函数配置
-  新增特殊环境变量 `TARO_APP_ID`，帮助开发者在多环境下快速切换 `appid`
- 新增 `defineConfig` , 用法参考了 [vite](https://cn.vitejs.dev/config/#config-intellisense)，但为了兼容以前的 `taro` 配置文件，又略有区别
- 默认模板适配修改

使用方式如下:
`config/index.ts文件`
```ts
// 直接传入对象
export default defineConfig({
   // 用户配置对象
})
```

```ts
// 传入（异步）函数
export default defineConfig((mergin, { command, mode }) => {
  // mergin 为webpack-mergin, 兼容以前的配置
  // 假如执行的命令为: "taro build --type weapp --mode test"
  // 则 command 的值为 build, mode 的值为 test
  if (mode === 'development') {
    return {
      // dev 独有配置
    }
  } else if (mode === 'test') {
    return {
      // test 独有配置
    }
  } else {
    return {
      // build 独有配置
    }
  }
})
```

```ts
export default defineConfig(async (mergin, { command, mode }) => {
  const data = await asyncFunction()
  return {
    //taro 配置
  }
})
```

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

> 以上修改已内置在模板中，发布在 `3.6.9-alpha.5`版本 可使用 `taro init `命令，选择`taro内置模板`进行体验

<img width="176" alt="image" src="https://github.com/NervJS/taro/assets/10484248/b338ee48-55fb-4749-ac1d-5b1a0c22239c">

2023-06-17 07:49 UTC, AdvancedCat commented on packages/taro-cli/src/util/defineConfig.ts
> +}
文件末尾要另起一行

2023-06-19 09:00 UTC, ZakaryCode commented on packages/taro-cli/templates/default/src/app.js
> +    console.log('App launched.', process.env.TARO_APP_API)
process.env.TARO_APP_API 这类配置应当交与开发者自行配置

2023-06-19 09:07 UTC, ZakaryCode commented on packages/taro-cli/templates/default/config/dev.js
> -module.exports = {
还是建议保留 dev\prod 两个配置文件，与过往习惯保持一致

2023-06-19 09:08 UTC, ZakaryCode commented on packages/taro-cli/templates/default/package.json.tmpl
> +    "start:dev": "npm run build:weapp -- --watch --mode dev",
没必要新增这几个 scrips，可以放到 RM 提示开发者自行配置使用

2023-06-19 12:48 UTC, bigmeow commented on .vscode/launch.json
> +      "program": "${workspaceFolder}/packages/create-app/dist/index.js",
是的 ， 是我自己调试时，修改后未及时还原

2023-06-19 12:51 UTC, bigmeow commented on packages/taro-cli/tsconfig.json
> +    "declaration": true
这个确实需要, 不加不会生成d.ts,没有类型提示
```ts
import { defineConfig } from "@tarojs/cli";
```

2023-06-19 13:01 UTC, bigmeow commented on packages/taro-cli/templates/default/_env.dev
> +TARO_APP_ID="dev环境小程序appid"
因为ts验证不通过，还不方便改ts类型(会影响到其他地方)

<img width="767" alt="image" src="https://github.com/NervJS/taro/assets/10484248/22d9c3c5-1ac3-4641-a7e9-14e9caf9b0bf">

2023-06-20 02:34 UTC, ZakaryCode commented on packages/taro-cli/tsconfig.json
> +    "declaration": true
不生成 dts 也会有类型提示啊

2023-06-20 02:45 UTC, bigmeow commented on packages/create-app/src/createApp.ts
> +// @ts-nocheck
我完善了相关类型

2023-06-20 07:08 UTC, bigmeow commented on packages/taro-cli/templates/default/config/dev.js
> -module.exports = {
这里是希望用新的配置了，用 `模式` 代替  `process.env.NODE_ENV` 来判断环境(当然老的文档依旧保留)

2023-06-20 07:26 UTC, ZakaryCode requested changes

2023-06-20 07:26 UTC, ZakaryCode commented on packages/taro-cli/src/create/project.ts
> +    if ((typeof conf.css) !== 'string') {
多了个括号

2023-06-20 07:26 UTC, ZakaryCode commented on packages/taro-cli/templates/default/_env.dev
> +TARO_APP_ID="dev环境小程序appid"
改成这样应该会更好些

```env
# 文档参考 https://taro-docs.jd.com/docs/next/env-mode-config
# TARO_APP_ID=touristappid
```

与当前一致，且不会因为没有配置影响正常编译

2023-06-20 07:26 UTC, ZakaryCode commented on packages/taro-cli/templates/default/config/dev.js
> -module.exports = {
使用 mode 替代也并非不可，但是直接从模板删除原有的方案对于一个小版本来说跨度有些太大了，另外直接删掉 dev/prod 也移除了模板对于一些场景的优化提示

2023-06-21 06:23 UTC, ZakaryCode approved these changes

2023-06-21 06:23 UTC, ZakaryCode commented on packages/taro-cli/src/create/project.ts
> +    if ((typeof conf.compiler) !== 'string') {
lint

2023-06-21 06:23 UTC, ZakaryCode commented on packages/taro-cli/src/create/project.ts
> +    if ((typeof conf.framework) !== 'string') {
lint

2023-06-21 06:23 UTC, ZakaryCode commented on packages/taro-cli/templates/default/config/prod.js
> +<% if (typescript) {%>import { UserConfigExport } from "@tarojs/cli";
```diff
- <% if (typescript) {%>import { UserConfigExport } from "@tarojs/cli";
+ <% if (typescript) {%>import type { UserConfigExport } from '@tarojs/cli'
```

2023-06-21 06:23 UTC, ZakaryCode commented on packages/taro-cli/templates/default/config/dev.js
> +<% if (typescript) {%>import { UserConfigExport } from "@tarojs/cli";
```diff
- <% if (typescript) {%>import { UserConfigExport } from "@tarojs/cli";
+ <% if (typescript) {%>import type { UserConfigExport } from '@tarojs/cli'
```

2023-06-21 07:04 UTC, merged