fix: image 组件开启lazy-load后不能更新src
NervJS/taro pull request #14297
Opened 2023-08-02 09:19 UTC by eat-happy

**这个 PR 做了什么?** (简要描述所做更改)
fix: image 组件开启lazy-load后不能更新src

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-08-07 03:32 UTC, ZakaryCode requested changes

2023-08-07 03:32 UTC, ZakaryCode commented on packages/taro-components/src/components/image/image.tsx
> +        {lazyLoad && !didLoad ? (
这样优化不必写三元判断吧，可以优化下写法

2023-08-07 03:32 UTC, ZakaryCode commented on packages/taro-components/src/components/image/image.tsx
> +        {lazyLoad && !didLoad ? (
另外在实际加载后 lazyLoad 属性也无作用，或许可以考虑添加原生 lazyLoad 参数？

2023-08-07 07:05 UTC, eat-happy commented on packages/taro-components/src/components/image/image.tsx
> +        {lazyLoad && !didLoad ? (
https://caniuse.com/loading-lazy-attr  原生兼容在ios上不太好，当前也可以用nativeProps 传入。这是在当前代码的最小改动，这个三元是控制src的传入(有了src 才会加载图片)，lazyLoad的作用是在加载前显示空的img(可能有样式 宽高啥的)。

2023-08-11 06:01 UTC, ZakaryCode approved these changes
感谢贡献

2023-08-11 07:43 UTC, merged