Feature 新增 webpack 不同级别编译错误处理方式
NervJS/taro pull request #14559
Opened 2023-09-16 02:10 UTC by beezen

**这个 PR 做了什么?** (简要描述所做更改)

背景：当 Taro 框架在流水线的自动集成环节中进行编译构建时，编译错误并不会以非 0 退出码结束进程，导致无法判断构建生成发布物是否功能完善，容易造成事故。

目标：当 Taro 框架在流水线的自动集成环节中进行编译构建时，如果发生编译错误，应该以非 0 的退出码结束进程，以方便自动化脚本定义该次流程成功或失败。

目前 webpack 编译过程中的错误处理(Error Handling) 主要涉及以下三种类型的错误:

1、致命的 wepback 错误（配置出错等）
2、编译错误（缺失的 module，语法错误等）
3、编译警告

其中编译警告并不会影响应用功能的正常使用，无需考虑处理。

通过在工程编译配置中新增字段 errorLevel 来定义错误处理的严格模式。

参数值说明：
- 0（默认 ） ：表示只有发生“1、致命的webpack错误（配置出错等）”情况时，返回非 0 的退出码结束进程。
- 1：表示发生“1、致命的 wepback 错误（配置出错等）2、编译错误（缺失的 module，语法错误等）”情况时，返回非 0 的退出码结束进程。

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-09-25 16:44 UTC, Chen-jj requested changes

2023-09-25 16:44 UTC, Chen-jj commented on packages/taro-webpack-runner/src/index.ts
> +    errorHandling(config.errorLevel, stats)
看了一下 webpack 代码，watch 模式下发生错误时，应该是进入 `compiler.hooks.failed` 而不进入 ` compiler.hooks.done`，可以再确认一下

2023-09-25 16:44 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/index.h5.ts
> +        errorHandling(errorLevel, stats)
看了一下 webpack 代码，watch 模式下发生错误时，应该是进入 `compiler.hooks.failed` 而不进入 ` compiler.hooks.done`，可以再确认一下

2023-09-25 16:44 UTC, Chen-jj commented
另外需要更新一下文档的 **项目配置** 部分

2023-09-26 09:27 UTC, beezen commented
关联更新：
文档：https://github.com/NervJS/taro-docs/pull/179
taro-doctor：https://github.com/NervJS/taro-doctor/pull/8

2023-11-10 05:17 UTC, beezen commented
@Chen-jj 健哥 这个特性如何了  后续cicd上想着能用上

2023-12-26 08:04 UTC, ZEJIA-LIU commented
您好，我已收到您的邮件，我会尽快给你回复，如有急事，请致电13825803202，谢谢。

2023-12-26 09:33 UTC, ZakaryCode approved these changes

2023-12-26 09:33 UTC, ZakaryCode commented
> 这个特性如何了 后续cicd上想着能用上

稍微调整了下，下一个版本上

2023-12-26 10:45 UTC, ZakaryCode approved these changes

2023-12-26 10:47 UTC, merged