Feature type ai
NervJS/taro pull request #14561
Opened 2023-09-16 11:09 UTC by smileying

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-09-18 02:18 UTC, ZakaryCode commented
稍微调整了下类型的代码，还有几个问题同步需要处理一下

2023-09-18 02:28 UTC, ZakaryCode requested changes

2023-09-18 02:28 UTC, ZakaryCode commented on packages/taro/types/api/ai/visionkit.d.ts
> +  interface Origin {
不要存在这种零散的类型，这样书写生成文档时会有冗余，可以写到相关性最高的 namespace 中，或者可以重复多写几次亦可

2023-09-18 02:28 UTC, ZakaryCode commented on packages/taro/types/api/ai/visionkit.d.ts
> +  interface VKBodyAnchor {
应当是原有的 VKAnchor 类型，或许应该重命名之前的类型，并新增

```ts
/** @ignore */
type VKAnchor = VKBodyAnchor | VKDepthAnchor | VKFaceAnchor | VKHandAnchor | VKMarkerAnchor | VKOCRAnchor | VKPlaneAnchor
```

2023-09-18 02:28 UTC, ZakaryCode commented on packages/taro/types/api/ai/visionkit.d.ts
> +    interface IRunOCROption {
无用类型，且缺少相关备注

2023-09-18 02:28 UTC, ZakaryCode commented on packages/taro/types/api/ai/visionkit.d.ts
> +  interface VKBodyAnchor {
可以尝试将几个 Anchor 类型与 VKSession.on 类型关联一下

2023-09-19 08:20 UTC, smileying commented on packages/taro/types/api/ai/visionkit.d.ts
> +  interface Origin {
已修改

2023-09-22 05:57 UTC, ZakaryCode approved these changes

2023-09-22 05:57 UTC, merged