feat: plugin-html支持把div转换成static-view或pure-view
NervJS/taro pull request #14602
Opened 2023-09-25 09:15 UTC by leiyu0932

**这个 PR 做了什么?** (简要描述所做更改)

html-plugin  支持 把 div 转换成 static-view 或 pure-view， 当有事件绑定时还是转换成view， 当没有事件有自定义属性时转换成static-view，  当 没有事件也没有自定义属性时，转换成 pure-view

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #14657
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-10-11 17:26 UTC, Chen-jj requested changes

2023-10-11 17:26 UTC, Chen-jj commented on packages/taro-runtime/src/hydrate.ts
> +  hooks.call('modifyHydrateData', data, node)
补充 node 类型

2023-10-11 17:26 UTC, Chen-jj commented on packages/shared/src/runtime-hooks.ts
> +  modifyHydrateData:(data: Record<string, any>, node) => void
补充 node 类型

2023-10-11 17:26 UTC, Chen-jj commented on packages/taro-plugin-html/src/runtime.ts
> +hooks.tap('modifyHydrateData', (data, node) => {
节点不变的情况下，在 `modifyHydrateData` 修改初始化阶段的映射是正确的。

但我们还需要去考虑 view、static-view、pure-view 节点相互转化的情况， 例如：

```js
conditionA ? <div></div> : <div hoverStartTime="1000"></div>
conditionA ? <div></div> : <div onClick={() => {}}></div>
conditionA ? <div hoverStartTime="1000"></div> : <div onClick={() => {}}></div>
```

因此在 dom 的 setAttribute、removeAttribute、addEventListener、removeEventListener 时机也需要进行节点名称的判断。可以参考 taro-runtime 里的对应处理进行优化

2023-10-12 07:52 UTC, leiyu0932 commented on packages/taro-plugin-html/src/runtime.ts
> +hooks.tap('modifyHydrateData', (data, node) => {
好的， 这块我尽快 处理完善一下

2023-10-17 10:33 UTC, leiyu0932 commented on packages/taro-runtime/src/hydrate.ts
> +  hooks.call('modifyHydrateData', data, node)
在定义的地方 已经补充类型

2023-10-17 10:34 UTC, leiyu0932 commented on packages/taro-plugin-html/src/runtime.ts
> +hooks.tap('modifyHydrateData', (data, node) => {
已更新代码，在 setAttribute、removeAttribute、addEventListener、removeEventListener  增加了 html块级元素判断的相关逻辑， 当为 nodeName 为 html块级元素时 当做  view 来处理

2023-10-17 10:36 UTC, leiyu0932 commented on packages/taro-plugin-html/src/index.ts
这块 span 改到了 行内元素数组里， 与dom-external/inner-html/tags  里的 isBlockElements 方法 保持一致， 要不当使用span元素的时候会有问题， 如果 有特殊原因 不能调整， 我这边 再重新 定义 一个  isBlockElements 方法， 包含span的

2023-10-17 14:54 UTC, leiyu0932 commented on packages/shared/src/runtime-hooks.ts
> +  modifyHydrateData:(data: Record<string, any>, node) => void
这个文件 在 shared 里 类型定义 在 runtime里 感觉shared 引用 runtime里类型不太合适， 看了下 227行也有类似写法 没有加类型， 所以这块 是不是 可以不加类型

2023-10-17 14:56 UTC, leiyu0932 commented on packages/taro-runtime/src/hydrate.ts
> +  hooks.call('modifyHydrateData', data, node as any)
这块 本地 编译 试了 很多种写法  比如  node as TaroElement 等 都编译不过去  一直包  (plugin Typescript) TS2345: Argument of type 'TaroElement' is not assignable to parameter of type 'TaroElement | TaroText'.  这个错， 所以 暂时写成  node as any 可以  build 成功， 辛苦 帮忙看下 这块是否还有更好的写法

2023-10-31 03:26 UTC, Chen-jj requested changes

2023-10-31 03:26 UTC, Chen-jj commented on packages/taro-plugin-html/src/utils.ts
> +  } else if (!node || isAnyEventBinded(node)) {
还需要新增对 catch-view 的判断

2023-10-31 03:26 UTC, Chen-jj commented on packages/taro-runtime/src/dom/element.ts
> +    const name = isBlockElements(this.nodeName) ? VIEW : this.nodeName
插件相关的逻辑应该以 hook 的方式收归在插件内，而尽量不去修改 `runtime.js` 的内容，对插件逻辑进行解耦。

设置属性时，可以使用 `modifySetAttrPayload` 钩子。副作用是只有一个 hook，插件没有办法知道前置状态，只知道当前状态，导致每次都需要 setData `nn`。

2023-10-31 03:26 UTC, Chen-jj commented on packages/taro-runtime/src/dom/element.ts
> +    const name = isBlockElements(this.nodeName) ? VIEW : this.nodeName
同上，使用 `modifyRmAttrPayload` hook。

2023-10-31 03:26 UTC, Chen-jj commented on packages/taro-runtime/src/dom/element.ts
> +    const name = isBlockElements(this.nodeName) ? VIEW : this.nodeName
`addEventListener`、`removeEventListener` 需要新增钩子

2023-11-07 11:09 UTC, Chen-jj approved these changes

2023-11-07 11:50 UTC, merged