fix: h5模式下app.config.js中animation：false路由调整问题修复
NervJS/taro pull request #14673
Opened 2023-10-17 10:38 UTC by voidman2017

**这个 PR 做了什么?** (简要描述所做更改)

当配置了app.config.js中的animation为false的情况下，发生路由跳转。上一个页面元素节点没有被隐藏

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-10-19 02:15 UTC, ZakaryCode requested changes

2023-10-19 02:15 UTC, ZakaryCode commented on packages/taro-router/src/style.ts
> +  .taro_page_shade{
应该将 27-30 行代码挪动到这里修复该问题

2023-10-19 02:53 UTC, voidman2017 commented on packages/taro-router/src/style.ts
> +  .taro_page_shade{
已做调整

2023-10-23 03:00 UTC, ZakaryCode approved these changes
感谢贡献

2023-10-23 04:26 UTC, merged