Feature types data
NervJS/taro pull request #14782
Opened 2023-11-06 09:25 UTC by smileying

**这个 PR 做了什么?** (简要描述所做更改)

更新数据分析及数据缓存API types 

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-11-07 02:41 UTC, ZakaryCode requested changes

2023-11-07 02:41 UTC, ZakaryCode commented on packages/taro/types/api/storage/background-fetch.d.ts
> +      callback: onBackgroundFetchData.Callback,
此处定义错误，需再斟酌

2023-11-07 02:41 UTC, ZakaryCode commented on packages/taro/types/api/storage/index.d.ts
> +      success?: (result: SuccessCallbackResult<T>) => void
该文件中新增的 namespace 基本都缺失 SuccessCallbackResult 类型，同时该定义与标准不符合，需要再看看～

2023-11-07 04:12 UTC, smileying commented on packages/taro/types/api/storage/background-fetch.d.ts
> +      callback: onBackgroundFetchData.Callback,
updated

2023-11-07 04:13 UTC, smileying commented on packages/taro/types/api/storage/index.d.ts
> +      success?: (result: SuccessCallbackResult<T>) => void
已修改~

2023-11-08 05:58 UTC, ZakaryCode approved these changes

2023-11-08 06:17 UTC, merged