fix(runtime): fix event listener not working in root-portal if the pa…
NervJS/taro pull request #14836
Opened 2023-11-15 06:39 UTC by TheKonka

…rent node also listening

#13312

**这个 PR 做了什么?** (简要描述所做更改)
修复当rootportal父节点有监听点击事件时，rootportal内部节点点击事件无效问题

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #13312
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-11-23 02:34 UTC, Fried-dumplings commented
求求官方快快合并，这个问题对我很重要，十分感谢

2023-11-24 07:20 UTC, Chen-jj approved these changes

2023-11-24 07:20 UTC, Chen-jj commented on packages/taro-runtime/src/utils/index.ts
> +  while (node?.parentElement && node.parentElement._path !== ROOT_STR && node.parentElement.nodeName !== 'root-portal') {
改成这样会不会更好些？

```
const parentNodeName = node?.parentElement?.nodeName
while (parentNodeName !== ROOT_STR && parentNodeName !== 'root-portal') {
```

2023-11-24 07:21 UTC, Chen-jj requested changes

2023-11-24 07:21 UTC, Chen-jj commented on packages/taro-runtime/src/utils/index.ts
> +  while (node?.parentElement && node.parentElement._path !== ROOT_STR && node.parentElement.nodeName !== 'root-portal') {
改成这样会不会更好些？

```
const parentNodeName = node?.parentElement?.nodeName
while (parentNodeName !== ROOT_STR && parentNodeName !== 'root-portal') {
```

2023-11-24 09:02 UTC, TheKonka commented on packages/taro-runtime/src/utils/index.ts
> +  while (node?.parentElement && node.parentElement._path !== ROOT_STR && node.parentElement.nodeName !== 'root-portal') {
```ts
export function isParentBinded(node: TaroElement | null, type: string): boolean {
  if (!node) return false
  let res = false
  while ((node = node.parentElement)) {
    const parentNodeName = node.nodeName
    if (parentNodeName === ROOT_STR || parentNodeName === 'root-portal') break
    if (node.__handlers[type]?.length) {
      res = true
      break
    }
  }
  return res
}
```

这样吗，大佬

2023-11-24 11:07 UTC, Chen-jj commented on packages/taro-runtime/src/utils/index.ts
> +  while (node?.parentElement && node.parentElement._path !== ROOT_STR && node.parentElement.nodeName !== 'root-portal') {
@TheKonka 之前忽略了 while 的逻辑，这样改如何：

```
export function isParentBinded (node: TaroElement | null, type: string): boolean {
  while ((node = node?.parentElement || null)) {
    if (!node || node.nodeName === ROOT_STR || node.nodeName === 'root-portal') {
      return false
    } else if (node.__handlers[type]?.length) {
      return true
    }
  }

  return false
}
```

2023-11-24 12:05 UTC, TheKonka commented on packages/taro-runtime/src/utils/index.ts
> +  while (node?.parentElement && node.parentElement._path !== ROOT_STR && node.parentElement.nodeName !== 'root-portal') {
修改了，大佬

2023-11-24 14:25 UTC, Chen-jj approved these changes

2023-11-24 14:25 UTC, merged

2023-11-24 14:25 UTC, Chen-jj commented
感谢贡献~