fix: 修复独立分包组件没有走子编译器的问题
NervJS/taro pull request #14934
Opened 2023-12-05 08:21 UTC by xuanzebin

**这个 PR 做了什么?** (简要描述所做更改)
- 修复独立分包组件没有走子编译器的问题

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #14848
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-12-06 11:19 UTC, Chen-jj requested changes

2023-12-06 11:19 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +  getIndependentPackage (pagePath: string) {
添加返回值类型

2023-12-06 11:19 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +    let res: IndependentPackage | null = null
这块改为 `array.find`，比 foreach 更可读些，代码量也可以少两行

2023-12-06 11:19 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +      if (independentPackage) {
`compileFile` 第二个参数是可选属性，调用时可以不使用 ifelse 区分了吧？

2023-12-06 11:19 UTC, Chen-jj commented on packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
> +          if (independentPackage) {
后续使用了 `?.`，不用再先用 if

2023-12-07 07:38 UTC, Chen-jj approved these changes

2023-12-18 10:34 UTC, merged

2024-07-15 04:46 UTC, 490626721 commented
vue3分包后子包还是提示找不到组件，看了dist文件夹目录，components未打包进去