feat: 新增openLocation的实现
NervJS/taro pull request #14957
Opened 2023-12-11 12:09 UTC by guoenxuan

**这个 PR 做了什么?** (简要描述所做更改)
- 新增taro-h5平台的openLocation实现
- 修改taro-h5的 createLocationChooser 实现 

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-02-02 08:30 UTC, ZakaryCode requested changes

2024-02-02 08:30 UTC, ZakaryCode commented on packages/taro-h5/src/api/location/chooseLocation.ts
> +  const { key = LOCATION_APIKEY, referer = 'myapp', ...opts } = mapOpt
保留 LOCATION_APIKEY 变量缺失提示，即便可以传入 key 依旧需要配置变量才可以正常使用 API

2024-02-02 08:30 UTC, ZakaryCode commented on packages/taro-h5/src/api/location/openLocation.ts
> +      <div class='taro_choose_location'>
模板同上，应当尽可能缩减这段字符串体积

2024-02-05 01:10 UTC, guoenxuan commented on packages/taro-h5/src/api/location/chooseLocation.ts
> +      `
已修改

2024-02-05 01:10 UTC, guoenxuan commented on packages/taro-h5/src/api/location/chooseLocation.ts
> +  const { key = LOCATION_APIKEY, referer = 'myapp', ...opts } = mapOpt
已修改

2024-02-05 01:11 UTC, guoenxuan commented on packages/taro-h5/src/api/location/openLocation.ts
> +
已修正

2024-02-18 03:12 UTC, ZakaryCode requested changes

2024-02-18 03:12 UTC, ZakaryCode commented on packages/taro-h5/src/api/location/openLocation.ts
> +export const openLocation: typeof Taro.openLocation = (options) => {
此处参考 `getLocation` 方法提供 `openLocationByW3CApi` 方法，并保留 `processOpenApi` 外包裹。

2024-02-18 03:12 UTC, ZakaryCode commented on packages/taro-h5/src/api/location/chooseLocation.ts
> +    referer,
为何删除了 coord 参数格式化？

2024-02-18 07:35 UTC, guoenxuan commented
因harmony-hybrid有自己的location实现，该PR的修改不适合放在taro-h5, 我将关闭该PR

2024-02-18 07:36 UTC, closed without merging