feat: 增加navigationStyle配置处理逻辑
NervJS/taro pull request #14960
Opened 2023-12-11 12:29 UTC by guoenxuan

**这个 PR 做了什么?** (简要描述所做更改)
- 增加navigationStyle配置项的处理逻辑trigger `__taroSetNavigationStyle`事件
- spa应用的页面加载时，生命周期触发顺序改为 page.onShow >> page.onReady

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [x] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-12-21 05:55 UTC, ZakaryCode requested changes

2023-12-21 05:55 UTC, ZakaryCode commented on packages/taro-router/src/router/page.ts
> +        this.onReady(page, true)
这里为什么调整 show、ready 的顺序？不太符合页面事件规范

2023-12-21 05:55 UTC, ZakaryCode commented on packages/taro-router/src/router/page.ts
>          this.bindPageEvents(page, pageConfig)
事件顺序

2023-12-21 05:55 UTC, ZakaryCode commented on packages/taro-router/src/router/page.ts
> +      document.querySelector('.taro_router')) as HTMLDivElement
lint

2023-12-21 05:55 UTC, ZakaryCode commented on packages/taro-router/src/router/page.ts
> +        this.isDefaultNavigationStyle() && pageEl?.classList.add('taro_navigation_page')
有无相关样式？

2023-12-25 09:25 UTC, guoenxuan commented on packages/taro-router/src/router/page.ts
> +        this.onReady(page, true)
这里是根据 https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page-life-cycle.html 进行的修改

2023-12-25 12:55 UTC, guoenxuan commented on packages/taro-router/src/router/page.ts
> +        this.isDefaultNavigationStyle() && pageEl?.classList.add('taro_navigation_page')
> 有无相关样式？

样式处理在特定平台下。这里无相关样式。

2023-12-25 12:56 UTC, guoenxuan commented on packages/taro-router/src/router/page.ts
>          this.bindPageEvents(page, pageConfig)
这里是根据 https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page-life-cycle.html 进行的修改

2023-12-25 12:57 UTC, guoenxuan commented on packages/taro-router/src/router/page.ts
> +      document.querySelector('.taro_router')) as HTMLDivElement
已处理

2023-12-26 06:15 UTC, ZakaryCode commented on packages/taro-router/src/router/page.ts
> +        this.isDefaultNavigationStyle() && pageEl?.classList.add('taro_navigation_page')
multi-page 的 load 事件中可以补充类似逻辑对齐一下

另外这里有个关联的 issue #14935 目前仅在 iOS 复现，可以考虑一起修复。大致是因为快速切换页面时，load 事件没有触发导致回调函数未执行（或者可以帮忙标注 FIXME

2023-12-26 09:15 UTC, guoenxuan commented on packages/taro-router/src/router/page.ts
> +        this.isDefaultNavigationStyle() && pageEl?.classList.add('taro_navigation_page')
multi-page已补充类似逻辑。 已标注FIXME

2023-12-26 10:56 UTC, ZakaryCode approved these changes

2023-12-26 11:10 UTC, merged