fix: 组件Image兼容mode为空串和src无值的情况
NervJS/taro pull request #14963
Opened 2023-12-11 12:34 UTC by guoenxuan

**这个 PR 做了什么?** (简要描述所做更改)
Image组件兼容mode=""和src无值的情况

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-12-12 08:51 UTC, ZakaryCode requested changes

2023-12-12 08:51 UTC, ZakaryCode commented on packages/taro-components/src/components/image/image.tsx
> +    const compMode = mode || 'scaleToFill'
mode 已经有默认值，这里不太可能为空？

2023-12-12 08:51 UTC, ZakaryCode commented on packages/taro-components/package.json
> +    "generate:lib": "node -e \"require('fs').mkdirSync('lib', { recursive: true })\"",
为什么需要在这里写脚本？应该可以使用 mkdirp 替代？

2023-12-12 08:51 UTC, ZakaryCode commented on packages/taro-components/src/components/image/image.tsx
> +          src ? (
为空时移除 img 节点，这是从小程序端同步的逻辑？

2023-12-12 10:56 UTC, guoenxuan commented on packages/taro-components/package.json
> +    "generate:lib": "node -e \"require('fs').mkdirSync('lib', { recursive: true })\"",
这里是为了兼容windows系统。mkdirp在windows系统上不存在

2023-12-12 11:14 UTC, guoenxuan commented on packages/taro-components/src/components/image/image.tsx
> +    const compMode = mode || 'scaleToFill'
mode: "" 和不写mode字段有点区别。这里是处理用户mode: "" 这种情况

2023-12-12 14:31 UTC, ZakaryCode commented on packages/taro-components/package.json
> +    "generate:lib": "node -e \"require('fs').mkdirSync('lib', { recursive: true })\"",
mkdirp 是项目内已有的依赖，可以直接添加到对应包内的 devDeps 中

2023-12-13 06:09 UTC, guoenxuan commented on packages/taro-components/src/components/image/image.tsx
> +    const compMode = mode || 'scaleToFill'
应该可以，但需要把mode单独提出来声明，因为原有已经用了const。那改成 let { mode = 'scaleToFill' } = this ？

2023-12-13 06:59 UTC, handsomeliuyang commented on packages/taro-components/src/components/image/image.tsx
> +          src ? (
1. 使用Image控件的用法：通过css设置背景，而不设置src，如<Image className="service-phone-image"></Image>
2. 在h5端运行时，src为空时的img控件，会显示出边框，显示效果有问题

2023-12-13 08:38 UTC, guoenxuan commented on packages/taro-components/src/components/image/image.tsx
> +    const compMode = mode || 'scaleToFill'
已合并，去掉compMode变量

2023-12-13 08:38 UTC, guoenxuan commented on packages/taro-components/package.json
> +    "generate:lib": "node -e \"require('fs').mkdirSync('lib', { recursive: true })\"",
已改成mkdirp

2023-12-21 03:11 UTC, ZakaryCode commented on packages/taro-components/src/components/image/image.tsx
> +          src ? (
这种用法听起来不太合理，小程序端可以这么做么？

2023-12-21 03:14 UTC, ZakaryCode requested changes

2023-12-21 03:14 UTC, ZakaryCode commented on packages/taro-components/src/components/image/image.tsx
> +    mode ||= 'scaleToFill'
额，不需要解析值啊

```ts
const mode = this.mode ||= 'scaleToFill'
```

2023-12-25 13:15 UTC, guoenxuan commented on packages/taro-components/src/components/image/image.tsx
> +          src ? (
通过css设置背景，在小程序端可以生效

2023-12-25 13:21 UTC, guoenxuan commented on packages/taro-components/src/components/image/image.tsx
> +    mode ||= 'scaleToFill'
> 额，不需要解析值啊
> 
> ```ts
> const mode = this.mode ||= 'scaleToFill'
> ```

已处理

2023-12-26 12:07 UTC, ZakaryCode approved these changes

2023-12-26 12:07 UTC, merged