fix: 优化路由接口以及修复onResize回调参数缺失的字段
NervJS/taro pull request #14967
Opened 2023-12-11 13:04 UTC by guoenxuan

**这个 PR 做了什么?** (简要描述所做更改)
- 路由接口增加url是否是有效页面的url判断
- page.onResize增加deviceOrientation、size.screenWidth/screenHeight字段信息

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-12-27 02:09 UTC, ZakaryCode requested changes

2023-12-27 02:09 UTC, ZakaryCode commented on packages/taro-router/src/events/resize.ts
> +          screenHeight: window.screen.height,
新增回调字段请在类型中呈现

2023-12-27 02:09 UTC, ZakaryCode commented on packages/taro-router/src/api.ts
> +            const res = { errMsg: `${method}:fail page ${pagePath} is not found` }
需要触发 onPageNotFound 事件

2023-12-27 02:09 UTC, ZakaryCode commented on packages/taro-router/src/api.ts
> +            return
如果 fail 或 compete 是 function，这里应该 `return resolve(res)`，反之则为 `return reject(res)`，下面的 catch 中也存在类似问题

2023-12-29 01:57 UTC, guoenxuan commented on packages/taro-router/src/events/resize.ts
> +          screenHeight: window.screen.height,
已补上

2023-12-29 01:57 UTC, guoenxuan commented on packages/taro-router/src/api.ts
> +            return
已修改

2023-12-29 01:59 UTC, guoenxuan commented on packages/taro-router/src/api.ts
> +            const res = { errMsg: `${method}:fail page ${pagePath} is not found` }
这里参考了微信小程序的行为。微信小程序在用路由函数跳转到不存在的页面时，并不会触发onPageNotFound 事件，而是返回了错误信息。

2024-02-02 02:54 UTC, ZakaryCode approved these changes
感谢贡献～

2024-02-02 03:28 UTC, merged