fix(h5): h5 端开启 enablePullDownRefresh 白屏问题修复
NervJS/taro pull request #14992
Opened 2023-12-15 10:46 UTC by voidman2017

**这个 PR 做了什么?** (简要描述所做更改)

修复  H5 端开启 enablePullDownRefresh: true 页面白屏问题

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2023-12-18 02:25 UTC, ZakaryCode requested changes
另外 node16 测试 CI 挂了，修复上述问题后需要注意测试用例情况

2023-12-18 02:25 UTC, ZakaryCode commented on packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
> +      setTimeout(()=>{
这里的修改看起来没有必要

2023-12-18 02:25 UTC, ZakaryCode commented on packages/taro-plugin-vue2/src/runtime/connect.ts
> +            'taro-pull-to-refresh-core',
需同步修改

```diff
packages/taro-plugin-react/src/runtime/connect.ts:76

-          customWrapper || 'taro-pull-to-refresh',
+           customWrapper || 'taro-pull-to-refresh-core',
```

2023-12-18 02:28 UTC, voidman2017 commented on packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
> +      setTimeout(()=>{
是因为如果直接在onPullDownRefresh中同步调用taro.stopPullDownRefresh，会导致无法回到初始状态，高度为51px

2023-12-18 02:51 UTC, ZakaryCode commented on packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
> +      setTimeout(()=>{
正常流程中不太会有这种情况，一般会在时延或者一些操作后还原高度

2023-12-18 02:53 UTC, ZakaryCode commented on packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
> +      setTimeout(()=>{
不过这可能对一些新人或者特殊场景造成困扰，在这里时延也算是合理

> 请在为 setTimeout 第二参数补上 0 后 resolve conversation

2023-12-18 02:53 UTC, voidman2017 commented on packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
> +      setTimeout(()=>{
实际场景确实是异步请求数据更新的方式居多，但是也存在同步更新的场景下导致该异常情况。如果确认不需要，可以删除该部分代码

2023-12-21 02:51 UTC, ZakaryCode commented on packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
> +      },0)
lint

2023-12-21 03:46 UTC, ZakaryCode approved these changes
感谢贡献~

2023-12-21 03:46 UTC, merged