refactor: update swiper@11 in taro-components
NervJS/taro pull request #15122
Opened 2024-01-17 07:29 UTC by TheKonka

**这个 PR 做了什么?** (简要描述所做更改)
- 升级 h5端 swiper@11.0.5
- 暂时使用 tsx 替代 ts-node 因为ts-node在 node 20 环境下报错，相关issue:
 https://github.com/TypeStrong/ts-node/issues/2100

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #15082
- [ ] 新功能(Feature)
- [x] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-01-17 08:33 UTC, xuanzebin commented
`@tarojs/components-react` 中的 swiper 版本应该需要同步进行替换

2024-02-02 08:01 UTC, xuanzebin commented
代码改动量有点大，下周我再验证一下😁 @TheKonka

2024-02-04 09:02 UTC, xuanzebin requested changes

2024-02-07 01:54 UTC, TheKonka commented on packages/taro-components/src/components/swiper/swiper.tsx
> +      modules: [Pagination, Autoplay, Zoom],
大佬，问题应该都修复咯，有空的时候麻烦再帮忙验证下

2024-03-14 07:45 UTC, ZEJIA-LIU commented on packages/taro-components/src/components/swiper/swiper.tsx
> +      modules: [Pagination, Autoplay, Zoom],
你好，我刚刚验证了一下，发现手动切换 swiperItem 的时候，会出现卡顿甚至无展示的情况，

2024-03-15 02:07 UTC, TheKonka commented on packages/taro-components/src/components/swiper/swiper.tsx
> +      modules: [Pagination, Autoplay, Zoom],
@ZEJIA-LIU  谢谢，卡顿问题我测试发现可能是 ios上面chrome浏览器的问题， 我试了包括ios上面的safari，安卓手机都没有卡顿。这个卡顿问题即使是不用这个pr 的版本或者 swiperjs 官方网站的 [demo](https://swiperjs.com/demos) 也能复现。
删除SwiperItem无展示的问题修复了

2024-04-18 14:29 UTC, closed without merging