fix(h5): 开启预构建时路由表未与pages同步
NervJS/taro pull request #15227
Opened 2024-02-17 10:01 UTC by Hector-Chong

**这个 PR 做了什么?** (简要描述所做更改)
#15225 

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-02-18 02:28 UTC, ZakaryCode commented
请注意提交 PR 时 lint 等相关问题，另外该项改动将会导致 prebundle 在生产环境中体积增大，应当针对于该场景优化，或者通过删除虚拟模块 cache 来调整更新策略，而非插入代码的方式。

2024-02-18 02:29 UTC, ZakaryCode requested changes
请注意提交 PR 时 lint 等相关问题，另外该项改动将会导致 prebundle 在生产环境中体积增大，应当针对于该场景优化，或者通过删除虚拟模块 cache 来调整更新策略，而非插入代码的方式。

2024-02-18 06:53 UTC, Hector-Chong commented
> 请注意提交 PR 时 lint 等相关问题，另外该项改动将会导致 prebundle 在生产环境中体积增大，应当针对于该场景优化，或者通过删除虚拟模块 cache 来调整更新策略，而非插入代码的方式。

未查询到删除虚拟模块的 Cache API，能否通过 hook 监听 `app.config.ts` 变化，并重写虚拟模块 `app.boot.js`？

2024-02-18 08:32 UTC, Hector-Chong commented
变更修复方式，将 `app.config` 设置为 `buildDependencies` 选项。

2024-02-19 02:14 UTC, ZakaryCode approved these changes

2024-02-19 02:28 UTC, merged