fix: 修正app的onShow/onHide页面路径信息
NervJS/taro pull request #15230
Opened 2024-02-19 02:02 UTC by guoenxuan

**这个 PR 做了什么?** (简要描述所做更改)
修正App.onShow和onHide时的页面路径信息

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-02-19 02:13 UTC, ZakaryCode commented
这里是应用级配置，按照小程序文档，此处应当返回 `启动小程序的路径` 而非当前页面路径

2024-02-19 03:26 UTC, guoenxuan commented
> 这里是应用级配置，按照小程序文档，此处应当返回 `启动小程序的路径` 而非当前页面路径

经过测试验证，微信小程序运行时，如果当前处于某个页面，path信息是该页面的路径

2024-02-21 09:27 UTC, ZakaryCode requested changes

2024-02-21 09:27 UTC, ZakaryCode commented on packages/taro-router/src/router/mpa.ts
>      }else{
lint

2024-02-21 09:27 UTC, ZakaryCode commented on packages/taro-router/src/router/mpa.ts
> +    const path = currentPath.substring(0, currentPath.indexOf('?'))
备注一下和文档的差异，避免二次调整

2024-02-21 09:27 UTC, ZakaryCode commented on packages/taro-router/src/router/mpa.ts
> +      Current.page?.onShow?.()
这应该会与页面内的 show 事件重复？

2024-02-22 08:52 UTC, guoenxuan commented on packages/taro-router/src/router/mpa.ts
>      }else{
已修正

2024-02-22 08:55 UTC, guoenxuan commented on packages/taro-router/src/router/mpa.ts
> +      Current.page?.onShow?.()
保留spa中页面onShow处理，经验证不会重复触发，行为与微信小程序中表现的一致。已去掉mpa中的处理。

2024-02-23 08:46 UTC, ZakaryCode approved these changes
感谢贡献

2024-02-23 08:46 UTC, merged