fix: 修复设置 devServer 的 historyApiFallback 配置不生效问题
NervJS/taro pull request #15310
Opened 2024-03-06 13:06 UTC by bluescurry

**这个 PR 做了什么?** (简要描述所做更改)

修改了这个问题 https://github.com/NervJS/taro/issues/15281

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #15281
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-03-13 08:19 UTC, bluescurry commented
@Chen-jj 是否可以优先看下这个 PR，多页面现在无法在本地调试

2024-03-14 03:08 UTC, ZEJIA-LIU approved these changes

2024-03-14 03:12 UTC, ZEJIA-LIU requested changes
webpack4 也有类似的代码，麻烦一起修改了

2024-03-14 03:28 UTC, ZEJIA-LIU approved these changes

2024-03-14 05:55 UTC, merged