types: 修改request请求api的complete res参数类型，与success一致
NervJS/taro pull request #15392
Opened 2024-03-22 15:16 UTC by phy-lei

**这个 PR 做了什么?** (简要描述所做更改)
修改taro api request的complete配置中res的参数类型，这个类型与successCallback是一致的：  
![image](https://github.com/NervJS/taro/assets/58167763/a08c268f-6d21-45f6-88e4-6356cdbd81b9)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [x] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-05-03 07:13 UTC, ZakaryCode requested changes

2024-05-03 07:13 UTC, ZakaryCode commented on packages/taro/types/api/network/request.d.ts
> +      complete?: (res: SuccessCallbackResult<T>) => void
两者还是有区别的，比如 data 这些都不应该是必选参数，如果一定要改或许应该这样

```ts
Partial<SuccessCallbackResult> & TaroGeneral.CallbackResult
```

2024-05-06 07:50 UTC, ZakaryCode approved these changes

2024-05-07 07:27 UTC, ZEJIA-LIU approved these changes

2024-05-07 11:45 UTC, merged