fix: 当使用自定义的编译器编译时，不安装@tarojs/plugin-framework-react依赖会报错的bug
NervJS/taro pull request #15471
Opened 2024-04-07 09:57 UTC by phy-lei

**这个 PR 做了什么?** (简要描述所做更改)
修复该issuse #15470 

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-04-10 09:15 UTC, koppthe requested changes
感谢提交~

代码没有处理 framework 配置项为空的场景，另外建议在原有的 switch 单独添加 case 'solid' 即可，以兼容用户未正确设置 framework 配置项的情况。

2024-04-10 09:47 UTC, phy-lei commented
> 感谢提交~
> 
> 代码没有处理 framework 配置项为空的场景，另外建议在原有的 switch 单独添加 case 'solid' 即可，以兼容用户未正确设置 framework 配置项的情况。

感谢建议，确实没有处理 framework 配置项为空，我会加上。但是我不太建议再加额外的分支去处理solid，因为难免也会有可能用户使用的是别的框架svelte，angular等，那到时候可能这里还得继续加分支。一般我们自定义的编译器可以在配置的plugins中注入，这样更加开放性。如果后面能把solid引入官方包里，那自然多加个case比较好，但目前还不是。以上是我的想法，期待您的回复～

2024-04-11 02:14 UTC, koppthe commented
> > 感谢提交~
> > 代码没有处理 framework 配置项为空的场景，另外建议在原有的 switch 单独添加 case 'solid' 即可，以兼容用户未正确设置 framework 配置项的情况。
> 
> 感谢建议，确实没有处理 framework 配置项为空，我会加上。但是我不太建议再加额外的分支去处理solid，因为难免也会有可能用户使用的是别的框架svelte，angular等，那到时候可能这里还得继续加分支。一般我们自定义的编译器可以在配置的plugins中注入，这样更加开放性。如果后面能把solid引入官方包里，那自然多加个case比较好，但目前还不是。以上是我的想法，期待您的回复～ ![image](https://private-user-images.githubusercontent.com/58167763/321189304-bcdecda8-a839-4f5e-9301-096499fd551b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDEyMzQsIm5iZiI6MTcxMjgwMDkzNCwicGF0aCI6Ii81ODE2Nzc2My8zMjExODkzMDQtYmNkZWNkYTgtYTgzOS00ZjVlLTkzMDEtMDk2NDk5ZmQ1NTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAyMDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMGM4NWYwM2EyODNjMjk0MmExNmYzNjMwY2U0MmJlYjgxMGJiMjY5MDEzMDYzMWU1NWQ0YjAwN2I5OGE2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lqUoa8H6jjHfPhchBeYfrlAmHd1wpKWikjmpB497IWg) 刚试了配置空的framework，taro的cli也跑不起来

同意你的观点，从可扩展性的角度来看，映射对象的方案更优。

2024-04-11 02:16 UTC, koppthe approved these changes

2024-04-11 02:58 UTC, merged