fix: 修改判断，考虑初始绑定的事件为空的情况
NervJS/taro pull request #15540
Opened 2024-04-19 04:11 UTC by shushu2013

**这个 PR 做了什么?** (简要描述所做更改)

修改判断，考虑初始绑定的事件为空（没有旧的事件绑定的情况）

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue: fix #15530
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）
- [ ] 鸿蒙（harmony）

2024-04-20 07:14 UTC, koppthe requested changes
感谢 PR~  这里的判断逻辑不用修改，应该是修改以下代码吧

```js
unstable_batchedUpdates(() => newEventHandler.call(this, e))
```

改为
```js
unstable_batchedUpdates(() => newEventHandler && newEventHandler.call(this, e))
```

2024-04-20 10:22 UTC, shushu2013 commented
> 感谢 PR~ 这里的判断逻辑不用修改，应该是修改以下代码吧
> 
> ```js
> unstable_batchedUpdates(() => newEventHandler.call(this, e))
> ```
> 
> 改为
> 
> ```js
> unstable_batchedUpdates(() => newEventHandler && newEventHandler.call(this, e))
> ```

newEventHandler 和 oldEventHandler 都不存在，应该不用运行到这一步再判断，直接第一步就判断处理，就可以了吧

2024-04-22 08:10 UTC, shushu2013 commented
> ```js
> node.removeEventListener(eventName, undefined)
> ```

再这样改下就可以了
```
oldEventHandler && node.removeEventListener(eventName, oldEventHandler)
```

2024-05-10 07:01 UTC, koppthe approved these changes

2024-05-10 07:48 UTC, merged

2024-09-05 02:01 UTC, onegaop commented
> ```js
> newEventHandler
> ```

要判断，taro 3.6.35 报错了