[CLI] Add chalk warning
NervJS/taro pull request #7125
Opened 2020-07-21 09:21 UTC by iugo

path.join(projectDir, 'client', 'package.json') 大概率也是不正确的, 所以进行提醒.

**这个 PR 做了什么?** (简要描述所做更改)

新增的 CLI 提醒.

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [x] 其他，请描述(Other, please describe):

完善的 CLI 的用户体验, 避免出现无法认知的 `UnhandledPromiseRejectionWarning` 错误.

**这个 PR 满足以下需求:**

- [ ] 提交到 master 分支
- [ ] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [ ] 所有测试用例已经通过
- [ ] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ ] 在本地测试可用，不会影响到其它功能

**这个 PR 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] QQ 轻应用
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

**其它需要 Reviewer 或社区知晓的内容：**

2020-07-28 11:10 UTC, Chen-jj commented
@iugo 48 行 `path.join(projectDir, 'client', 'package.json') ` 用于取云开发项目的 package.json 文件，直接报 warning 并不是很妥当。

2020-08-10 09:29 UTC, iugo commented
我当初遇到的问题是操作不当, 然后没有在合适的地方提示出错.

没有使用云开发.

更合理的情况应该是, 如果真的在用云开发, 则不抛错, 继续就行, 如果不在用云开发, 再警告.

可能最终判断一下 package.json 文件是否存在才是更好的.

2020-08-19 06:45 UTC, Chen-jj requested changes

2020-08-19 06:45 UTC, Chen-jj commented on packages/taro-cli/src/create/page.ts
> +        chalk.yellow('请确认是在正确的项目目录下执行 Taro 命令.')
改成这样咯：

```js
console.log(chalk.yellow('请在项目根目录下执行 taro create 命令!'))
process.exit(0)
```

原因：

1. `chalk.yellow` 还需要调用 `console.log` 才会输出到屏幕。
2. 文案改为更加清晰直接
3. 报错直接退出运行，否则还会报 promise 那堆报错。

2020-08-20 09:11 UTC, iugo commented on packages/taro-cli/src/create/page.ts
> +        chalk.yellow('请确认是在正确的项目目录下执行 Taro 命令.')
我是看到 https://github.com/NervJS/taro/blob/08b8e34213b2702602dc9cecc7ebc4320672a487/packages/taro-cli/src/create/page.ts#L72 才简单写了一下, 还以为内部会抛错. 我会再改一下.

2020-08-20 09:12 UTC, iugo commented on packages/taro-cli/src/create/page.ts
> +        chalk.yellow('请确认是在正确的项目目录下执行 Taro 命令.')
已修改: https://github.com/NervJS/taro/pull/7125/commits/c52e874edc52decea069b7f69b5132120bdf5699

2020-08-20 09:27 UTC, Chen-jj commented on packages/taro-cli/src/create/page.ts
> +        chalk.yellow('请确认是在正确的项目目录下执行 Taro 命令.')
尴尬，那里应该是漏了 `console.log`。

感谢大佬 PR！

2020-08-20 09:27 UTC, Chen-jj approved these changes

2020-08-20 10:45 UTC, merged