feat(taro-runtime): consistent window object
NervJS/taro pull request #8105
Opened 2020-11-23 13:09 UTC by atzcl

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [x] 新功能(Feature)
- [x] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 满足以下需求:**

- [x] 提交到 master 分支
- [x] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [x] 所有测试用例已经通过
- [x] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [x] 在本地测试可用，不会影响到其它功能

**这个 PR 涉及以下平台:**

- [x] 微信小程序
- [x] 支付宝小程序
- [x] 百度小程序
- [x] 头条小程序
- [x] QQ 轻应用
- [x] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [x] 移动端（React-Native）

**其它需要 Reviewer 或社区知晓的内容：**
close https://github.com/NervJS/taro/issues/8021

2020-12-04 02:35 UTC, Chen-jj requested changes

2020-12-04 02:35 UTC, Chen-jj commented on packages/taro-runtime/src/bom/window.ts
> +  Reflect.ownKeys(global).forEach(property => {
`Reflect` 并不是所有小程序框架在所有机型都兼容，这里需要修改下。

2020-12-05 05:26 UTC, atzcl commented on packages/taro-runtime/src/bom/window.ts
> +  Reflect.ownKeys(global).forEach(property => {
@Chen-jj 改用 `getOwnPropertyNames`、`getOwnPropertySymbols` 来枚举 global 属性了

2020-12-05 07:03 UTC, atzcl commented
ci 挂了，但是应该跟这个 pr 无关

2020-12-11 12:31 UTC, Chen-jj approved these changes

2020-12-11 12:32 UTC, Chen-jj commented
感谢贡献～

2020-12-11 13:21 UTC, merged