补充uploadFile的timeout,fileName参数功能
NervJS/taro pull request #8184
Opened 2020-12-02 12:53 UTC by zhaoguoweiLLHC

**这个 PR 做了什么?** (简要描述所做更改)
补充了h5下的uploadFile的timeout,fileName参数功能

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 满足以下需求:**

- [x] 提交到 master 分支
- [x] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [x] 所有测试用例已经通过
- [x] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [x] 在本地测试可用，不会影响到其它功能

**这个 PR 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] QQ 轻应用
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

**其它需要 Reviewer 或社区知晓的内容：**

2020-12-12 08:41 UTC, ZakaryCode commented
对于 timeout 没有什么疑问，但是 fileName 并不是一个标准的参数，它不应该在 taro 中实现，详细理由参考 #8112 中的回复，如果希望记录文件名并修改应该在 formData 中添加参数记录，然后在服务端修改

> [参考文档](https://developers.weixin.qq.com/miniprogram/dev/api/network/upload/wx.uploadFile.html)

2020-12-12 08:43 UTC, ZakaryCode requested changes
fileName 是一个非标准参数，合并将在移除 fileName 后完成

2020-12-14 07:31 UTC, zhaoguoweiLLHC commented
> fileName 是一个非标准参数，合并将在移除 fileName 后完成

哈哈，我见taro文档有写filename 参数，也标明了是H5特有的。所以就想着修复下。
如果不需要filename参数实现的话，记得和文档部门沟通协商哈。
到时候如果文档里去掉filename参数了，我就把filename功能也去掉重新再PR下。
![image](https://user-images.githubusercontent.com/23580548/102050804-6d61d080-3e1e-11eb-9ce3-9272f1161b02.png)

2020-12-14 08:31 UTC, ZakaryCode approved these changes
这是一个 2.x 已经合入的特性，考虑到用户平滑升级因素，将在 3.x 合入该特性。

2020-12-14 15:10 UTC, merged