fix(alipay): 修复 my.getStorageSync 返回 falsy 值时的判断错误
NervJS/taro pull request #8186
Opened 2020-12-02 18:34 UTC by GoodbyeNJN

**这个 PR 做了什么?** (简要描述所做更改)

将原有的短路运算改为明确地判断是否为null

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #8170 
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 满足以下需求:**

- [x] 提交到 master 分支
- [x] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [x] 所有测试用例已经通过
- [x] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [x] 在本地测试可用，不会影响到其它功能

**这个 PR 涉及以下平台:**

- [ ] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] QQ 轻应用
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

**其它需要 Reviewer 或社区知晓的内容：**

2020-12-02 19:01 UTC, Chen-jj requested changes

2020-12-02 19:01 UTC, Chen-jj commented on packages/taro/apis/alipay.js
> +            if (data === null) {
data === null 这个条件，当 getStorageSync 返回 { data: undefined } 时，返回了 undefined，而微信那边是空字符串，这里感觉需要兼容一下

2020-12-03 01:56 UTC, GoodbyeNJN commented on packages/taro/apis/alipay.js
> +            if (data === null) {
这个文件的api应该只对支付宝小程序生效吧，如果是的话可以不考虑兼容微信那边的逻辑。
而支付宝官方的[文档](https://opendocs.alipay.com/mini/api/ox0wna)里没有明确提到获取一个不存在的key，或者调用异常时返回的data会是什么值，但在页面上的交互式预览中可以测得获取不存在的key会返回null，暂时无法测得调用异常会返回什么值，所以此处暂时是用===null去做的判断。

2020-12-03 06:16 UTC, Chen-jj commented on packages/taro/apis/alipay.js
> +            if (data === null) {
`Taro.getStorageSync('unknow_key')` 的时候 data 的确是 null，而不是 undefined，这里我看错了。

但还有一个判断有误，`APDataAPDataStorage` 是 undefined 不是 null，所以现在获取一个不存在的 storage 值会返回 undefined，应该返回空字符串，幸苦改下哈：

![image](https://user-images.githubusercontent.com/11807297/100971428-d8372000-3571-11eb-97c2-d4ec5bb24f66.png)

2020-12-04 02:07 UTC, Chen-jj approved these changes

2020-12-04 02:08 UTC, merged