fix: 补全 cover-view 在配合 map 组件使用时的特殊属性
NervJS/taro pull request #8954
Opened 2021-03-23 02:26 UTC by jay4q

**这个 PR 做了什么?** (简要描述所做更改)

补全了 cover-view 在配合微信小程序 map 组件使用时，自定义气泡框所需要的特殊属性，`marker-id` 和 `slot`

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 满足以下需求:**

- [x] 提交到 master 分支
- [x] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [ ] 所有测试用例已经通过
- [ ] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ ] 在本地测试可用，不会影响到其它功能

**这个 PR 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] QQ 轻应用
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

**其它需要 Reviewer 或社区知晓的内容：**

2021-03-25 05:51 UTC, Chen-jj requested changes

2021-03-25 05:51 UTC, Chen-jj commented on packages/shared/src/components.ts
> +  'marker-id': '',
这两个属性是微信特有的，麻烦修改到 `taro-weapp` 这个包里对应的 `components.ts` 文件。

另外，对象 `key` 的单引号需要去掉，eslint 会过不了～

2021-03-25 05:52 UTC, Chen-jj commented
@jay4q 麻烦修改一下代码。另外能否提供一个成功为 `Map` 自定义气泡的 Demo？之前尝试过加这些属性也没有成功

2021-03-26 02:35 UTC, jay4q commented on packages/shared/src/components.ts
> +  'marker-id': '',
> @jay4q 麻烦修改一下代码。另外能否提供一个成功为 `Map` 自定义气泡的 Demo？之前尝试过加这些属性也没有成功

当时我是开发环境下，直接修改的本地 `node_modules` 下的 `@tarojs/shared/dist/index.js` 文件成功的，不好意思没考虑到跨平台的情况 😅

``` js
// var CoverView = Object.assign({ 'scroll-top': 'false', 'marker-id': '', 'slot': '' }, touchEvents)
var CoverView = Object.assign({ 'scroll-top': 'false' }, touchEvents)
```

2021-03-31 07:27 UTC, Chen-jj commented
@jay4q 麻烦修复一下 lint 哈

![image](https://user-images.githubusercontent.com/11807297/113106541-7774d700-9235-11eb-967f-25aa633c0194.png)

另外能提供一下设置气泡的 demo 么，或者代码片段

2021-04-02 06:21 UTC, jay4q commented
> @jay4q 麻烦修复一下 lint 哈
> 
> ![image](https://user-images.githubusercontent.com/11807297/113106541-7774d700-9235-11eb-967f-25aa633c0194.png)
> 
> 另外能提供一下设置气泡的 demo 么，或者代码片段

OK 改好了～

在以往版本里，我是这样做的：

## 修改 Taro 代码

> 位于 /node_modules/@tarojs/shared/dist/index.js

``` js
// var CoverView = Object.assign({ 'scroll-top': 'false' }, touchEvents)
var CoverView = Object.assign({ 'scroll-top': 'false', 'marker-id': '', 'slot': '' }, touchEvents)
```

## 正常使用地图组件即可

``` tsx
  <Map
    // ...
    markers={markers}
  >
    <CoverView
      // @ts-ignore
      slot='callout'
    >
      {
        markers.map((item, i) => (
          <CoverView marker-id={i} style='display:inline'>
            { /** 自定义样式的 callout */ }
          </CoverView>
        ))
      }
    </CoverView>
  </Map>
```

2021-04-07 08:36 UTC, Chen-jj commented
@jay4q 测试跪了，麻烦再在 Taro 仓库根目录跑一下 `lerna run updateSnapshot --scope @tarojs/mini-runner` 更新一下 snapshot 哈～

2021-04-25 03:38 UTC, Chen-jj commented
@jay4q 我们来改一下测试用例吧：#9184，这个 PR 先关了哈，感谢贡献～

2021-04-25 03:38 UTC, closed without merging