fix: 解决 h5 navigateBack调用delta>1时,路由栈异常问题
NervJS/taro pull request #8979
Opened 2021-03-29 10:29 UTC by yoonzm

**这个 PR 做了什么?** (简要描述所做更改)
解决 h5 navigateBack调用delta>1时,路由栈异常问题

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) [#2178](https://github.com/NervJS/taro/issues/2178)
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 满足以下需求:**

- [ ] 提交到 master 分支
- [x] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [x] 所有测试用例已经通过
- [x] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [x] 在本地测试可用，不会影响到其它功能

**这个 PR 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] QQ 轻应用
- [ ] 快应用平台（QuickApp）
- [x] Web 平台（H5）
- [ ] 移动端（React-Native）

**其它需要 Reviewer 或社区知晓的内容：**

2021-03-31 11:27 UTC, Chen-jj requested changes

2021-03-31 11:27 UTC, Chen-jj commented on packages/taro-router/src/router.ts
> +        for (let i = 0; i < Math.abs(historyBackDelta) - 1; i++) {
使用 `while (historyBackDelta-- > 1)` 来进行循环更合适，按照你的思路， `historyBackDelta` 最终**必须重置为 1**。否则正常触发浏览器后退（如点击后退按钮）时，会有问题。

2021-03-31 11:27 UTC, Chen-jj commented on packages/taro-router/src/router.ts
> +          stacks.pop()
不能简单地 `stacks.pop()`，应该使用 `unloadPage()`。否则页面组件的销毁阶段生命周期不会触发、页面组件树也没有在 DOM 中卸载。

2021-03-31 11:28 UTC, Chen-jj commented
@yoonzm 的确存在此问题，请按评论修改代码～

2021-04-01 02:52 UTC, yoonzm commented on packages/taro-router/src/router.ts
> +          stacks.pop()
好的，我思考一下

2021-04-01 03:02 UTC, yoonzm commented on packages/taro-router/src/router.ts
> +          stacks.pop()
@Chen-jj 

1. 我所理解的是一次性返回多层页面，对于用户来说体验上并不是一个一个的关掉页面，并不需要触发中间的每个页面的生命周期，不知道这样是否会存在问题
2. 页面组件树的dom卸载体现在哪里呢，我看到unloadPage中是`onHide``onUnload`两个生命周期和`stacks.pop()`
```
function unloadPage (page: PageInstance | null) {
  if (page != null) {
    page.onHide!()
    stacks.pop()
    page.onUnload()
  }
}
```

2021-04-07 08:33 UTC, Chen-jj commented on packages/taro-router/src/router.ts
> +          stacks.pop()
1. 每个页面是一个 React 组件，销毁阶段的生命周期需要正常触发，可能存在定时器回收等逻辑。
2. `page.onHide!()` 触发页面的 onHide 生命周期，`page.onUnload()` 会触发页面组件从 React 中卸载。

> 页面组件树的dom卸载体现在哪里呢

体现在 DOM 树，Inspect 一下看看 DOM 树中页面对应的 DOM 没有被卸载，应该就明白了

2021-04-10 16:02 UTC, yoonzm commented
已重新提交提交pr [9073](https://github.com/NervJS/taro/pull/9073)

2021-04-10 16:02 UTC, closed without merging