fix(@tarojs/extend): query 判空&抛出异常
NervJS/taro pull request #9328
Opened 2021-05-14 06:55 UTC by alexlees

**这个 PR 做了什么?** (简要描述所做更改)

 对createSelectorQuery 做判空，并在错误时抛出异常

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #9327
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [x] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-05-31 11:30 UTC, alexlees commented
@luckyadam 能review下吗，很小的点，还没能合并上去

2021-06-11 05:35 UTC, alexlees commented
@Chen-jj review please.

2021-07-08 11:41 UTC, Chen-jj requested changes

2021-07-08 11:41 UTC, Chen-jj commented on packages/taro-extend/src/jquery/zepto.js
>            Taro.createSelectorQuery().select('#' + this[0].uid).boundingClientRect(function (rect) {
boundingClientRect 的回调要用箭头函数

2021-07-08 11:44 UTC, Chen-jj requested changes

2021-07-08 11:44 UTC, Chen-jj commented on packages/taro-extend/src/jquery/zepto.js
> +            if (!rect) reject(new Error('offset error: ' + '#' + this[0].uid + ' query fail'))
应该直接 return，或者把 resolve 放入 else 块中。现在还是会执行 resolve 的。

2021-07-08 11:47 UTC, Chen-jj commented
@alexlees 十分抱歉现在才 review。PR 有两个问题，因为时间久远所有我们来改吧，十分感谢 PR ～

2021-07-08 11:47 UTC, closed without merging

2021-07-09 04:00 UTC, alexlees commented on packages/taro-extend/src/jquery/zepto.js
> +            if (!rect) reject(new Error('offset error: ' + '#' + this[0].uid + ' query fail'))
Promise A+ 规范会处理reject后的resolve

2021-07-09 05:44 UTC, alexlees commented
> @alexlees 十分抱歉现在才 review。PR 有两个问题，因为时间久远所有我们来改吧，十分感谢 PR ～

OK，抱歉，被关掉MR后还是有点抱怨，但是看到晚上11点还在为开源做事情还是很感动