fix(swan): View 标签支持 flex 布局
NervJS/taro pull request #9529
Opened 2021-06-11 17:18 UTC by SyMind

**这个 PR 做了什么?** (简要描述所做更改)

 对百度小程序 pure-view 进行有限深度的非递归渲染，已解决 View 标签 flex 布局异常的问题。

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #6015
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [x] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-06-12 10:40 UTC, SyMind commented
@Chen-jj 有时间看一下。

2021-06-29 11:44 UTC, bluescurry commented
@Chen-jj 辛苦看下这个PR，对兼容百度小程序来说真的很重要 🙏🏻

2021-07-02 02:24 UTC, SyMind commented
这个 pr 当前究竟有什么问题么？首先从框架方很难指望百度小程序会对此进行更新，而且实际已经证明了他们的对此事的优先级很低，所以从框架层面解决该问题我认为是很合理的，当前的这个 pr 有什么问题？

2021-07-02 06:29 UTC, tourze commented
同求合并

2021-07-08 15:59 UTC, Chen-jj requested changes

2021-07-08 15:59 UTC, Chen-jj commented on packages/shared/src/template.ts
> +        if (
这里的逻辑应该是 "不等于" 吧。

可以这样改，就不用加 swan 的判断了：

```js
// packages/taro-swan/src/template.ts
export class Template extends RecursiveTemplate {
  // ...
  protected createMiniComponents (components): any {
    const res = super.createMiniComponents(components)

    delete res['pure-view']
    delete res['static-view']

    return res
  }
}
```

2021-07-08 15:59 UTC, Chen-jj commented on packages/taro-runtime/src/constants.ts
> +export const SPECIAL_NODES = process.env.TARO_ENV === 'swan'
这里我加个 `hooks`，让开发者可以在端平台插件中修改。

2021-07-08 15:59 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +export function buildFlattenView (depth = 8): string {
`buildFlattenView` 可以直接作为 Tempalte 类的方法。

2021-07-08 15:59 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +`<view s-if="{{item.nn==='view'&&(item.st||item.cl)}}" hover-class="{{xs.b(item.hoverClass,'none')}}" hover-stop-propagation="{{xs.b(item.hoverStopPropagation,false)}}" hover-start-time="{{xs.b(item.
需要注释一下，如果 `view` 的属性或事件有修改，需要同步修改此处。

2021-07-08 15:59 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +`<view s-if="{{item.nn==='view'&&(item.st||item.cl)}}" hover-class="{{xs.b(item.hoverClass,'none')}}" hover-stop-propagation="{{xs.b(item.hoverStopPropagation,false)}}" hover-start-time="{{xs.b(item.
另外希望优化一下最终输出的缩进

![image](https://user-images.githubusercontent.com/11807297/124954215-70394280-e048-11eb-816a-5210d6aad016.png)

2021-07-08 16:03 UTC, Chen-jj requested changes

2021-07-08 16:03 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +      return buildFlattenView()
希望 swan 插件可以提供一个配置项用于修改 `buildFlattenView` 的参数。

2021-07-08 16:04 UTC, Chen-jj commented
@SyMind 十分抱歉，之前在忙鸿蒙的东西没有关注这个 PR。

思路十分正确，有些细微之处烦请修改一下，我这边也会尽快新增一个运行时 hooks 用于修改 `SPECIAL_NODES`。

明天会发 3.2 最后一个 patch 版本，此 PR 可能要跟 3.3 版本进行发布。

2021-07-09 06:35 UTC, w88975 commented
@Chen-jj 这个PR多久能merge呢, 目前开发百度小程序有该问题

2021-07-09 07:01 UTC, Chen-jj commented
@w88975 下周ok

2021-07-13 12:56 UTC, bluescurry commented
@SyMind 辛苦看看那些review的问题吧，尽快能修复这个问题~

2021-07-15 07:00 UTC, SyMind commented
@bluescurry 本周实在是太忙了，周五搞。

2021-07-18 14:24 UTC, SyMind commented
@Chen-jj 应该是解决了，麻烦有时间看一下。

2021-07-20 03:35 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +      return buildFlattenView()
@SyMind 是作为 `@tarojs/plugin-platform-swan` 插件的参数，现在是作为 Taro 编译配置的参数

2021-07-20 03:36 UTC, Chen-jj commented on packages/shared/src/template.ts
> +        if (
@SyMind 仍未修改。

2021-07-20 03:42 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +export function buildFlattenView (depth = 8): string {
@SyMind 可能是我没说清楚，是作为 `@tarojs/plugin-platform-swan` 的 `Template` 类的方法。现在直接嵌入到基类 `RecursiveTemplate` 中，这是不对的。

2021-07-20 03:44 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +`<view s-if="{{item.nn==='view'&&(item.st||item.cl)}}" hover-class="{{xs.b(item.hoverClass,'none')}}" hover-stop-propagation="{{xs.b(item.hoverStopPropagation,false)}}" hover-start-time="{{xs.b(item.
@SyMind 未添加注释

2021-07-20 03:46 UTC, Chen-jj commented
@SyMind 可能是没沟通清楚，整体的方向错了。这次的修改把方法放到基类、把配置放到全局了，但这是不对的，只是百度小程序需要这些东西，要尽量把它们放小程序插件里。麻烦再按评论修改一下。

2021-07-20 13:28 UTC, SyMind commented
@Chen-jj 更改完毕

2021-07-21 02:54 UTC, Chen-jj approved these changes

2021-07-21 02:54 UTC, Chen-jj commented on packages/shared/src/utils.ts
> +export function indent (str: string, size: number): string {
`indent` 放 `@tarojs/plugin-platform-swan` 里，不需要修改 `shared/src/utils.ts`

2021-07-21 02:54 UTC, Chen-jj commented on packages/shared/src/template.ts
> +import { toCamelCase, toKebabCase, toDashed, hasOwn, indent } from './utils'
`indent` 放 `@tarojs/plugin-platform-swan` 里，不需要修改 `shared/src/template.ts`

2021-07-21 02:59 UTC, SyMind commented on packages/shared/src/template.ts
> +import { toCamelCase, toKebabCase, toDashed, hasOwn, indent } from './utils'
我的看法是需要的，你可以看一下 indent 的用处，在 template 会有如下的代码。

```jsx
<block ${Adapter.for}="{{i.${Shortcuts.Childnodes}}}" ${Adapter.key}="uid">
      ${indent(child, 8)}
</block>
```

如果此时 child 是多行文本，例如：

```jsx
<div>
      hello, world
</div>
```

传入后得到的字符串为如下：

```jsx
<block ${Adapter.for}="{{i.${Shortcuts.Childnodes}}}" ${Adapter.key}="uid">
      <div>
      hello, world
</div>
</block>
```

2021-07-21 03:00 UTC, SyMind commented on packages/shared/src/template.ts
> +import { toCamelCase, toKebabCase, toDashed, hasOwn, indent } from './utils'
我想在 template 中处理这种多行文本缩进问题是合理的。

2021-07-21 03:16 UTC, merged

2021-07-28 08:35 UTC, lifeng1893 commented
非view标签还是存在flex: 1无效的问题，taro版本v3.3.1。暂时看了button和input标签的flex: 1没有生效

2021-07-28 09:38 UTC, SyMind commented
@lifeng1893 这个问题本质还是由于百度小程序的渲染 bug 导致，当前采取的也是一种启发式的解决方案，具体讨论如下：

2021-07-29 01:30 UTC, lifeng1893 commented
@SyMind 我个人认为button和input需要支持下，这两个标签的能力用view标签替代不了

2021-07-29 02:05 UTC, SyMind commented
@lifeng1893 https://github.com/NervJS/taro/pull/9884 已经在这个 pr 中添加了对 button、input、text 标签的支持。

2021-08-20 09:02 UTC, lyrbet commented
感觉其他标签处理起来很复杂，有种曲线救国的方法就是用grid。
```

2021-08-20 09:02 UTC, lyrbet commented
感觉其他标签处理起来很复杂，有种曲线救国的方法就是用grid。

2021-08-20 09:24 UTC, lyrbet commented
@lifeng1893，其实@SyMind 大佬适配了View的问题已经解决大部分情况了，感觉其他标签处理起来很复杂，有种曲线救国的方法就是用grid。

比如

```scss

.container {
  display: flex;

  .box1 {
    flex: 1;
  }

  .box2 {
    width: 20px;
  }
}

```

```scss

.container {
  @if $ENV == 'swan' {
    display: grid;
    grid-template-columns: 1fr 20px;
    grid-template-areas:
        "box1-area"
        "box2-area";

    .box1 {
      grid-area: box1-area;
    }

    .box2 {
      grid-area: box2-area;
    }
  } @else {
    display: flex;
    .box1 {
      flex: 1;
    }
    .box2 {
      width: 20px;
    }
  }

}

```

Env 需要配置

```js
  sass:{
  data: "$ENV: " + process.env.Env + ";"
}
```

2021-08-23 07:46 UTC, lifeng1893 commented
@lyrbet 我这边试试，感谢

2021-12-13 09:23 UTC, guaizi149 commented
@Chen-jj @SyMind  ScrollView组件的flex布局是不是也可以考虑支持下？

2022-11-14 07:17 UTC, hisanshao commented
快手小程序也有一样的问题