百度小程序中 swiper-item、cover-view 和 cover-image 组件使用非递归方式渲染
NervJS/taro pull request #9884
Opened 2021-07-24 12:19 UTC by SyMind

**这个 PR 做了什么?** (简要描述所做更改)

百度小程序中 swiper-item、cover-view 和 cover-image 组件使用非递归方式渲染

**这个 PR 是什么类型?** (至少选择一个)

- [x] 错误修复(Bugfix) issue id #6015
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [x] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2021-07-25 23:36 UTC, SyMind commented
@Chen-jj 看一下。

2021-08-12 06:58 UTC, Chen-jj requested changes

2021-08-12 06:58 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +<input s-elif="{{item.nn==='text'&&(item.st||item.cl)}}}}" id="{{item.uid}}" ${this.buildFlattenNodeAttributes('input')} />
此外，input 应该分为 focus 和 blur 两种，如果比较麻烦，可以先不做

2021-08-12 06:58 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +      case 'input':
`input` `textarea` 被配置了 `voidElements`，所以这里对它们的模板没有用处

2021-08-12 06:58 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +<block s-else>{{item.v}}</block>`
这里应该是 `<block s-else><template is="{{xs.e(0)}}" data="{{{i:item}}}" /></block>`，现在的处理就只能渲染文本节点。

2021-08-12 07:05 UTC, Chen-jj commented
@SyMind 增加了其他组件的支持后，情况是相当复杂的，有很多排列组合的场景都需要测试，请按上述评论进行修改，并在本地先进行尽量完备的测试。

这是我的测试用例，可能还有一些考虑不全的地方，请修改后回复一下你的测试用例：

```js
import { Component } from 'react'
import { View, Input, Text, Button, Canvas, CoverView, CoverImage, Swiper, SwiperItem } from '@tarojs/components'
import './index.scss'

export default class Index extends Component {
  render () {
    return (
      <View>
        <View className='box'>
          <Text className='item'>s-text 1</Text>
          <Text className='item'>s-text 2</Text>
        </View>
        <View className='box'>
          <Text onClick={() => {}} className='item'>text 1</Text>
          <Text onClick={() => {}} className='item'>text 2</Text>
        </View>
        <View className='box'>
          <Button className='item'>Button 1</Button>
          <Button className='item'>Button 2</Button>
        </View>
        <View className='box'>
          <Input type='text' placeholder='A' onClick={() => {}} className='item'>A</Input>
          <Input type='text' placeholder='A1' onClick={() => {}} className='item'>Hello world!</Input>
        </View>
        <Canvas canvasId='my'>
          <CoverView className='box'>
            <CoverView className='item'>1</CoverView>
            <CoverView className='item'>2</CoverView>
            <CoverImage className='item'></CoverImage>
            <View>
              <Text>3</Text>
            </View>
          </CoverView>
        </Canvas>
      </View>
    )
  }
}
```

2021-08-12 08:52 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
>  <block s-else>
`swiper` 也麻烦加一下哈

2021-08-12 09:12 UTC, Chen-jj requested changes

2021-08-12 09:12 UTC, Chen-jj commented on packages/taro-swan/src/template.ts
> +  modifyLoopContainer = (children: string, nodeName: string): string => {
这段不需要修改，因为 **swiper > swiper-item + swiper-item** 这种情况就是不支持 flex 的。

在 `buildFlattenView` 里处理 **view > swiper + swiper** 这种情况即可。

2021-08-28 13:26 UTC, closed without merging